## 1.0.0
-- FILE_SERVER_DOCUMENT definition
 CREATE TABLE "FILE_SERVER_DOCUMENT"
    (
    "ID" NUMBER(19,0),
 	"FILE_PATH" VARCHAR2(1024 CHAR),
 	"FILE_NAME" VARCHAR2(256 CHAR),
 	"FILE_ORG_TYPE" VARCHAR2(1024 CHAR),
 	"FILE_SIZE" NUMBER(19,0),
 	"LINK_ID" NUMBER(19,0),
 	"FILE_TYPE" VARCHAR2(510 CHAR),
 	"MAIN_MODEL_ID" NUMBER(19,0),
 	"SIZE_DIS" VARCHAR2(256 CHAR),
 	"MEMO" VARCHAR2(510 CHAR),
 	"PROPERTY_CODE" VARCHAR2(510 CHAR),
 	"SHOW_TYPE" VARCHAR2(510 CHAR),
 	"OPENER" VARCHAR2(510 CHAR),
 	"OPEN_TIME" TIMESTAMP (6),
 	"DEPLOYMENT_ID" NUMBER(19,0),
 	"ACTIVITY_NAME" VARCHAR2(510 CHAR),
 	"TASK_DESCRIPTION" VARCHAR2(510 CHAR),
 	"FILE_ICON" VARCHAR2(510 CHAR),
 	"IS_FILE_VIEW" NUMBER(1,0),
 	"DOC_CONTENT" VARCHAR2(510 CHAR),
 	"DOC_SUMMARY" VARCHAR2(510 CHAR),
 	"CONVERT_STATUS" VARCHAR2(510 CHAR),
 	"REASON" VARCHAR2(510 CHAR),
 	"CONVERT_PATH" VARCHAR2(510 CHAR),
 	"DOWNLOAD_TIMES" NUMBER(19,0),
 	"PREVIEW_TIMES" NUMBER(19,0),
 	"VERSION" NUMBER(*,0) DEFAULT 0,
 	"VALID" NUMBER(*,0) DEFAULT 1,
    "CREATOR" VARCHAR(32) ,
    "MODIFIER" VARCHAR(32) ,
 	"CREATE_TIME" TIMESTAMP (6),
 	"MODIFY_TIME" TIMESTAMP (6),
 	"DELETE_STAFF_ID" NUMBER(19,0),
 	"MODIFY_STAFF_ID" NUMBER(19,0),
 	"CREATE_STAFF_ID" NUMBER(19,0),
 	"DELETE_TIME" TIMESTAMP (6),
 	 PRIMARY KEY ("ID")
    ) ;
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."VERSION" IS '版本信息';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."DELETE_TIME" IS '删除时间';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."MODIFY_TIME" IS '修改时间';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."CREATE_TIME" IS '创建时间';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."DELETE_STAFF_ID" IS '删除者';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."MODIFY_STAFF_ID" IS '修改者';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."CREATE_STAFF_ID" IS '创建者';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."VALID" IS '是否有效';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."CONVERT_PATH" IS '转换后的文件路径';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."REASON" IS '不支持转换的原因';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."CONVERT_STATUS" IS '附件转换状态';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."TASK_DESCRIPTION" IS '活动描述';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."ACTIVITY_NAME" IS '活动名称';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."DEPLOYMENT_ID" IS '流程ID';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."OPEN_TIME" IS '上次打开时间';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."OPENER" IS '首次打开用户';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."SHOW_TYPE" IS '显示类型';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."FILE_TYPE" IS '文件类型   pic：图片字段 attachment:普通附件  office:文档控件';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."PROPERTY_CODE" IS '字段CODE';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."FILE_SIZE" IS '大小';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."MEMO" IS '备注';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."MAIN_MODEL_ID" IS '主关联模型的ID，如是表单 则为tableInfoId';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."LINK_ID" IS '对应表单ID';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."FILE_ORG_TYPE" IS '附件类型';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."FILE_PATH" IS '路径';
      COMMENT ON COLUMN "FILE_SERVER_DOCUMENT"."FILE_NAME" IS '名称';
      COMMENT ON TABLE "FILE_SERVER_DOCUMENT"  IS '附件表';
      
-- FILE_SERVER_DOCUMENT_DOWN_INFO definition

CREATE TABLE "FILE_SERVER_DOCUMENT_DOWN_INFO"
   (	"ID" NUMBER(19,0),
    "DOCUMENT_ID" NUMBER(19,0),
	"RECORD_TYPE" VARCHAR2(100 CHAR),
	"IP_ADDR" VARCHAR2(100 CHAR),
	"DOWNLOAD_TIME" TIMESTAMP (6),
	"DOWNLOAD_STAFF_ID" NUMBER(19,0),
	"VALID" NUMBER(*,0) DEFAULT 1,
    "MODIFIER" VARCHAR(32) ,
    "CREATOR" VARCHAR(32) ,
    "CREATE_TIME" TIMESTAMP,
    "MODIFY_TIME" TIMESTAMP,
    "DELETE_TIME" TIMESTAMP ,
    "VERSION" NUMBER(*,0) DEFAULT 0,
    "CREATE_STAFF_ID" NUMBER(20, 0)  ,
    "MODIFY_STAFF_ID" NUMBER(20, 0)  ,
	 PRIMARY KEY ("ID")
   ) ;
   COMMENT ON COLUMN "FILE_SERVER_DOCUMENT_DOWN_INFO"."VERSION" IS '版本信息';
   COMMENT ON COLUMN "FILE_SERVER_DOCUMENT_DOWN_INFO"."RECORD_TYPE" IS '记录类型';
   COMMENT ON COLUMN "FILE_SERVER_DOCUMENT_DOWN_INFO"."IP_ADDR" IS '下载IP';
   COMMENT ON COLUMN "FILE_SERVER_DOCUMENT_DOWN_INFO"."DOWNLOAD_TIME" IS '下载时间';
   COMMENT ON COLUMN "FILE_SERVER_DOCUMENT_DOWN_INFO"."DOWNLOAD_STAFF_ID" IS '下载人';
   COMMENT ON COLUMN "FILE_SERVER_DOCUMENT_DOWN_INFO"."DOCUMENT_ID" IS '附件ID';
   COMMENT ON TABLE "FILE_SERVER_DOCUMENT_DOWN_INFO"  IS '附件下载信息';

## 1.0.1
SELECT ID FROM FILE_SERVER_DOCUMENT;

## 1.0.2
ALTER TABLE FILE_SERVER_DOCUMENT ADD TENANT_ID VARCHAR2(256 CHAR);
UPDATE FILE_SERVER_DOCUMENT SET TENANT_ID='dtbucket' WHERE TENANT_ID IS NULL;

## 1.0.3
ALTER TABLE FILE_SERVER_DOCUMENT DROP COLUMN TENANT_ID;