/**
 * Copyright (C) 2011 ZHEJIANG SUPCON TECHNOLOGY CO.,LTD. 
 * All rights reserved.
 */
package com.supcon.supfusion.configuration.services.exceptions;


import lombok.Data;

@Data
public class EcException extends RuntimeException {

	public enum Code {
		SQL_ERROR, // 查询时发生的其他SQLException
		ID_NOT_NULL,
		ID_MUST_NULL,
		OBJECT_NULL,
		OBJECT_HAVE_BEAN_DELETED,
		CODE_NOT_NULL,
		URL_NOT_NULL,
		URL_FORMAT_ERROR,
		NAME_NOT_NULL,
		UNIQUEURL,
		UNIQUECODE,
		UNIQUEISMAIN,
		UNIQUENAME,
		UNIQUESHORTNAME,
		UNIQUESTAFFNAME,
		USER_SHOULD_BE_UNIQUE,
		STAFF_NOT_EXIST,
		DEPARTMENT_NOT_EXIST,
		COMPANY_NOT_EXIST,
		TRANSFORM_ERROR,
		OTHER,
		CURR_NODE_IS_NOT_LEAF,
		TREE_NODE_CAN_NOT_MOVE,
		ROLE_TREE_NODE_CAN_NOT_MOVE,
		ROLE_CURR_NODE_IS_NOT_LEAF,
		ASSO_WITH_POSITION,
		HAS_CHILD_DEPARTMENT,
		HAS_CHILD_POSITION,
		HAS_CHILD_ROLE,
		ASSO_WITH_POSITIONWORK,
		STAFF_ALREADY_HAVE_USER,
		ASSO_WITH_ROLEUSER,
		USERNAME_EXISTED,
		UNIQUEKEY,
		UNIQUEKEY_NOT_UNIQUE,
		MENUINFO_NOT_NULL_STILL_EXIST_OTHER,
		MODULE_MENUINFO_CODE_EXIST,
		MENUINFO_CAN_NOT_MOVE,
		KEY_NOT_NULL,
		TOO_LONG,
		MODEL_NAME_TOO_LONG,
		ROOMALREADYEXISTS,
		MEETINGREADYCANCEL,
		KEY,
		NO_PERMISSION,
		NO_INTERNATION_KEY,
		ASS_NOT_DELETE,
		ASS_PROPERTY_NOT_SELECTED,
		ASS_BY_DATACLASSIFIC,
		MNECODEVIEW_ONLY,
		PENDING_NOT_FOUND,
		MODULE_IS_CONTROL,
		CONTRAINT_BY_OTHER,
		REFERENCE_VIEW,
		NO_USERS_PEDNING,
		CONTRAINT_BY_OTHER_MODULE,
		CONTRAINT_CODE,
		CONTRAINT_INTERNATION_KEY,
		SYNC_FAILURE,
		SYNC_NO_URL,
		IS_NOT_SYSADMIN,
		NO_FIELDPERMISSION,
		DOCUMENT_ERROR,
		DIFFERENT_USERID,
		ASS_BY_DATAGROUP,
		ASS_BY_DATAGRID,
		ASS_BY_VIEW,
		ASS_BY_PROPERTY,
		ASS_BY_MODEL,
		ASS_BY_ENTITY,
		ASS_BY_MODULE,
		ASS_BY_SHADOWVIEW,
		ASS_BY_BUTTON,
		ASS_BY_REFERENCEVIEW,
		ASS_BY_LAYOUT,
		USED_BY_BATCHCCONTROLPRINT,
		PENDING_DEALED,
		NOSAME_MODULE_IMPORT,
		MODULE_IMPORTED_EXISTS,
		PENDING_HAS_EXIST,
		TASK_NOT_ALLOW_PROXY,
		PENDING_HAS_HANGUP,
		PROCESS_IS_NOT_EXIST,
		TABLE_IS_NOT_EXIST,
		MAX_LAY_NO,
		USED_BY_VIEW,
		USERD_USER_PEMISSION,
		PRECOMPILEERROR,
		PROCESS_IS_NOT_EXIST_AND_NEW_DEPLOY,
		WORKFLOW_PERMISSIONCHANGE_ERROR,
		FILE_NOT_FOUND,
		SCRIPT_NOT_FOUND,
		NO_COMPANY_PERMISSION,
		LANGUAGE_NOT_FORMAT,
		INFOSET_COL_KEY,
		PUBLISH_FAILURE,
		POSITION_IS_EXIST,
		NO_SCRIPT,
		SYSTEM_ERROR,
		SELECT_NOT_SELF,
		WEBMSGUSER_NOT_EXIST,
		WEBMSG_NOT_UNIT,
		GroupUnit_HAS_NOT_USER,
		WEBMSG_NOT_COMPANY,
		COMPANY_NOT_EXIST_USER,
		WEBMSG_NOT_DEPARTMENT,
		DEPARTMENT_NOT_EXIST_USER,
		WEBMSG_NOT_USER,
		WEBMSG_RECEIVER_NOT_EXIST,
		WEBMSG_IS_NULL,
		WEBMSG_NOT_REPLY,
		//		  WEBMSG_NOT_GROUP_PERMISSION,
//		  WEBMSG_NOT_COMPANY_PERMISSION,
//		  WEBMSG_CAN_NOT_OTHER_COMPANY,
//		  WEBMSG_CAN_NOT_OTHER_DEPARTMENT,
//		  WEBMSG_ALLOW_CURRENT_COMPANY,
//		  WEBMSG_NOT_DEPARTMENT_PERMISSION,
		WEBMSG_NOT_SYSTEMMSG_PERMISSION,
		WEBMSG_NOT_SENDER_YOUSELF,
		WEBMSG_USER_HAS_SETTING,
		WEBMSG_NOT_SETTING,
		ASS_BY_TASK,
		UNIQUE_CONSTRAINT,
		DEPENDENT_MODULE_NOT_EXISTS,
		DEPENDENT_ENTITY_NOT_EXISTS,
		UNIQUE_FIELD,
		UNIQUE_FIELD_BAPCODE,
		UNIQUEOFFICE,
		UNIQUE_SUMMARY,
		MESSAGE_SEND_FAIL,
		MOUDLE_CYCLE_DEPEND,
		DOWNLOAD_NO_PERMISSION,
		UNIQUE_MODEL_NAME,
		PROJECT_ENV_CAN_NOT_MODIFY_PRODUCT_ELEMENT,
		PRODUCT_ENV_CAN_NOT_MODIFY_PROJECT_ELEMENT,
		NO_PENDING,
		SQL_DEAL_TIMEOUT,
		SEND_ACTIVEMQ_MESSAGE_ERROR,
		FILE_UPLOAD_ERROR,
		HAS_NOT_FINISHED_DEPLOY,
		EXPECTED_CONSIGN_CIRCULAR_REFERENCE,
		RESULT_COUNT_EXCEED_MAX_PAGE_SIZE,
		FILE_MAX_SIZE_ERROR,
		/*撤回*/
		/**
		 * 待办已被撤回
		 */
		RECALL_ERROR_RECALLED,
		/**
		 * 待办已过撤回时效
		 */
		RECALL_ERROR_TIMEOUT,
		/**
		 * 待办已被处理
		 */
		RECALL_ERROR_DEALED,
		/**
		 * 用户未处理过该单据
		 */
		RECALL_ERROR_HAD_NOT_DEALED,
		/**
		 * 非普通活动
		 */
		RECALL_ERROR_NOT_NORMAL_ACTIVITY,
		/**
		 * 单据被挂起，无法撤回
		 */
		RECALL_ERROR_NOT_HANGUP,
		/**
		 * 撤回功能已取消，无法撤回
		 */
		RECALL_ERROR_CLOSED,
		STAFF_CODE_UNIQUECODE,
		/**
		 * 预期委托循环依赖
		 */
		EXPECTED_CONSINER_LOOP,
		DELETE_MAIN_LIST,
		EXTENSION_POINT_EXIST,
		EXTENSION_POINT_SORT_EXIST,
		SYNC_NONE_SECURITYID,
		SYNC_NONE_SECURITYKEY,
		SYNC_SECURITYKEY_NOT_MATCH,
		SYNC_SECURITYKEY_EMPTY,
		SYNC_ERROR,
		VIEW_NAME_KEY,
		NO_COMPANY_ADMIN,
		EMPTY_USER_PASSWORD,
		SAME_MODEL_NAME_ERROR,
		REFERVIEW_NOT_FOUND,
		TEMPLATE_IMPORT_LOSS_MODELCODE,
		TREE_NODE_CAN_NOT_COPY,
		/**
		 * 第三方页面无权限访问
		 */
		THIRD_PAGE_NO_PERMISSION,
		PSW_MUST_DIFFERENT_WITH_NAME,
		USER_TOKEN_SN_USED,
		DYNAMICODE_TOKEN_BIND_FAILED,
		DYNAMICODE_TOKEN_UNBIND_FAILED,
		DYNAMICODE_TOKEN_GET_ACTIVE_TOKEN_CODE_ERROR,
		DYNAMICODE_TOKEN_ACTIVE_TOKEN_ERROR,
		PASSWORD_FORMAT_ERROR,
		SYSTEMCODE_SPECIAL_CHAR_ERROR,
		HAS_CHILD_COMPANY,
		/**
		 * 人员没有关联用户
		 */
		STAFF_USER_NOT_EXISTED,
		ISNOTLEAF,
		ISNOTCOPYTOBAPMENU,
		UNIQUE_MAINASSOCIATED,
		/**
		 * 上载导入导出模板xml出错
		 */
		IMPORT_TEMPLATE_FILE_DEAL_ERROR,
		/**
		 * 上载portlet出错
		 */
		IMPORT_PORTLET_FILE_ERROR,
		/**
		 * SQL模型相关报错
		 */
		SQLCANNOTNULL,
		ONLYSELECT,
		SQLERROR,
		SQLCOLUMNREPEAT,
		SQL_COlUMN_NAME_ERROR,
		CHECKBUSSINESSKEY,
		CHECKMAINDISPLAY,
		NOBUSSINESSKEY,
		NOMAINDISPLAY,
		TYPECANNOTINHERENT,
		MODELVIEWCANNOTSQLERROR,
		CANNOTSELECTALL,
		ISMAINASSOCIATEDONLYONE,
		CREATE_VIEW_ERROR,
		/**
		 * 上载任务调度模板xml出错
		 */
		SCHEDULER_TEMPLATE_FILE_DEAL_ERROR,
		NO_ROLE_FIND,
		/*
		 * 网络打印相关
		 */
		NO_PRINTSERVICE_CONFIG,
		CANNOT_CONNECT_PRINTSERVICE,
		ADVQUERYCONDITION_TYPE_ERROR,
		VIEW_NO_ECHARTS_ERROR,
		LEAD_INTO,
		DEPEND_INTO,
		FILE_EXISTS;
		public String toMessageKey() {
			return "ec.exceptions." + this.name();
		}
	}

	private Code code;
	private String messageKey;
	private Object[] args;

	public EcException(String message) {
		super(message);
	}

	public EcException(Code code) {
		this.code = code;
	}

	public EcException(Code code, Object... args) {
		this.code = code;
		this.args = args;
	}

	public EcException(String messageKey, Object... args) {
		this.messageKey = messageKey;
		this.args = args;
	}

	public EcException(Throwable cause) {
		super(cause);
	}

	public EcException(String message, Throwable cause) {
		super(message, cause);
	}

}
