-- Critical-table checksum template.
-- This file is intentionally manual because each business table needs a stable
-- primary key and business-significant columns.
--
-- Example:
-- select
--   'public.org_department' as table_name,
--   count(*) as row_count,
--   md5(coalesce(string_agg(
--     concat_ws('|', id, code, name, valid),
--     E'\n' order by id
--   ), '')) as checksum,
--   'OK' as status
-- from public.org_department;
--
-- Rules:
-- - Order by a stable primary key or deterministic business key.
-- - Exclude volatile audit columns unless they are part of the acceptance.
-- - Output table_name, row_count, checksum and status as tab-separated columns.
-- - Compare source and target outputs with scripts/compare-checksums.py in the
--   rehearsal report.
