## 1.0.0
/*====================================================*/
/* TABLE: 规则表                                       */
/*====================================================*/
CREATE TABLE COUNTER_RULE  (
  ID             NUMBER(20,0) NOT NULL ,--COMMENT '规则ID',
  RULE_NAME      VARCHAR2(128) NOT NULL ,--COMMENT '规则名称',
  VALID          NUMBER(3,0) DEFAULT 0 ,--COMMENT '是否失效',
  CREATOR        VARCHAR2(32) DEFAULT 'SYSTEM' ,--COMMENT '创建者',
  CREATE_TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,--COMMENT '创建时间',
  CREATE_STAFF_ID NUMBER(20,0) DEFAULT 0 ,--COMMENT '创建者ID',
  MODIFIER       VARCHAR2(32) ,--COMMENT '修改人',
  MODIFY_TIME    TIMESTAMP ,--COMMENT '修改时间',
  MODIFY_STAFF_ID NUMBER(20,0) ,--COMMENT '修改者ID',
  PRIMARY KEY (ID)
);
COMMENT ON TABLE COUNTER_RULE IS '规则表';
COMMENT ON COLUMN COUNTER_RULE.ID IS '规则ID';
COMMENT ON COLUMN COUNTER_RULE.RULE_NAME IS '规则名称';
COMMENT ON COLUMN COUNTER_RULE.VALID IS '是否失效';
COMMENT ON COLUMN COUNTER_RULE.CREATOR IS '创建者';
COMMENT ON COLUMN COUNTER_RULE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN COUNTER_RULE.CREATE_STAFF_ID IS '创建者ID';
COMMENT ON COLUMN COUNTER_RULE.MODIFIER IS '修改人';
COMMENT ON COLUMN COUNTER_RULE.MODIFY_TIME IS '修改时间';
COMMENT ON COLUMN COUNTER_RULE.MODIFY_STAFF_ID IS '修改者ID';



/*====================================================*/
/* TABLE: 规则子表                                     */
/*====================================================*/
 CREATE TABLE COUNTER_RULE_FIELD  (
   ID             NUMBER(20,0) NOT NULL ,--COMMENT '字段ID',
   RULE_ID        NUMBER(20,0) NOT NULL ,--COMMENT '规则ID',
   FIELD_TYPE     NUMBER(3,0) NOT NULL ,--COMMENT '字段类型：0=DATE=日期 1=AUTO=自增 2=CUSTOM=自定义 3=PROPERTY=实体字段 4=INHERENT=实体属性 5=SEPARATOR=分隔符',
   THECASE        NUMBER(3,0) DEFAULT 0 ,--COMMENT '大小写样式：0=ORIGINAL=保持原样 1=UPPER=大写 2=LOWER=小写',
   FIELD_VALUE    VARCHAR2(64) NOT NULL ,--COMMENT '字段值：当FIELDTYPE=0时为SYSTEMDATE',
   DATE_FORMATTER VARCHAR2(32) DEFAULT 'UNKNOWN' ,--COMMENT '日期格式化：YY、YYYY、YYYYMM、YYYYMMDD',
   AUTO_LENGTH    NUMBER(3,0) DEFAULT 0 ,--COMMENT '自增长度: > 1',
   AUTO_TYPE      NUMBER(3,0) DEFAULT 0 ,--COMMENT '自增类型：0=DATE=按日期 1=CODE=按编码',
   AUTO_DATE_RULE NUMBER(3,0) DEFAULT 0 ,--COMMENT '按日期自增规则：0=DAILY=按天 1=MONTHLY=按月 2=YEARLY=按年',
   FIELD_ORDER    NUMBER(10,0) DEFAULT 1 ,--COMMENT '字段排序码：>=1',
   VALID          NUMBER(3,0) DEFAULT 0 ,--COMMENT '是否失效',
   CREATOR        VARCHAR2(32) DEFAULT 'SYSTEM' ,--COMMENT '创建者',
   CREATE_TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,--COMMENT '创建时间',
   CREATE_STAFF_ID NUMBER(20,0) DEFAULT 0 ,--COMMENT '创建者ID',
   MODIFIER       VARCHAR2(32) ,--COMMENT '修改人',
   MODIFY_TIME    TIMESTAMP ,--COMMENT '修改时间',
   MODIFY_STAFF_ID NUMBER(20,0) ,--COMMENT '修改者ID',
   PRIMARY KEY (ID)
  );
  COMMENT ON TABLE COUNTER_RULE_FIELD IS '规则子表';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.ID IS '字段ID';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.RULE_ID IS '规则ID';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.FIELD_TYPE IS '字段类型：0=DATE=日期 1=AUTO=自增 2=CUSTOM=自定义 3=PROPERTY=实体字段 4=INHERENT=实体属性 5=SEPARATOR=分隔符';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.THECASE IS '大小写样式：0=ORIGINAL=保持原样 1=UPPER=大写 2=LOWER=小写';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.FIELD_VALUE IS '字段值：当FIELDTYPE=0时为SYSTEMDATE';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.DATE_FORMATTER IS '日期格式化：YY、YYYY、YYYYMM、YYYYMMDD';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.AUTO_LENGTH IS '自增长度: > 1';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.AUTO_TYPE IS '自增类型：0=DATE=按日期 1=CODE=按编码';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.AUTO_DATE_RULE IS '按日期自增规则：0=DAILY=按天 1=MONTHLY=按月 2=YEARLY=按年';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.FIELD_ORDER IS '字段排序码：>=1';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.VALID IS '是否失效';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.CREATOR IS '创建者';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.CREATE_TIME IS '创建时间';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.CREATE_STAFF_ID IS '创建者ID';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.MODIFIER IS '修改人';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.MODIFY_TIME IS '修改时间';
  COMMENT ON COLUMN COUNTER_RULE_FIELD.MODIFY_STAFF_ID IS '修改者ID';
  CREATE INDEX IDX_COUNTER_RULE_FIELD ON COUNTER_RULE_FIELD(RULE_ID,VALID);

/*====================================================*/
/* TABLE: 规则序号表                                   */
/*====================================================*/
CREATE TABLE COUNTER_RULE_SEQUENCE (
ID             NUMBER(20,0) NOT NULL ,--COMMENT 'ID',
RULE_ID        NUMBER(20,0) NOT NULL ,--COMMENT '规则ID',
RULE_FIELD_ID  NUMBER(20,0) NOT NULL ,--COMMENT '规则序号字段ID',
SEQ_REFERENCE  VARCHAR2(128) NOT NULL ,--COMMENT '序号参照值：即序号是依照其滚动生成的',
SEQ_NO         NUMBER(20,0) NOT NULL ,--COMMENT '当前序号值',
LAST_BATCH_ID  NUMBER(20,0) NOT NULL ,--COMMENT '最后一次申请的批次ID',
CREATOR        VARCHAR2(32) DEFAULT 'SYSTEM' ,--COMMENT '创建者',
CREATE_TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,--COMMENT '创建时间',
CREATE_STAFF_ID NUMBER(20,0) DEFAULT 0 ,--COMMENT '创建者ID',
MODIFIER       VARCHAR2(32) ,--COMMENT '修改人',
MODIFY_TIME    TIMESTAMP ,--COMMENT '修改时间',
MODIFY_STAFF_ID NUMBER(20,0) ,--COMMENT '修改者ID',
PRIMARY KEY (ID)
);
  COMMENT ON TABLE COUNTER_RULE_SEQUENCE IS '规则序号表';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.ID IS '主键ID';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.RULE_ID IS '规则ID';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.RULE_FIELD_ID IS '规则序号字段ID';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.SEQ_REFERENCE IS '序号参照值：即序号是依照其滚动生成的';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.SEQ_NO IS '当前序号值';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.LAST_BATCH_ID IS '最后一次申请的批次ID';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.CREATOR IS '创建者';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.CREATE_TIME IS '创建时间';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.CREATE_STAFF_ID IS '创建者ID';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.MODIFIER IS '修改人';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.MODIFY_TIME IS '修改时间';
  COMMENT ON COLUMN COUNTER_RULE_SEQUENCE.MODIFY_STAFF_ID IS '修改者ID';
  CREATE UNIQUE INDEX UDX_COUNTER_RULE_SEQ ON COUNTER_RULE_SEQUENCE(RULE_ID,SEQ_REFERENCE);


/*====================================================*/
/* TABLE: 申请批次表                                   */
/*====================================================*/
CREATE TABLE COUNTER_BATCH (
ID             NUMBER(20,0) NOT NULL ,--COMMENT '批次ID',
RULE_ID        NUMBER(20,0) NOT NULL ,--COMMENT '规则ID',
APPLY_COUNT    NUMBER(10,0) NOT NULL ,--COMMENT '申请数量：>=1',
CREATOR        VARCHAR2(32) DEFAULT 'SYSTEM' ,--COMMENT '创建者',
CREATE_TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,--COMMENT '创建时间',
CREATE_STAFF_ID NUMBER(20,0) DEFAULT 0 ,--COMMENT '创建者ID',
MODIFIER       VARCHAR2(32) ,--COMMENT '修改人',
MODIFY_TIME    TIMESTAMP ,--COMMENT '修改时间',
MODIFY_STAFF_ID NUMBER(20,0) ,--COMMENT '修改者ID',
CONSTRAINT PK_COUNTER_BATCH PRIMARY KEY (ID)
);

  COMMENT ON TABLE COUNTER_BATCH IS '申请批次表';
  COMMENT ON COLUMN COUNTER_BATCH.ID IS '批次ID';
  COMMENT ON COLUMN COUNTER_BATCH.RULE_ID IS '规则ID';
  COMMENT ON COLUMN COUNTER_BATCH.APPLY_COUNT IS '申请数量：>=1';
  COMMENT ON COLUMN COUNTER_BATCH.CREATOR IS '创建者';
  COMMENT ON COLUMN COUNTER_BATCH.CREATE_TIME IS '创建时间';
  COMMENT ON COLUMN COUNTER_BATCH.CREATE_STAFF_ID IS '创建者ID';
  COMMENT ON COLUMN COUNTER_BATCH.MODIFIER IS '修改人';
  COMMENT ON COLUMN COUNTER_BATCH.MODIFY_TIME IS '修改时间';
  COMMENT ON COLUMN COUNTER_BATCH.MODIFY_STAFF_ID IS '修改者ID';
  CREATE INDEX IDX_COUNTER_BATCH ON COUNTER_BATCH(RULE_ID);


/*====================================================*/
/* TABLE: 申请批次字段参数表                            */
/*====================================================*/
CREATE TABLE COUNTER_BATCH_PARAM (
ID                 NUMBER(20,0) NOT NULL ,--COMMENT 'ID',
BATCH_ID           NUMBER(20,0) NOT NULL ,--COMMENT '批次ID',
RULE_FIELD_ID      NUMBER(20,0) NOT NULL ,--COMMENT '规则字段ID',
RULE_FIELD_VALUE   VARCHAR2(128) NOT NULL ,--COMMENT '规则字段值',
CREATOR            VARCHAR2(32) DEFAULT 'SYSTEM' ,--COMMENT '创建者',
CREATE_TIME        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,--COMMENT '创建时间',
CREATE_STAFF_ID    NUMBER(20,0) DEFAULT 0 ,--COMMENT '创建者ID',
MODIFIER           VARCHAR2(32) ,--COMMENT '修改人',
MODIFY_TIME        TIMESTAMP ,--COMMENT '修改时间',
MODIFY_STAFF_ID    NUMBER(20,0) ,--COMMENT '修改者ID',
CONSTRAINT PK_COUNTER_BATCH_PARAM PRIMARY KEY (ID)
);
  COMMENT ON TABLE COUNTER_BATCH_PARAM IS '申请批次字段参数表';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.ID IS '主键ID';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.BATCH_ID IS '批次ID';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.RULE_FIELD_ID IS '规则字段ID';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.RULE_FIELD_VALUE IS '规则字段值';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.CREATOR IS '创建者';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.CREATE_TIME IS '创建时间';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.CREATE_STAFF_ID IS '创建者ID';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.MODIFIER IS '修改人';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.MODIFY_TIME IS '修改时间';
  COMMENT ON COLUMN COUNTER_BATCH_PARAM.MODIFY_STAFF_ID IS '修改者ID';
  CREATE INDEX IDX_COUNTER_BATCH_PARAM ON COUNTER_BATCH_PARAM(BATCH_ID);
