CREATE TABLE wom_produce_tasks (
    id BIGINT PRIMARY KEY,
    table_no VARCHAR(128),
    produce_batch_num VARCHAR(128),
    plan_num NUMERIC(20, 6),
    finish_num NUMERIC(20, 6),
    task_run_state VARCHAR(64),
    valid BOOLEAN DEFAULT TRUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wom_produce_task_exelog (
    id BIGINT PRIMARY KEY,
    task_id BIGINT NOT NULL,
    valid BOOLEAN DEFAULT TRUE
);

CREATE TABLE wom_mat_outpt_records (
    id BIGINT PRIMARY KEY,
    table_no VARCHAR(128),
    task_exelog_id BIGINT NOT NULL,
    report_num NUMERIC(20, 6),
    output_num NUMERIC(20, 6),
    mat_batch_num VARCHAR(128),
    produce_batch_num VARCHAR(128),
    material_id BIGINT,
    sync_state VARCHAR(64),
    valid BOOLEAN DEFAULT TRUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qcs_inspects (
    id BIGINT PRIMARY KEY,
    source_id BIGINT,
    valid BOOLEAN DEFAULT TRUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qcs_inspect_reports (
    id BIGINT PRIMARY KEY,
    inspect_id BIGINT,
    valid BOOLEAN DEFAULT TRUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE qcs_un_qlf_deals (
    id BIGINT PRIMARY KEY,
    report_id BIGINT,
    valid BOOLEAN DEFAULT TRUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wom_quality_quantity_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    request_id VARCHAR(128) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    task_id BIGINT NOT NULL,
    task_no VARCHAR(128),
    source_output_id BIGINT NOT NULL,
    source_output_no VARCHAR(128),
    batch_no VARCHAR(128),
    reported_quantity NUMERIC(20, 6) NOT NULL,
    good_quantity NUMERIC(20, 6) NOT NULL,
    bad_quantity NUMERIC(20, 6) NOT NULL,
    unit_code VARCHAR(64),
    reason_code VARCHAR(64) NOT NULL,
    reason_text VARCHAR(1000),
    qcs_inspect_id BIGINT,
    qcs_report_id BIGINT,
    qcs_deal_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT 'CONFIRMED',
    version BIGINT NOT NULL DEFAULT 0,
    wms_sync_state VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    wms_sync_message VARCHAR(1000),
    wms_synced_at TIMESTAMP WITH TIME ZONE,
    confirmed_by VARCHAR(128) NOT NULL,
    confirmed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reversal_reason VARCHAR(1000),
    reversed_by VARCHAR(128),
    reversed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_wom_quality_quantity_positive CHECK (
        reported_quantity > 0 AND good_quantity >= 0 AND bad_quantity > 0
        AND reported_quantity = good_quantity + bad_quantity
    ),
    CONSTRAINT ck_wom_quality_quantity_status CHECK (
        status IN ('CONFIRMED', 'REVERSAL_PENDING', 'REVERSED')
    ),
    CONSTRAINT ck_wom_quality_quantity_wms_sync CHECK (
        wms_sync_state IN ('PENDING', 'APPLIED', 'FAILED')
    )
);

CREATE UNIQUE INDEX uk_wom_quality_quantity_request
    ON wom_quality_quantity_reports (tenant_id, request_id);
CREATE UNIQUE INDEX uk_wom_quality_quantity_test_output
    ON wom_quality_quantity_reports (tenant_id, source_output_id, status);

CREATE TABLE wom_quality_quantity_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES wom_quality_quantity_reports(id) ON DELETE CASCADE,
    event_no BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    actor VARCHAR(128) NOT NULL,
    reason VARCHAR(1000),
    payload CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_wom_quality_quantity_event_type CHECK (
        event_type IN (
            'CONFIRMED', 'WMS_SYNC_APPLIED', 'WMS_SYNC_FAILED', 'QUALITY_LINKED',
            'REVERSAL_REQUESTED', 'REVERSED'
        )
    )
);

CREATE UNIQUE INDEX uk_wom_quality_quantity_event_no
    ON wom_quality_quantity_events (report_id, event_no);
