## \u672C\u914D\u7F6E\u6587\u4EF6\u96C6\u6210\u73AF\u5883\u4F7F\u7528\uFF0Cwindows\u73AF\u5883\u4F7F\u7528nacos
server.port=30020
spring.application.name=baseService
logPath=${bap.home}/baseservice/logs
spring.resources.static-locations=file:${bap.workspace}/static/
supfusion.cloud.i18n.locale-modules[0]=baseservice
supfusion.cloud.i18n.module-versions[0]=${I18N_VERSION:baseservice202012180000}
supfusion.cloud.i18n.modules[0]=baseservice
supfusion.cloud.i18n.useGetAllModule=true
supfusion.cloud.i18n.heartbeat-seconds=10
supfusion.cloud.i18n.temp=/tmp
supfusion.cloud.i18n.basename=BOOT-INF/classes/i18n/
management.metrics.tags.application=${spring.application.name}
management.metrics.export.prometheus.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.files.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.jvm.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.logback.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.processor.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.uptime.enabled=${MONITOR_ENABLED:true}
management.endpoints.web.exposure.include='*'
management.endpoint.health.show-details=ALWAYS
management.endpoint.shutdown.enabled=false
management.health.db.enabled=false