management:
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: ${MONITOR_ENABLED:true}
    binders:
      files:
        enabled: ${MONITOR_ENABLED:true}
      jvm:
        enabled: ${MONITOR_ENABLED:true}
      logback:
        enabled: ${MONITOR_ENABLED:true}
      processor:
        enabled: ${MONITOR_ENABLED:true}
      uptime:
        enabled: ${MONITOR_ENABLED:true}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: false

spring:
  profiles:
    active: prod
  redis:
    host: ${SUPOS_REDIS_HOST:redis}
    port: ${SUPOS_REDIS_PORT:6379}
  application:
    name: orgmanagement
  datasource:
    type: com.supcon.supfusion.framework.scaffold.dbp.MultiTenantDatasource
    initialization-mode: never
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${SUPOS_KAFKA_BROKERS:kafka:9092}
          auto-create-topics: true
      bindings:
        tenant-input:
          destination: supOS_tenant
          content-type: application/json
          group: ${spring.application.name}
        rbac_input_log:
          destination: topic.permission.refresh
          binder: kafka
          content-type: application/json
          group: ${spring.application.name}
  kafka:
    jaas:
      enabled: false

server:
  port: 30215
  servlet:
    context-path: /
  tomcat:
    max-threads: ${SUPOS_TOMCAT_MAX_THREAD:200}

supfusion:
  cloud:
    scan:
      enabled: false
      host: http://rbac-service:8080
    i18n:
      enabled: ${SUPOS_I18N_ENBALED:true}
      heartbeat-seconds: 30
      host: http://i18n-service:8080
      locale-modules:
        - rbac
        - userManagement
        - organization
      module-versions:
        - rbac202106011451
        - organization202106011451
        - userManagement202106011451
      basename: i18n/
      use-get-all-module: true
      modules:
        - rbac
        - userManagement
        - organization
    jwt:
      enabled: ${SUPOS_JWT_ENABLED:true}
      header: ${SUPOS_JWT_HEADER:Authorization}
      token-head: ${SUPOS_JWT_HEADER_TOKEN:Bearer}
      symmetric: false
      secret: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtkvoXs7oFBaeUS+I6Ha1SFbz4owQP4YZ0af/ujDAj0BWbHBbGQXbOwSr/Kw6eFPzxz2BfQTvrtaAtAoo5//ZS6S8wsGfXnwSkkXyMYrye+OJfsCGHv0FfSbSvfs6Agp+8E9A/ScB/fL/kMvvVxvr+1LeXr8Kc4R5woydaHto4CjD6ix7Jbfaq+UVS7RT2TE+TGBjpbcUfxceygVaX8lt7s48z0dcwg8gJEk4MwIVCC5iA44tZS3bXBLBUaZsx4VC5dK+4c5PXNDADWHXKF2w+U70MoB5vSR5RzADWO5slQf2h3Vt2Hb7cFPdhGBoWzrTfmdzRM+Kii8bfLxrYpz2WQIDAQAB
      expiration: 604800
    nacos:
      server-addr: ${SUPOS_NACOS_ADDRESS:nacos:8848}
      username: ${SUPOS_NACOS_USERNAME:nacos}
      password: ${SUPOS_NACOS_PASSWORD:nacos}
    registry:
      enabled: true
      secure: false
      weight: 1
      group: prod
    discovery:
      enabled: true
      group: ${SUPOS_NACOS_REGISTRY_GROUP:DEFAULT_GROUP}
    config-center:
      enabled: true
    datasource:
      connect:
        use-system: ${SUPOS_SYSTEM_DB_USE:false}
        system:
          db-type: ${SUPOS_SYSTEM_DB_TYPE:mariadb}
          db-name: ${SUPOS_SYSTEM_DB_NAME:fusion}
          host: ${SUPOS_SYSTEM_DB_HOST:mariadb}
          port: ${SUPOS_SYSTEM_DB_PORT:3306}
          username: ${SUPOS_SYSTEM_DB_USERNAME:root}
          password: ${SUPOS_SYSTEM_DB_PASSWORD:123456}
      druid:
        init-pool-size: ${SUPOS_DS_MIN_POOL_SIZE:1}
        min-pool-size: ${SUPOS_DS_MIN_POOL_SIZE:1}
        max-pool-size: ${SUPOS_DS_MAX_POOL_SIZE:20}
        idle-live-millis: ${SUPOS_DS_IDLE_TIME:30000}
        max-live-millis: ${SUPOS_DS_LIVE_TIME:90000}
        connection-timeout: ${SUPOS_DS_CONN_TIME:30000}
        idle-test-interval-millis: ${SUPOS_DS_IDLE_TEST_TIME:30000}
        test-while-idle: ${SUPOS_DS_IDLE_TEST_ENABLED:true}
      script:
        script-root-dirs: classpath*:META-INF/
        version-prefix: '##'
    tenant:
      sync-cache: ${SUPOS_TENANT_SYNC_CACHE:true}
      init-getter: ${SUPOS_TENANT_INIT_GETTER:true}
      register: ${SUPOS_TENANT_REGISTER:true}
  organization:
    org-type: single

mybatis-plus:
  type-aliases-package: com.supcon.supfusion.rbac.dao.po,com.supcon.supfusion.auth.dao.po,com.supcon.supfusion.organization.dao.po
  type-enums-package: com.supcon.supfusion.rbac.dao.enums
  mapper-locations:
    - classpath:mappers/*.xml
    - classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
  global-config:
    banner: false
    db-config:
      logic-delete-enabled: false
      optimistic-lock-enabled: false
#      pagination-enabled: true
rbac:
  default-systemRole-name: 管理员角色

feign:
  client:
    default-config: default
    default-to-properties: true
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000
  httpclient:
    enabled: true

kaptcha:
  border: "yes"         #  是否有边框，默认为 yes，可选 yes、no
  border.color: 105,179,90    # 边框颜色
  textproducer:
    font:
      color: blue     # 验证码字体颜色
      size: 30        # 文本字符大小
      names: 宋体,楷体     # 文本字体样式
    char:
      length: 4     # 验证码文本字符长度
  image:
    width: 120      # 图片宽度
    height: 40      # 图片高度
  session:
    key: code     # 存储 session key
# 人员签名、头像配置地址
file:
  path: ${IMAGE_PATH:default/img}