package com.supcon.supfusion.signature.dao.enums;

public enum FieldType {
	TEXTFIELD, PASSWORDFIELD, TEXTAREA, SELECT, DATE, DATETIME, OUTERSELECT, AUTOCOMPLETE, MULTSELECT, RICHTEXT, RADIO, CHECKBOX, LABEL, SELECTCOMP, DATAGRID, MULTFILES, ATTACHMENT, PROPERTYATTACHMENT, PICTURE, OFFICE, OUTDATA,MULTIDATAGRID,SELECTTAGNUMBER,SUPERVISION,EASYTABLE,LAYER,TIME,COLOR
}
