ALTER TABLE wms_stock_documents
    ADD COLUMN IF NOT EXISTS quantity_allocation_state VARCHAR(32) DEFAULT 'NONE' NOT NULL;

ALTER TABLE wms_stock_document_lines
    ADD COLUMN IF NOT EXISTS reported_quantity NUMERIC(20, 6);
ALTER TABLE wms_stock_document_lines
    ADD COLUMN IF NOT EXISTS good_quantity NUMERIC(20, 6);
ALTER TABLE wms_stock_document_lines
    ADD COLUMN IF NOT EXISTS bad_quantity NUMERIC(20, 6);

UPDATE wms_stock_document_lines
SET reported_quantity = quantity, good_quantity = quantity, bad_quantity = 0;

ALTER TABLE wms_stock_document_lines ALTER COLUMN reported_quantity SET NOT NULL;
ALTER TABLE wms_stock_document_lines ALTER COLUMN good_quantity SET NOT NULL;
ALTER TABLE wms_stock_document_lines ALTER COLUMN bad_quantity SET NOT NULL;
ALTER TABLE wms_stock_document_lines ALTER COLUMN reported_quantity SET DEFAULT 0;
ALTER TABLE wms_stock_document_lines ALTER COLUMN good_quantity SET DEFAULT 0;
ALTER TABLE wms_stock_document_lines ALTER COLUMN bad_quantity SET DEFAULT 0;

ALTER TABLE wms_stock_document_lines DROP CONSTRAINT ck_wms_stock_document_lines_quality;
ALTER TABLE wms_stock_document_lines ADD CONSTRAINT ck_wms_stock_document_lines_quality
    CHECK (quality_status IN ('PENDING', 'QUALIFIED', 'PARTIAL', 'UNQUALIFIED'));
ALTER TABLE wms_stock_documents DROP CONSTRAINT ck_wms_stock_documents_quality;
ALTER TABLE wms_stock_documents ADD CONSTRAINT ck_wms_stock_documents_quality
    CHECK (quality_status IN ('PENDING', 'QUALIFIED', 'PARTIAL', 'UNQUALIFIED'));
ALTER TABLE wms_inventory_transactions DROP CONSTRAINT ck_wms_inventory_transactions_type;
ALTER TABLE wms_inventory_transactions ADD CONSTRAINT ck_wms_inventory_transactions_type
    CHECK (transaction_type IN (
        'COMPLETION_INBOUND', 'PRODUCTION_ISSUE', 'QUALITY_RELEASE', 'QUALITY_HOLD',
        'QUALITY_ALLOCATION_HOLD', 'QUALITY_ALLOCATION_RELEASE'
    ));

CREATE TABLE IF NOT EXISTS wms_quality_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    source_system VARCHAR(32) NOT NULL DEFAULT 'WOM',
    source_line_id VARCHAR(128) NOT NULL,
    task_id VARCHAR(128) NOT NULL,
    quality_report_id VARCHAR(128) NOT NULL,
    total_quantity NUMERIC(20, 6) NOT NULL,
    good_quantity NUMERIC(20, 6) NOT NULL,
    bad_quantity NUMERIC(20, 6) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_wms_quality_allocations_quantity CHECK (
        total_quantity > 0 AND good_quantity >= 0 AND bad_quantity > 0
        AND total_quantity = good_quantity + bad_quantity
    ),
    CONSTRAINT ck_wms_quality_allocations_status CHECK (status IN ('ACTIVE', 'REVERSED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_wms_quality_allocations_source
    ON wms_quality_allocations (tenant_id, source_system, source_line_id);

CREATE TABLE IF NOT EXISTS wms_quality_allocation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    event_key VARCHAR(256) NOT NULL,
    allocation_id BIGINT NOT NULL REFERENCES wms_quality_allocations(id) ON DELETE CASCADE,
    event_type VARCHAR(32) NOT NULL,
    quality_report_id VARCHAR(128) NOT NULL,
    payload CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_wms_quality_allocation_event_type CHECK (event_type IN ('APPLY', 'REVERSE'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_wms_quality_allocation_events_key
    ON wms_quality_allocation_events (tenant_id, event_key);
