spring.application.name=servicemanager
version=6.1.1.00
spring.datasource.druid.filter.slf4j.enabled=true
spring.datasource.druid.filter.slf4j.statement-create-after-log-enabled=false
spring.datasource.druid.filter.slf4j.statement-close-after-log-enabled=false
spring.datasource.druid.filter.slf4j.result-set-open-after-log-enabled=false
spring.datasource.druid.filter.slf4j.result-set-close-after-log-enabled=false
server.port=30010
spring.kafka.consumer.auto-offset-reset=latest
supfusion.cloud.i18n.locale-modules[0]=appConfig
supfusion.cloud.i18n.module-versions[0]=${I18N_VERSION:appConfig202101071358}
supfusion.cloud.i18n.modules[0]=appConfig
supfusion.cloud.i18n.useGetAllModule=true
supfusion.cloud.i18n.heartbeat-seconds=10
supfusion.cloud.i18n.temp=/tmp
## \u4E0D\u786E\u5B9A\u7528\u4E0D\u7528
entityPath=${bap.home}/workspace
logPath=${bap.home}/operatetools/logs
# entityconf.jdk=${bap.home}/assembly/jdk1.8/bin
# entityconf.logDirectoryPath=${bap.workspace}/bap-workspace/baplogs
# entityconf.moduleServerPath=${bap.home}/module-Server
entityconf.mvn=${bap.home}/assembly/maven/bin/mvn
# =${bap.workspace}/baplogs/uploadLog
spring.cloud.util.enabled=true
dynamicode.server.enable=false
endpoints.shutdown.sensitive=false
# masterSlave.enabled=false
misServer.workspace=${bap.home}/bap-static/
maven.repository.path=${bap.home}/assembly/repository/maven
supos.app.path=${bap.home}/apps
management.metrics.tags.application=${spring.application.name}
management.metrics.export.prometheus.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.files.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.jvm.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.logback.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.processor.enabled=${MONITOR_ENABLED:true}
management.metrics.binders.uptime.enabled=${MONITOR_ENABLED:true}
management.endpoints.web.exposure.include='*'
management.endpoint.health.show-details=ALWAYS
management.endpoint.shutdown.enabled=false
management.health.db.enabled=false
supos.app.init.version=${SUPOS_APP_INIT_VERSION:1.2.19}
cloud.discovery.group=${CLOUD_DISCOVERY_GROUP:DEFAULT_GROUP}
supos.nacos.registry.group=${SUPOS_NACOS_REGISTRY_GROUP:DEFAULT_GROUP}
i18n.host=${I18N_HOST:i18n-service.default}
i18n.port=${I18N_PORT:8080}
nacos.host=${NACOS_HOST:nacos.default}
nacos.port=${NACOS_PORT:8848}
supos.nacos.username=${SUPOS_NACOS_USERNAME:nacos}
supos.nacos.password=${SUPOS_NACOS_PASSWORD:nacos}
supos.redis.host=${SUPOS_REDIS_HOST:redis.default}
supos.redis.port=${SUPOS_REDIS_PORT:6379}
supos.kafka.brokers=${SUPOS_KAFKA_BROKERS:127.0.0.1:9092}
supos.zookeeper.nodes=${SUPOS_ZOOKEEPER_NODES:127.0.0.1:2181}
