CREATE TABLE IF NOT EXISTS wfm_task_pending (
  id BIGINT(20) NOT NULL,
  user_id BIGINT(20) NOT NULL COMMENT '用户ID',
  person_name VARCHAR(128) DEFAULT NULL COMMENT '人员名',
  app_id VARCHAR(64) DEFAULT NULL COMMENT 'app id',
  task_description VARCHAR(512) DEFAULT NULL COMMENT '活动名称-国际化编号',
  activity_type VARCHAR(32) DEFAULT NULL COMMENT '活动类型',
  activity_name VARCHAR(64) DEFAULT NULL COMMENT '活动ID',
  execution_id VARCHAR(128) DEFAULT NULL COMMENT '活动实例ID',
  task_status TINYINT(4) NOT NULL DEFAULT 88 COMMENT '88-进行中 77-暂停',
  open_url VARCHAR(1024) DEFAULT NULL COMMENT '待办关联url',
  instance_id VARCHAR(64) DEFAULT NULL COMMENT 'bap业务ID',
  process_key VARCHAR(64) DEFAULT NULL COMMENT '流程编号',
  process_version INT(4) DEFAULT 0 COMMENT '流程版本',
  process_name VARCHAR(200) DEFAULT NULL COMMENT '流程名称',
  process_description VARCHAR(512) DEFAULT NULL COMMENT '流程定义描述',
  initiator_id VARCHAR(64) DEFAULT NULL COMMENT '流程发起者',
  staff_name VARCHAR(128) DEFAULT NULL COMMENT '流程发起者人员名称',
  process_id VARCHAR(64) DEFAULT NULL COMMENT '流程实例ID',
  table_info_id BIGINT(20) DEFAULT NULL COMMENT 'bap字段',
  entity_code VARCHAR(64) DEFAULT NULL COMMENT 'bap字段',
  table_no VARCHAR(64) DEFAULT NULL COMMENT '单据编号',
  deployment_id BIGINT(20) DEFAULT 0 COMMENT '流程部署ID',
  task_type TINYINT(2) DEFAULT 0 COMMENT '待办类型 0-普通待办 2-委托待办 4-编辑待发',
  proxy_source BIGINT(20) DEFAULT NULL COMMENT '最近一次委托者',
  description VARCHAR(512) DEFAULT NULL COMMENT '委托原因',
  loops TINYINT(2) DEFAULT NULL COMMENT '循环会签 0不是循环会签,1表示本公司，2表示夸公司，3表示本部门,4表示本部门及下级，5自定义',
  task_source VARCHAR(32) DEFAULT NULL COMMENT '数据来源 bap, supOS',
  cid BIGINT(20) DEFAULT NULL COMMENT '公司ID',
  model_id BIGINT(20) DEFAULT NULL COMMENT 'bap字段',
  main_loop SMALLINT(1) DEFAULT 0 COMMENT '是否是主办人',
  attention SMALLINT(1) DEFAULT 0 COMMENT '是否关注',
  has_read SMALLINT(1) DEFAULT 0 COMMENT '是否已读 0-未读, 1-已读',
  multi_company SMALLINT(1) DEFAULT 0 COMMENT '是否跨公司',
  source_staff BIGINT(20) DEFAULT 0 COMMENT '委托的原始用户',
  latest_user VARCHAR(64) DEFAULT NULL COMMENT '上个环节提交者人员名称',
  mobile_approve SMALLINT(1) DEFAULT 1 COMMENT '启动移动客户端审批',
  description_zh_cn VARCHAR(512) DEFAULT NULL,
  task_description_zh_cn VARCHAR(512) DEFAULT NULL,
  process_description_zh_cn VARCHAR(512) DEFAULT NULL,
  integration_id VARCHAR(64) DEFAULT NULL,
  row_version INT(11) DEFAULT NULL COMMENT '乐观锁',
  version INT(11) DEFAULT NULL COMMENT 'bap专用乐观锁',
  due_time TIMESTAMP NULL,
  tenant_id VARCHAR(64) DEFAULT '',
  start_time TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  creator VARCHAR(32) DEFAULT NULL,
  create_staff_id BIGINT(20) DEFAULT NULL,
  create_time TIMESTAMP DEFAULT current_timestamp(),
  modifier VARCHAR(32) DEFAULT NULL,
  modify_staff_id BIGINT(20) DEFAULT NULL,
  modify_time TIMESTAMP DEFAULT current_timestamp(),
  PRIMARY KEY (id),
  KEY idx_wfm_task_pending_user_id (user_id),
  KEY idx_wfm_task_pending_process_id (process_id)
) DEFAULT CHARSET=utf8;
create trigger trg_pending_task_insert
after insert on wfm_task_pending
FOR EACH ROW
insert into supos_system001.wfm_task_pending (id,user_id,person_name,app_id,task_description,activity_type,activity_name,
execution_id,task_status,open_url,instance_id,process_key,process_version,process_name,process_description,initiator_id,
staff_name,process_id,table_info_id,entity_code,table_no,deployment_id,task_type,proxy_source,description,loops,
task_source,cid,model_id,main_loop,attention,has_read,multi_company,source_staff,latest_user,mobile_approve,
description_zh_cn,task_description_zh_cn,process_description_zh_cn,integration_id,row_version,version,tenant_id,
creator,create_staff_id,create_time,modifier,modify_staff_id,modify_time,start_time,due_time)
values
(new.id,new.user_id,new.person_name,new.app_id,new.task_description,new.activity_type,new.activity_name,new.execution_id,
new.task_status,new.open_url,new.instance_id,new.process_key,new.process_version,new.process_name,new.process_description,
new.initiator_id,new.staff_name,new.process_id,new.table_info_id,new.entity_code,new.table_no,new.deployment_id,new.task_type,
new.proxy_source,new.description,new.loops,new.task_source,new.cid,new.model_id,new.main_loop,new.attention,new.has_read,
new.multi_company,new.source_staff,new.latest_user,new.mobile_approve,new.description_zh_cn,new.task_description_zh_cn,
new.process_description_zh_cn,new.integration_id,new.row_version,new.version,new.tenant_id,new.creator,new.create_staff_id,new.create_time,
new.modifier,new.modify_staff_id,new.modify_time,new.start_time,new.due_time);
create trigger trg_pending_task_delete
after delete on wfm_task_pending
FOR EACH ROW
delete from supos_system001.wfm_task_pending where id=old.id;