package com.supcon.supfusion.configuration.services.utils;

import java.util.HashMap;
import java.util.Map;

public class DBColumnNames {
	
	public static final Map<String, String> COLUMN_NAMES = new HashMap<>();
	
	static {
		COLUMN_NAMES.put("ADV_QUERY_JSON", "CODE,EC_ENV,VERSION,PROJ_FLAG,NAME,LAYOUT_NAME,QUERY_CONFIG,VIEW_CODE,TARGETMODEL_CODE");
		COLUMN_NAMES.put("ADV_QUERY_CONDITION", "ID,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,LAYOUT_NAME,ADMIN_FLAG,VIEW_CODE,REMARK,COND_NAME,MODEL_ALIAS,OWNER_ID");
		COLUMN_NAMES.put("ADV_QUERY_CONDITION_ITEM", "ID,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,NAME,VALUEBAK,ADV_TYPE,MODEL_ALIAS,CONDITION_ID,PARENT_ID,MODEL_CODE,JOIN_INFO,LOGIC,VALUE,OPERATOR,PARAM_STR,DB_COLUMN_TYPE,COLUMN_NAME,TYPE");
		
		COLUMN_NAMES.put("BACKUP_DATA_GRID", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,EX,ORGPROPERTY_CODE,TARGETMODEL_CODE,VIEW_CODE,NAME,DG_FIELD_CONFIG,CONFIG,BACKUPVIEW_CODE");
		COLUMN_NAMES.put("BACKUP_VIEW", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,FIELD_CONFIG,CONFIG,VIEW_CODE");
		COLUMN_NAMES.put("BUSINESS_CENTER", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,PROJ_FLAG,IS_NEW_FIRST,RELATE_BUSINESS_CODE,SHOW_NAME,ASS_VIEW_CODE,SORT,ENABLED,RELATING_FIELD_CODE,MAIN_FIELD_CODE,RELATING_MODEL_CODE,MAIN_MODEL_CODE,MODEL_CODE");
		COLUMN_NAMES.put("BUTTON", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,IS_SIGNATURE_CONFIG,PROJ_FLAG,IS_PUBLISHED,BUTTON_ALIGN,PERMISSION_CODE,CONFIG,SCRIPT_CODE,REGION_TYPE,DATAGRID_CODE,VIEW_CODE,CELL_CODE,DISPLAY_NAME,OPERATE_URL,IS_HIDE,IS_CUSTOM_FUNC,IS_CALLBACK,IS_PERMISSION,IS_USE_MORE,BUTTON_STYLE,CONFIRM_CONTENT,IS_CONFIRM,VIEWSELECT_CODE,OPERATE_TYPE,NAME,POWER_TYPE,ROLE_ID,POSITION_ID,SIGNER_ID,SIGNATURE_TYPE,SIGNATURE_ENABLED,BUTTON_OPERATION_CODE");
		COLUMN_NAMES.put("BUTTONINFO", "CODE,EC_ENV,VERSION,VIEW_CODE,ENTITY_CODE,ACTION,NAME_SPACE,ICON_CLS,URL,NAME");
		
		COLUMN_NAMES.put("CUSTOMER_CONDITION", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,PROJ_FLAG,CONDITION_SQL,JSON_CONDITION,DATACLASSIFIC_CODE,DATAGRID_CODE,VIEW_CODE");
		COLUMN_NAMES.put("CUSTOM_CODE", "CODE,EC_ENV,VERSION,CUSTOM_CODE,SUB_TYPE,TYPE,MODEL_CODE,ENTITY_CODE,MODULE_CODE");
		
		COLUMN_NAMES.put("DATA_CLASSIFIC", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,PROJ_FLAG,IS_DEFAULT,SORT,DATA_GROUP_CODE,DC_CONDITION,DISPLAY_NAME,NAME");
		COLUMN_NAMES.put("DATA_GRID", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,PROJ_FLAG,OPERATE_NAME,PERMISSION_CODE,IS_PERMISSION,DATA_GRID_TYPE,FULL_CONFIG,DATA_GRID_NAME,EX,ORGPROPERTY_CODE,TARGETMODEL_CODE,CONFIG,VIEW_CODE,NAME,DATA_GRID_JSON");
		COLUMN_NAMES.put("DATA_GROUP", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,PROJ_FLAG,SORT,LAYOUT_NAME,IS_MULTIPLE,DISPLAY_NAME,NAME,VIEW_CODE,TARGETMODEL_CODE");
		COLUMN_NAMES.put("DEFAULT_ADV_COND", "CODE,EC_ENV,VERSION,VIEW_CODE,CONTENT");
		COLUMN_NAMES.put("DEPLOY_INFO", "ID,VALID,VERSION,LOGFILE_PREFIX,STATUS,TASKS,MODULE_CODE,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,DELETE_TIME,MODIFY_TIME,CREATE_TIME");
		
		COLUMN_NAMES.put("ENTITY", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENABLE_WS,ENABLE_REST,PROJ_FLAG,TYPE,ENABLE_AUDIT,ENABLE_ACL_RESTRICT,MOBILE,CROSS_COMPANY_FLAG,IS_CONTROL,IS_INHERENTED_BASE,INHERENT_COMMON_FLAG,IS_BASE,MODULE_CODE,PAY_CLOSE_ATTENTION,GROUP_ENABLED,PREFIX,DESCRIPTION,WORKFLOW_ENABLED,ENTITY_NAME,NAME,ENABLE_FIELDS_PERMISSION_CONF,VALUE_ZH_CN");
		COLUMN_NAMES.put("ENTITY_MODIFY_INFO", "ID,VERSION,LAST_MODIFY_TIME,MODULE_CODE,ENTITY_CODE");
		COLUMN_NAMES.put("EVENT", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,PROJ_FLAG,SECTION_CODE,TAB_CODE,LAYOUT_CODE,BUTTON_CODE,FIELD_CODE,EVENT_FUNCTION,EVENT_FUNCTION_ES5,NAME");
		COLUMN_NAMES.put("EXTRA_QUERY_JSON", "CODE,EC_ENV,VERSION,PROJ_FLAG,QUERY_CONFIG,VIEW_CODE");
		COLUMN_NAMES.put("EXTRA_VIEW", "CODE,EC_ENV,VERSION,PROJ_FLAG,FULL_CONFIG,CONFIG,VIEW_CODE,VIEW_JSON");
		
		COLUMN_NAMES.put("FAST_QUERY_JSON", "CODE,EC_ENV,VERSION,PROJ_FLAG,LAYOUT_NAME,QUERY_CONFIG,VIEW_CODE,TARGETMODEL_CODE");
		COLUMN_NAMES.put("FIELD", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,PROJ_FLAG,COLUMN_TYPE,FULL_PROPERTY_CODE,REGION_TYPE,ADVQUERYJSON_CODE,FASTQUERYJSON_CODE,DATAGRID_CODE,CONFIG,CELL_CODE,NONE,IS_HIDDEN,LAY_REC,SHOW_FORMAT,SHOW_TYPE,VIEW_CODE,PROPERTY_CODE,DISPLAY_NAME,NAME,FIELD_KEY,LAYER_TYPE");
		
		COLUMN_NAMES.put("LAYOUT", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,CONTENT,DESCRIPTION,IMAGE,NAME");
		
		COLUMN_NAMES.put("MODEL", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,PROJ_FLAG,SPECIALPER_TEMPLATE_SQL,IS_CONFIG_SPECIAL,SPECIAL_AUTH_ISANDREL,IS_MNE_CODE,IS_CONTROL,IS_CACHE,ENTITY_CLASS,IS_EXTRA_COL,ENABLE_DATA_AUDIT,ENABLE_OPERATION_AUDIT,ENABLE_SYNC,TABLE_NAME,INHERENT_COMMON_FLAG,EC_VERSION,JPA_NAME,MODULE_CODE,EXTENDS_MODEL_CODE,IS_EXTENDS,TYPE,DATA_TYPE,IS_MAIN,ENTITY_CODE,DESCRIPTION,MODEL_NAME,NAME,MODEL_SQL,VALUE_ZH_CN");
		COLUMN_NAMES.put("MODULE", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,IS_HIDE,IS_READ_ONLY,PROJ_FLAG,IS_NEW_GENERATE,IS_INHERENTED_BASE,DEPLOY_ORDER,DESCRIPTION,INITIAL_VERSION,PROJECT_VERSION,ARTIFACT,NAME,CATEGORY,VALUE_ZH_CN,COPY_MODULE_CODE,ACRONYM,TYPE");
		COLUMN_NAMES.put("MODULE_GENERATE_INFO", "ID,VERSION,LAST_MODIFY_TIME,MODULE_CODE");
		COLUMN_NAMES.put("MODULE_RELATION", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,PROJ_FLAG,MODULE_CODE,TARGET_MODULE_CODE");
		COLUMN_NAMES.put("MODULE_REFERENCE", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,PROJ_FLAG,MODULE_CODE,TARGET_MODULE_CODE");
		COLUMN_NAMES.put("MY_PORTLET", "ID,VERSION,CONFIG,USER_ID");
		
		COLUMN_NAMES.put("OTHER_RESTRICT", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,MEMO,HAND_WRITING_FLAG,TITLE,CONDITION_SQL,JSON_CONDITION,VIEW_CODE");
		
		COLUMN_NAMES.put("PORTLET", "ID,VERSION,IS_DEFAULT,TITLE_COLOR,TITLE_KEY,TITLE,SIZE_NUM,MORE_TARGET,MORE_URL,URL,CODE");
		COLUMN_NAMES.put("PRINT_TEMPLATE", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,TEMPLATE_ENABLED,VALID,PROJ_FLAG,IS_PUBLISH,PROCESS_KEY,PROCESS_VERSION,DESCRIPTION,TEMPLATE,TEMPLATE_REMARK,TEMPLATE_SCRIPT,VIEW_CODE,MODEL_CODE,TEMPLATE_NAME,TEMPLATE_CODE,ENTITY_CODE,EXTRA_PARAM_SCRIPT,EXTRA_PARAM_COUNT,EXTRA_PARAM,EXTRA_PIC_PARAM_COUNT,TEMPLATE_BUSINESSCODE");
		COLUMN_NAMES.put("PROPERTY", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,PROJ_CUSTOM_IN_USE,PROJ_FLAG,SORT,IS_HIDDEN,IS_ENGINE,FETCH_MODE,ASSOCIATED_PROPERTY_CODE,ASSOCIATED_TYPE,IS_CUSTOM,IS_MNE_WHOLE_LIKE_QUERY,COLUMN_NAME,SENIOR_SYSTEM_CODE,NO_ANALYZER,IS_MAIN_ASSOCIATED,IS_USED_FOR_SEARCH,STRETCH,PIC_HEIGHT,PIC_WIDTH,IS_BUSSINESS_KEY,IS_CONTROL,IS_USED_MNE_CODE,DEFAULT_VALUE,IS_SENSITIVE,IS_MAIN_DISPLAY,IS_USED_FOR_LIST,MODEL_CODE,DESCRIPTION,ATTRIBUTES,FILLCONTENT,IS_PK,IS_INHERENT,IS_IGNORE_AUDIT,IS_UNIQUE,MULTABLE,DECIMAL_NUM,MAX_LENGTH,NULLABLE,IS_INDEX,FIELD_TYPE,FORMAT,TYPE,DISPLAY_NAME,NAME,IS_GROUP_OBJECT,ONLY_LEAF");
		
		COLUMN_NAMES.put("REMIND_RECORD", "ID,VERSION,REMIND_CONTENT,PROCESS_VERSION,PROCESS_KEY,TASK_DESCRIPTION,ACTIVITY_NAME,REMIND_TIME,TABLE_INFO_ID,ENTITY_CODE,SEND_USER_ID,REMIND_STAFF_NAME,TABLE_NO");
		
		COLUMN_NAMES.put("SPECIAL_PERMISSION", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,ORDER_NO,PROPERTY_CODE,REF_VIEW_CODE,IS_TREE,TARGET_MODEL_CODE,TYPE,RELATION,RANK,MODEL_CODE");
		COLUMN_NAMES.put("SPECIAL_PERMISSION_RSHOW", "ID,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,IS_ASSIGNED,LAY_REC,IS_INCLUDE_SUB,OPERATE_ID,VALUE_CODE,VALUE_TITLE,VALUE_ID,SPECIAL_PERMISSION_CODE,ROLE_ID");
		COLUMN_NAMES.put("SPECIAL_PERMISSION_USHOW", "ID,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,IS_ASSIGNED,LAY_REC,IS_INCLUDE_SUB,OPERATE_ID,VALUE_CODE,VALUE_TITLE,VALUE_ID,SPECIAL_PERMISSION_CODE,USER_ID");
		COLUMN_NAMES.put("SQL", "CODE,EC_ENV,VERSION,PROJ_FLAG,DATA_GRID_CODE,VIEW_CODE,TYPE,QUERY_SQL");
		
		COLUMN_NAMES.put("TABLE_INFO", "ID,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,EFFECTIVE_STATE,PROCESS_VERSION,PROCESS_KEY,DEPLOYMENT_ID,SUMMARY,TARGET_TABLE_NAME,STATUS,OWNER_DEPAETMENT_ID,OWNER_DEPARTMENT_ID,OWNER_POSITION_ID,OWNER_STAFF_ID,TARGET_ENTITY_CODE,CREATE_POSITION_ID,POSITION_LAY_REC,EFFECT_TIME,EFFECT_STAFF_ID,CREATE_DEPARTMENT_ID,TABLE_NO");
		
		COLUMN_NAMES.put("VALIDATE", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ENTITY_CODE,MODULE_CODE,PROJ_FLAG,FIELD_CODE,PARAMS,TYPE");
		COLUMN_NAMES.put("VIEW", "CODE,EC_ENV,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,PROJ_ENABLED,MENU_NAME,PARENT_MENU_ID,PUBLISH_TIME,INHERIT_TYPE,PROJ_FLAG,EDIT_VIEW_TYPE,HAS_CUSTOM_SECTION,IMPORT_FLAG,ENABLE_SIMPLE_DEAL_INFO,BATCH_CONTROL_PRINT_VIEW_CODE,IS_BATCH_CONTROL_PRINT,MOBILE_ENABLE_FLAG,MOBILE,ONLY_FOR_QUERY,REF_OPERATE_NAME,OPERATE_URL,PERMISSION_CODE,MODULE_CODE,CONTROL_SETING_NAME,CONTROL_CODE,CONTROL_NAME,CONTROL_PRINT,IS_PERMISSION,IS_AUDIT,IS_PRINT,IS_HAND_SIGN,IS_SIGN,IS_SHADOW,SHADOW_VIEW_CODE,EXTRA_QUERY_JSON,DATA_GRID_TYPE,ASS_TREE_PATH,ASS_TREE_LAY_REC,ASS_TREE_MODEL_CODE,REFERENCE_VIEW_CODE,IS_REFERENCE,INCLUDE_CHILDREN,USED_FOR_TREE,DEAL_INFO_GROUP,DEAL_INFO_SHOW,HAS_ATTACHMENT,IS_CONTROL,CLOSE_PAGE_AFTER_SAVE,LAYOUT_CODE,SHOW_TYPE,WIDTH,HEIGHT,DIALOG_TYPE,CUSTOM_FLAG,URL,SCRIPT_CODE,RETRIAL_FLAG,ADV_QUERY_JSON,FAST_QUERY_JSON,EXTRA_VIEW,ASS_VIEW_CODE,ASS_MODEL_CODE,ENTITY_CODE,DESCRIPTION,MAIN_REF,MAIN_VIEW,USED_FOR_WORK_FLOW,OPEN_TYPE,TYPE,TITLE,DISPLAY_NAME,NAME,ATTACHMENT_FLAG");
	
		COLUMN_NAMES.put("IMPORT_TEMPLATE", "CODE,EC_ENV,VERSION,VALUE,PROJ_FLAG");
		
		COLUMN_NAMES.put("ECHARTS", "CODE,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,IS_SHOW_MAGIC_TYPE,LEGEND_POSITION,IS_SHOW_LEGEND,IS_FIRST_LOAD,TITLE,PROJ_FLAG");
		COLUMN_NAMES.put("ECHARTS_MODEL", "CODE,VERSION,DELETE_TIME,MODIFY_TIME,CREATE_TIME,DELETE_STAFF_ID,MODIFY_STAFF_ID,CREATE_STAFF_ID,VALID,ECHARTS_CODE,MODEL_CODE,TYPE,CLASSIFICATION_COLUMN,SERIES_COLUMN,VALUE_COLUMN,YAXIS_STR,XAXIS_STR,IS_CUSTOM_CONDITIONS,CUSTOM_CONDITIONS,CUSTOM_CONDITIONS_CONFJSON,MODEL_SQL,PROJ_FLAG");
		
	}
	
}
