integration.enable=true
integration.authentication=supfusion
integration.clientUrl=${actual-ip-port}
integration.userInfo=/inter-api/auth/v1/getCurrentLoginInfo
logPath=${bap.home}/workspace/bap-ms-log/authService-logs
server.port=30030
server.servlet.context-path=/auth
server.servlet.session.cookie.name=bapSessionId
server.servlet.session.cookie.path=/
server.servlet.session.timeout=24h
spring.messages.basename=META-INF/i18n/messages
spring.messages.useCodeAsDefaultMessage=true
spring.messages.encoding=UTF-8
spring.freemarker.template-loader-path=file:./custom_template,classpath:/templates/
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true