management.health.db.enabled=false
server.port=30160
server.servlet.context-path=/
spring.application.name=supos-iam
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
mybatis-plus.type-aliases-package=com.supcon.supfusion.iam.dao.entity
mybatis-plus.global-config.db-config.max-file-size=200MB
mybatis-plus.global-config.db-config.max-request-size=215MB
supfusion.cloud.i18n.locale-modules[0]=iam
supfusion.cloud.i18n.module-versions[0]=iam202101081639
supfusion.cloud.i18n.basename=i18n/
supfusion.cloud.i18n.use-get-all-module=true