spring.kafka.bootstrap-servers=${SUPOS_KAFKA_BROKERS:127.0.0.1:9092}
supfusion.kafka.bootstrap.server=${spring.kafka.bootstrap-servers}
spring.cloud.stream.kafka.binder.zk-nodes=${SUPOS_ZOOKEEPER_NODES:127.0.0.1:2181}
spring.cloud.stream.kafka.binder.auto-create-topics=true
spring.cloud.stream.kafka.binder.brokers=${spring.kafka.bootstrap-servers}