management.health.db.enabled=false
server.port=forceChange:30205
server.servlet.context-path=/
spring.application.name=portal
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
mybatis-plus.type-aliases-package=com.supcon.supfusion.portal.dao.entity
mybatis-plus.global-config.db-config.max-file-size=200MB
mybatis-plus.global-config.db-config.max-request-size=215MB
supfusion.cloud.i18n.locale-modules[0]=portal
supfusion.cloud.i18n.module-versions[0]=forceChange:portal202101081639
supfusion.cloud.i18n.basename=i18n/
supfusion.cloud.i18n.use-get-all-module=true
#supfusion.cloud.datasource.connect.use-system=true
#supfusion.cloud.datasource.connect.system.db-type=sqlserver
#supfusion.cloud.datasource.connect.system.db-name=bap72test3
#supfusion.cloud.datasource.connect.system.host=10.10.40.111
#supfusion.cloud.datasource.connect.system.port=1433
#supfusion.cloud.datasource.connect.system.username=sa
#supfusion.cloud.datasource.connect.system.password=${REPLACE_ME}
#supfusion.cloud.datasource.druid.init-pool-size=1
#supfusion.cloud.datasource.druid.min-pool-size=1
#supfusion.cloud.datasource.druid.max-pool-size=100
#supfusion.cloud.datasource.druid.validationQuerySql=${VALIDATIONQUERYSQL:SELECT 1}
#supfusion.cloud.datasource.script.script-root-dirs=classpath*:META-INF/
#spring.datasource.type=com.supcon.supfusion.framework.scaffold.dbp.MultiTenantDatasource
#spring.datasource.initialization-mode=never
