management.health.db.enabled=false
server.port=30233
server.servlet.context-path=/
spring.application.name=notification-sms-jincang
mybatis-plus.type-aliases-package=com.supcon.supfusion.notification.sms.dao.entities
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
mybatis-plus.global-config.db-config.max-file-size=200MB
mybatis-plus.global-config.db-config.max-request-size=215MB