mybatis-plus.configuration.log-impl=
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.banner=false
mybatis-plus.global-config.db-config.logic-delete-enabled=false
mybatis-plus.global-config.db-config.optimistic-lock-enabled=false
