server.port=30010
spring.application.name=servicemanager
spring.kafka.consumer.auto-offset-reset=latest
supfusion.cloud.i18n.basename=forceChange:i18n/
supfusion.cloud.i18n.locale-modules[0]=appConfig
supfusion.cloud.i18n.module-versions[0]=forceChange:appConfig202103161540
supfusion.cloud.i18n.modules[0]=appConfig
supfusion.cloud.i18n.useGetAllModule=true
supfusion.cloud.i18n.heartbeat-seconds=10
entityPath=${bap.home}/workspace
logPath=${bap.home}/../logs/entityconf-logs
entityconf.jdk=${bap.home}/assembly/jdk1.8/bin
entityconf.logDirectoryPath=${bap.home}/bap-workspace/baplogs
entityconf.moduleServerPath=${bap.home}/module-Server
entityconf.mvn=${bap.home}/assembly/maven/bin/mvn
entityconf.uploadLogDirectoryPath=${bap.home}/bap-workspace/baplogs/uploadLog
supos.app.path=/apps
supos.task.api=${REPLACE_ME}
supos.task.log.api=${REPLACE_ME}
supos.apps.api=/openapi/installer/v1/apps
spring.cloud.util.enabled=true
dynamicode.server.enable=false
endpoints.shutdown.sensitive=false
management.endpoints.web.exposure.include=*
masterSlave.enabled=false	
misServer.workspace=${bap.home}/bap-workspace/bap-static/
