server.port=8008
spring.output.ansi.enabled=ALWAYS
spring.application.name=supos-gateway
spring.jmx.enabled=false
spring.cloud.gateway.httpclient.websocket.max-frame-payload-length=4194304
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=false
spring.cloud.gateway.discovery.locator.predicates[0]=Path='/api/' + serviceId + '/**', '/inter-api/' + serviceId + '/**', '/open-api/' + serviceId + '/**', '/open-api/supos/' + serviceId + '/**', '/openapi/' + serviceId + '/**','/msService/' + serviceId + '/**','/msService/public/' + serviceId + '/**'
spring.cloud.gateway.discovery.locator.filters[0]=RewritePath='/' + serviceId + '/(?<remaining>.*)', '/' + serviceId + '/${remaining}'
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].maxAge=1800
spring.cloud.gateway.routes[0].id=keycloak
spring.cloud.gateway.routes[0].uri=lb://keycloak
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/realms/supos/auth/login
spring.cloud.gateway.routes[1].id=logout
spring.cloud.gateway.routes[1].uri=lb://keycloak
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/users/logout
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/auth/users/logout, /auth/realms/supos/protocol/openid-connect/logout
spring.cloud.gateway.routes[2].id=company
spring.cloud.gateway.routes[2].uri=lb://keycloak
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/realms/supos/auth/company
spring.cloud.gateway.routes[3].id=websocket-server
spring.cloud.gateway.routes[3].uri=ws://websocket-server:8080/inter-api/notification/ws/notice/**
spring.cloud.gateway.routes[3].predicates[0]=Path=/inter-api/notification/ws/notice/**
spring.cloud.gateway.routes[4].id=old-notification
spring.cloud.gateway.routes[4].uri=lb://notification-apiserver
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/notification/sendNotice
spring.cloud.gateway.routes[5].id=image
spring.cloud.gateway.routes[5].uri=lb://config
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/image/**, /project/dam/supngin/api/image/**, /project/dam/supngin/api/config/**, /inter-api/image/**, /open-api/image/**, /project/dam/supngin/inter-api/image/**, /project/dam/supngin/open-api/image/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/project/dam/supngin/(?<remaining>.*), /${remaining}
spring.cloud.gateway.routes[5].filters[1]=RewritePath=/image/(?<remaining>.*), /config/${remaining}
spring.cloud.gateway.routes[6].id=supngin-api-service
spring.cloud.gateway.routes[6].uri=lb://supngin-api-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/project/dam/supngin/api/service/**, /project/dam/supngin/inter-api/service/**
spring.cloud.gateway.routes[6].filters[0]=RewritePath=/project/dam/supngin/(?<remaining>.*), /${remaining}
spring.cloud.gateway.routes[7].id=supngin-oodm-gateway
spring.cloud.gateway.routes[7].uri=lb://supngin-oodm-gateway
spring.cloud.gateway.routes[7].predicates[0]=Path=/project/dam/supngin/api/dam/**, /project/dam/supngin/inter-api/dam/**, /open-api/supos/oodm/**
spring.cloud.gateway.routes[7].filters[0]=RewritePath=/project/dam/supngin/(?<remaining>.*), /${remaining}
spring.cloud.gateway.routes[8].id=app
spring.cloud.gateway.routes[8].uri=http://www.supos.com
spring.cloud.gateway.routes[8].predicates[0]=Path=/open-api/apps/**
spring.cloud.gateway.routes[8].filters[0]=AddTenantAppUriHeader=X-Tenant-Url
spring.cloud.gateway.routes[8].filters[1]=RequestHeaderToRequestUri=X-Tenant-Url
spring.cloud.gateway.routes[9].id=websocket-server
spring.cloud.gateway.routes[9].uri=ws://websocket-server:8080/inter-api/notification/ws/notice
spring.cloud.gateway.routes[9].predicates[0]=Path=/inter-api/notification/ws/notice
spring.cloud.gateway.routes[10].id=compose-broker
spring.cloud.gateway.routes[10].uri=lb:ws://compose-broker
spring.cloud.gateway.routes[10].predicates[0]=Path=/open-api/broker/ws
spring.cloud.gateway.routes[10].filters[0]=SetPortAfterLoadBalancer=5069
spring.cloud.gateway.routes[11].id=lake-dashboard
spring.cloud.gateway.routes[11].uri=http://lake-dashboard:8097
spring.cloud.gateway.routes[11].predicates[0]=Path=/project/dlake/{*newPath}
spring.cloud.gateway.routes[11].filters[0]=SetPath=http://lake-dashboard:8097/{newPath}
spring.cloud.gateway.routes[12].id=video-ws
spring.cloud.gateway.routes[12].uri=ws://videoserver:8800
spring.cloud.gateway.routes[12].predicates[0]=Path=/open-api/video/**
spring.cloud.gateway.routes[12].filters[0]=RewritePath=/open-api/(?<remaining>.*), /${remaining}
spring.cloud.gateway.routes[13].id=video
spring.cloud.gateway.routes[13].uri=http://videoserver:8800
spring.cloud.gateway.routes[13].predicates[0]=Path=/inter-api/video/**
spring.cloud.gateway.routes[13].filters[0]=RewritePath=/inter-api/(?<remaining>.*), /${remaining}
spring.cloud.gateway.routes[14].id=app-static-resource
spring.cloud.gateway.routes[14].uri=lb://app
spring.cloud.gateway.routes[14].predicates[0]=Path=/resource/{appIdStr:^App_.+}/**
spring.cloud.gateway.routes[14].filters[0]=RewritePath=/resource/(?<remaining>.*), /api/app/manager/images/preview/${remaining}
spring.cloud.gateway.routes[15].id=auth-login
spring.cloud.gateway.routes[15].uri=lb://auth
spring.cloud.gateway.routes[15].predicates[0]=Path=/inter-api/auth/login
spring.cloud.gateway.routes[15].filters[0]=RewritePath=/inter-api/auth/login, /inter-api/auth/v1/user/login
spring.cloud.gateway.routes[16].id=auth-logout
spring.cloud.gateway.routes[16].uri=lb://auth
spring.cloud.gateway.routes[16].predicates[0]=Path=/inter-api/auth/logout
spring.cloud.gateway.routes[16].filters[0]=RewritePath=/inter-api/auth/logout, /inter-api/auth/v1/user/logout
spring.cloud.gateway.routes[17].id=auth-companyChange
spring.cloud.gateway.routes[17].uri=lb://auth
spring.cloud.gateway.routes[17].predicates[0]=Path=/inter-api/auth/company/change
spring.cloud.gateway.routes[17].filters[0]=RewritePath=/inter-api/auth/company/change, /inter-api/auth/v1/company/change
spring.cloud.gateway.routes[18].id=auth-refreshToken
spring.cloud.gateway.routes[18].uri=lb://auth
spring.cloud.gateway.routes[18].predicates[0]=Path=/inter-api/auth/token/refresh
spring.cloud.gateway.routes[18].filters[0]=RewritePath=/inter-api/auth/token/refresh, /inter-api/auth/v1/token/refresh
spring.cloud.gateway.routes[19].id=app-forward
spring.cloud.gateway.routes[19].uri=http://www.supos.com
spring.cloud.gateway.routes[19].predicates[0]=Path=/msService/**,/appws/**
spring.cloud.gateway.routes[19].filters[0]=ForwardAppUrl
ribbon.ServerListRefreshInterval=15000
ribbon.ReadTimeout=10000
ribbon.ConnectTimeout=5000
ribbon.eager-load.enabled=true
ribbon.eager-load.clients=supos-iam
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS
management.endpoint.shutdown.enabled=false
management.health.db.enabled=false
management.health.mail.enabled=false
management.health.redis.enabled=false
management.health.mongo.enabled=false
management.health.elasticsearch.enabled=false
management.health.jms.enabled=false
management.health.rabbit.enabled=false
management.health.solr.enabled=false
management.health.cassandra.enabled=false
management.health.couchbase.enabled=false
management.health.influxdb.enabled=false
management.health.ldap.enabled=false
management.health.neo4j.enabled=false
jwt.secret=${REPLACE_ME}
jwt.expiration=604800
rbac.enable=true
path.black-list=
path.exclude-global[0]=/auth/realms/supos/auth/login
path.exclude-global[1]=/api/auth/users/logout
path.exclude-global[2]=/inter-api/systemconfig/v1/config/catalog/by/module
path.exclude-global[3]=/api/auth/users/login
path.exclude-global[4]=/api/auth/checkIntegration
path.exclude-global[5]=/api/config/configInfo/**
path.exclude-global[6]=/api/config/download/**
path.exclude-global[7]=/api/image/download/**
path.exclude-global[8]=/api/compose/manage/download/**
path.exclude-global[9]=/api/app/manager/staticFolderDownload/**
path.exclude-global[10]=/api/app/manager/export/download/**
path.exclude-global[11]=/api/app/manager/images/AppIconPreview/**
path.exclude-global[12]=/api/auth/download/user/template/**
path.exclude-global[13]=/open-api/supos/auth/v2/code/authorize/**
path.exclude-global[14]=/open-api/video/**
path.exclude-global[15]=/project/dam/supngin/api/dam/*/download/**
path.exclude-global[16]=/project/dam/supngin/api/dam/excel/data/export/download/**
path.exclude-global[17]=/project/dam/supngin/api/dam/excel/data/import/download/**
path.exclude-global[18]=/project/dam/supngin/api/dam/runtime/download/csv/**
path.exclude-global[19]=/project/dam/supngin/api/config/download/**
path.exclude-global[20]=/api/compose/manage/v3/download/objectselector/csv/**
path.exclude-global[21]=/resource/**
path.exclude-global[22]=/msService/public/**
path.exclude-global[23]=/inter-api/auth/v1/oauth2/authorize
path.exclude-global[24]=/inter-api/auth/login
path.exclude-global[25]=/api/auth/users/logout
path.exclude-global[26]=/inter-api/auth/company/change
path.exclude-global[27]=/msService/appws/**
path.exclude-global[28]=/appws/**
path.exclude-global[29]=/inter-api/auth/v1/head-office/**
path.exclude-global[30]=/inter-api/auth/v1/branch-office/**
path.exclude-sign=
snow-flake.datacenterId=${REPLACE_ME}
snow-flake.workerId=${REPLACE_ME}
filter.cacheRequestBodyGlobalFilter.enabled=true
keycloak.client=${REPLACE_ME}
keycloak.grant-type=${REPLACE_ME}
custom.dev.enable=false
