spring.application.name=notification-engine
cloud.stream.bindings.tenant-input.destination=supOS_tenant
cloud.stream.bindings.tenant-input.content-type=application/json
cloud.stream.bindings.tenant-input.group=${spring.application.name}
management.health.db.enabled=false
server.port=30100
server.servlet.context-path=/
supfusion.websocket.host=websocket-server:8080
supfusion.notification.thread.coreSize=5
supfusion.notification.thread.maxPoolSzie=5
supfusion.notification.thread.queueSize=200
supfusion.cloud.i18n.locale-modules[0]=notificationEngine
supfusion.cloud.i18n.module-versions[0]=forceChange:notificationEngine202101081213
supfusion.cloud.i18n.modules[0]=notificationEngine
supfusion.cloud.i18n.modules[1]=notificationEmail
supfusion.cloud.i18n.basename=forceChange:i18n/
supfusion.cloud.tenant.sync-cache=false
supfusion.cloud.tenant.init-getter=false
supfusion.swagger.enable=true
