supfusion.cloud.i18n.locale-modules[0]=systemConfig
supfusion.cloud.i18n.locale-modules[1]=workflow
supfusion.cloud.i18n.locale-modules[2]=organization
supfusion.cloud.i18n.locale-modules[3]=systemCode
supfusion.cloud.i18n.locale-modules[4]=rbac
supfusion.cloud.i18n.locale-modules[5]=theme
supfusion.cloud.i18n.module-versions[0]=forceChange:systemConfig202101081213
supfusion.cloud.i18n.module-versions[1]=forceChange:workflow202101081213
supfusion.cloud.i18n.module-versions[2]=forceChange:organization202101081213
supfusion.cloud.i18n.module-versions[3]=forceChange:systemCode202101081213
supfusion.cloud.i18n.module-versions[4]=forceChange:rbac202101081213
supfusion.cloud.i18n.module-versions[5]=forceChange:theme202101081213
supfusion.cloud.i18n.modules[0]=systemConfig
supfusion.cloud.i18n.modules[1]=notificationDingtalk
supfusion.cloud.i18n.modules[2]=notificationWechat
supfusion.cloud.i18n.modules[3]=notificationAdmin
supfusion.cloud.i18n.modules[4]=organization
supfusion.cloud.i18n.modules[5]=systemCode
supfusion.cloud.i18n.modules[6]=reg
supfusion.cloud.i18n.modules[7]=sys
supfusion.cloud.i18n.modules[8]=rbac
supfusion.cloud.i18n.modules[9]=i18n
supfusion.cloud.i18n.modules[10]=BaseSet
supfusion.cloud.i18n.modules[11]=theme
mybatis-plus.type-aliases-package=com.supcon.supfusion.rbac.dao.po
mybatis-plus.type-aliases-package=com.supcon.supfusion.theme.dao.po
mybatis-plus.type-enums-package=com.supcon.supfusion.rbac.dao.enums
org-type=single
file.upload-dir=./uploads
rbac.default-systemRole-name=管理员角色
rbac.default-language=zh_CN

supfusion.i18n.xlsx-upload-max-size=15
supfusion.i18n.i18n-key-length-num-defa=255
supfusion.i18n.i18n-value-length-num-defa=500
supfusion.i18n.i18n-resource-path=i18nResource/i18n/
supfusion.i18n.i18n-resource-code=i18n
supfusion.i18n.i18n-resource-version=i18n202008190930
supfusion.i18n.default-resource-path=i18nResource/sys/
supfusion.i18n.default-resource-code=sys
supfusion.i18n.default-resource-version=sys202007211025
supfusion.i18n.default-utc=UTC+8
supfusion.i18n.default-language=zh_CN
mybatis-plus.type-aliases-package=com.supcon.supfusion.i18n.dao.po
mybatis-plus.mapper-locations[0]=classpath:com/supcon/supfusion/i18n/dao/mapper/${supfusion.cloud.datasource.connect.system.db-type}/*.xml
mybatis-plus.global-config.db-config.id-type=ID_WORKER
mybatis-plus.global-config.db-config.field-strategy=NOT_EMPTY
mybatis-plus.global-config.db-config.db-type=${supfusion.cloud.datasource.connect.system.db-type}
mybatis-plus.global-config.db-config.optimistic-lock-enabled=false
mybatis-plus.global-config.db-config.logic-delete-enabled=true
mybatis-plus.configuration.map-underscore-to-camel-case=true