supfusion.cloud.nacos.server-addr=http://${SUPOS_NACOS_ADDRESS:127.0.0.1:8848}
supfusion.cloud.nacos.username=${SUPOS_NACOS_USERNAME:nacos}
supfusion.cloud.nacos.password=${REPLACE_ME}
supfusion.cloud.registry.enabled=true
supfusion.cloud.registry.secure=false
supfusion.cloud.registry.weight=1
supfusion.cloud.registry.group=${SUPOS_NACOS_REGISTRY_GROUP:prod}
supfusion.cloud.discovery.enabled=true
supfusion.cloud.discovery.group=${CLOUD_DISCOVERY_GROUP:prod}
supfusion.cloud.registry.partition=true
supfusion.cloud.discovery.partition=forceChange:false
