bap.home=
bap.default.company.code=defaultCompany
bap.default.company.name=defaultCompany
bap.default.isThreeRoles=false
bap.initsupos=false
script.basePath=${bap.home}/bap-workspace/scripts
WebSocketUrl=127.0.0.1:8080
bap.allow.empty.password=${REPLACE_ME}
bap.auditLog.global.enable=true
bap.company.single=true
bap.supmobile.validateCode.msgPath=classpath:META-INF/supmobile-validatecode-msg.xml
deploy.timeout.detection=600000
filePreview.IsFileView=true
orchid.env=product
ribbon.ConnectTimeout=60000
ribbon.ReadTimeout=60000
spring.http.encoding.charset=utf-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=true
spring.main.allow-bean-definition-overriding=true
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
entityconf.generatePath=${bap.home}/bap-workspace/generate
logging.config=classpath:logback-bap.xml
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
supfusion.cloud.i18n.temp=${bap.home}/bap-workspace/i18n_temp
logPath=${bap.home}/../logs/${spring.application.name}/
swagger.enable=false
spring.jackson.serialization.fail-on-empty-beans=false
spring.mvc.static-path-pattern=/**
project.staticPath=${bap.home}/bap-workspace/customFile/static/
spring.resources.static-locations=forceChange:classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/,file:${project.staticPath},classpath:/custom/,classpath:/static/
supfusion.cloud.i18n.basename=LANG-INF/l10n/
maven.repository.path=${bap.home}/assembly/repository/maven
druid.monitor.enabled=false
integration.supos.enabled=false
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.enabled=true
supos.isSaasPackage=false
server.tomcat.max-http-post-size=102400000
bap.suposinit=false
