server.port=30000
supfusion.cloud.i18n.module-versions[0]=forceChange:appConfig202105271111
supfusion.cloud.i18n.basename=forceChange:i18n/
supfusion.cloud.i18n.use-get-all-module=true
configuration-services.workspace=../../bap-workspace
configuration-services.uploadLogPath=forceChange:${work.dir}/logs/appUpload
#supfusion.cloud.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
#supfusion.cloud.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#supfusion.cloud.hibernate.dialect=com.supcon.supfusion.base.hibernate.MysqlDialect
#supfusion.cloud.hibernate.dialect=com.supcon.supfusion.base.hibernate.MariadbDialect
bap.suposinit=false
