spring.application.name=auth
server.port=30175
server.servlet.context-path=/
management.health.db.enabled=false
supfusion.cloud.i18n.locale-modules[0]=userManager
supfusion.cloud.i18n.module-versions[0]=forceChange:userManager202101081213
supfusion.cloud.i18n.modules[0]=userManager
supfusion.cloud.i18n.basename=forceChange:i18n/
kaptcha.border=yes
kaptcha.border.color=105,179,90
kaptcha.textproducer.font.color=blue
kaptcha.textproducer.font.size=30
kaptcha.textproducer.font.names=宋体,楷体
kaptcha.textproducer.char.length=4
kaptcha.image.width=120
kaptcha.image.height=40
kaptcha.session.key=code