management.health.db.enabled=false
server.port=30170
server.servlet.context-path=/
spring.application.name=rbac
spring.messages.basename=i18n/rbac
spring.cloud.stream.kafka.bindings.rbac_input_log.destination=topic.permission.refresh
spring.cloud.stream.kafka.bindings.rbac_input_log.content-type=application/json
spring.cloud.stream.kafka.bindings.rbac_input_log.group=${spring.application.name}
supfusion.cloud.scan.enabled=flase
supfusion.cloud.scan.host=http://rbac-service:30170
supfusion.cloud.i18n.locale-modules[0]=rbac
supfusion.cloud.i18n.module-versions[0]=forceChange:rbac202106100944
#supfusion.cloud.i18n.modules[0]=rbac
#supfusion.cloud.i18n.modules[1]=i18n
#supfusion.cloud.i18n.modules[2]=BaseSet
supfusion.cloud.i18n.use-get-all-module=true
supfusion.cloud.i18n.basename=forceChange:i18n/
mybatis-plus.type-aliases-package=com.supcon.supfusion.rbac.dao.po
mybatis-plus.type-enums-package=com.supcon.supfusion.rbac.dao.enums
rbac.default-systemRole-name=管理员角色
rbac.default-language=zh_CN
rbac.initsupos=false