supfusion.cloud.jwt.enabled=true
supfusion.cloud.jwt.header=Authorization
supfusion.cloud.jwt.tokenHead=${REPLACE_ME}
supfusion.cloud.jwt.symmetric=false
supfusion.cloud.jwt.expiration=604800
supfusion.cloud.jwt.secret=${REPLACE_ME}
