spring.datasource.type=com.supcon.supfusion.framework.scaffold.dbp.MultiTenantDatasource
spring.datasource.initialization-mode=never
spring.application.name=theme
server.port=30115
server.servlet.context-path=/
supfusion.cloud.system.top-level-domain=
supfusion.cloud.system.host-ip=
supfusion.cloud.system.deploy-mode=single
supfusion.cloud.i18n.locale-modules[0]=theme
supfusion.cloud.i18n.module-versions[0]=forceChange:theme202101081213
supfusion.cloud.i18n.modules[0]=theme
supfusion.cloud.i18n.basename=forceChange:i18n/
mybatis-plus.type-aliases-package=com.supcon.supfusion.theme.dao.po
management.health.db.enabled=false
