spring.application.name=customProperty
server.port=30210
server.servlet.context-path=/
supfusion.cloud.system.top-level-domain=
supfusion.cloud.system.host-ip=
supfusion.cloud.system.deploy-mode=single
supfusion.cloud.i18n.enabled=true
supfusion.cloud.i18n.host=http://127.0.0.1:30130
supfusion.cloud.i18n.locale-modules[0]=customProperty
supfusion.cloud.i18n.module-versions[0]=forceChange:customProperty202101081213
supfusion.cloud.i18n.basename=forceChange:i18n/
supfusion.cloud.i18n.use-get-all-module=true
mybatis-plus.type-aliases-package=com.supcon.supfusion.custon.property.dao.entity
management.health.db.enabled=false