management.health.db.enabled=false
server.port=30150
server.servlet.context-path=/
spring.application.name=flow-service
mybatis-plus.type-aliases-package=com.supcon.supfusion.flow.common.po
supfusion.cloud.i18n.locale-modules[0]=workflow
supfusion.cloud.i18n.module-versions[0]=forceChange:workflow202101081213
supfusion.cloud.i18n.modules[0]=workflow
supfusion.cloud.i18n.basename=forceChange:i18n/
spring.cloud.stream.bindings.tenant-input.destination=supOS_tenant
spring.cloud.stream.bindings.tenant-input.content-type=application/json
spring.cloud.stream.bindings.tenant-input.group=${spring.application.name}