server.port=30020
spring.application.name=baseService
logPath=${bap.home}/../logs/baseService-logs
spring.resources.static-locations=file:${bap.home}/bap-workspace/static/
supfusion.cloud.i18n.locale-modules[0]=baseservice
supfusion.cloud.i18n.module-versions[0]=forceChange:baseservice202101081213
supfusion.cloud.i18n.modules[0]=baseservice
supfusion.cloud.i18n.useGetAllModule=true
supfusion.cloud.i18n.heartbeat-seconds=10
supfusion.cloud.i18n.basename=forceChange:i18n/
base.initsupos=false