server.port=30175
spring.application.name=adp-lite
supfusion.cloud.i18n.basename=i18n/
supfusion.cloud.i18n.host=http://127.0.0.1:${server.port}
mybatis-plus.mapper-locations[0]=classpath:com/supcon/supfusion/i18n/dao/mapper/${supfusion.cloud.datasource.connect.system.db-type}/*.xml
mybatis-plus.mapper-locations[1]=classpath:mappers/*.xml
mybatis-plus.mapper-locations[2]=classpath:mapper/*.xml
mybatis-plus.mapper-locations[3]=classpath:mappers/${supfusion.cloud.datasource.connect.system.db-type}/*.xml
supfusion.supos.ak=${REPLACE_ME}
supfusion.supos.sk=${REPLACE_ME}
supfusion.supos.supos-host=${SUPOS_ADDRESS:http://127.0.0.1:${server.port}}
supfusion.cloud.i18n.locale-modules[0]=reg
supfusion.cloud.i18n.module-versions[0]=reg202105100105
supfusion.cloud.i18n.modules[0]=reg
supfusion.cloud.i18n.locale-modules[1]=organization
supfusion.cloud.i18n.module-versions[1]=organization202105100105
supfusion.cloud.i18n.modules[1]=organization
supfusion.cloud.i18n.locale-modules[2]=rbac
supfusion.cloud.i18n.module-versions[2]=rbac202105100105
supfusion.cloud.i18n.modules[2]=rbac
supfusion.cloud.i18n.locale-modules[3]=userManagement
supfusion.cloud.i18n.module-versions[3]=userManagement202105100105
supfusion.cloud.i18n.modules[3]=userManagement
supfusion.cloud.i18n.locale-modules[4]=systemCode
supfusion.cloud.i18n.module-versions[4]=systemCode202105100105
supfusion.cloud.i18n.modules[4]=systemCode
supfusion.cloud.i18n.locale-modules[5]=systemConfig
supfusion.cloud.i18n.module-versions[5]=systemConfig202105100105
supfusion.cloud.i18n.modules[5]=systemConfig
supfusion.cloud.i18n.locale-modules[6]=notificationApiServer
supfusion.cloud.i18n.module-versions[6]=notificationApiServer202105100105
supfusion.cloud.i18n.modules[6]=notificationApiServer
supfusion.cloud.i18n.locale-modules[7]=notificationAdmin
supfusion.cloud.i18n.module-versions[7]=notificationAdmin202105100105
supfusion.cloud.i18n.modules[7]=notificationAdmin
supfusion.cloud.i18n.locale-modules[8]=notificationMobile
supfusion.cloud.i18n.module-versions[8]=notificationMobile202105100105
supfusion.cloud.i18n.modules[8]=notificationMobile
supfusion.cloud.i18n.locale-modules[9]=notificationSupplant
supfusion.cloud.i18n.module-versions[9]=notificationSupplant202105100105
supfusion.cloud.i18n.modules[9]=notificationSupplant
supfusion.cloud.i18n.locale-modules[10]=notificationSMS
supfusion.cloud.i18n.module-versions[10]=notificationSMS202105100105
supfusion.cloud.i18n.modules[10]=notificationSMS
supfusion.cloud.i18n.locale-modules[11]=notificationDingtalk
supfusion.cloud.i18n.module-versions[11]=notificationDingtalk202105100105
supfusion.cloud.i18n.modules[11]=notificationDingtalk
supfusion.cloud.i18n.locale-modules[12]=notificationWechat
supfusion.cloud.i18n.module-versions[12]=notificationWechat202105100105
supfusion.cloud.i18n.modules[12]=notificationWechat
supfusion.cloud.i18n.locale-modules[13]=auditlog
supfusion.cloud.i18n.module-versions[13]=auditlog202105100105
supfusion.cloud.i18n.modules[13]=auditlog
supfusion.cloud.i18n.modules[14]=sys
supfusion.cloud.i18n.modules[15]=i18n
