management.health.db.enabled=false
server.port=30155
server.servlet.context-path=/
spring.application.name=systemconfig
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
mybatis-plus.type-aliases-package=com.supcon.supfusion.systemconfig.dao.entity
mybatis-plus.global-config.db-config.max-file-size=200MB
mybatis-plus.global-config.db-config.max-request-size=215MB
supfusion.cloud.i18n.locale-modules[0]=systemConfig
supfusion.cloud.i18n.module-versions[0]=forceChange:systemConfig202101081213
supfusion.cloud.i18n.basename=forceChange:i18n/
supfusion.cloud.i18n.modules[0]=systemConfig
supfusion.cloud.i18n.modules[1]=notificationDingtalk
supfusion.cloud.i18n.modules[2]=notificationWechat
supfusion.cloud.i18n.modules[3]=notificationAdmin
file.upload-dir=./uploads


