management.health.db.enabled=false
spring.application.name=file-server
spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB
server.port=30191
server.servlet.context-path=/
server.tomcat.max-swallow-size=2048MB
supfusion.cloud.tenant.sync-cache=false
supfusion.cloud.tenant.init-getter=false
supfusion.cloud.i18n.locale-modules[0]=fileServer
supfusion.cloud.i18n.module-versions[0]=forceChange:fileServer202101081213
supfusion.cloud.i18n.modules[0]=fileServer
supfusion.cloud.i18n.heartbeat-seconds=3000
supfusion.cloud.file.filePreview=false
supfusion.cloud.i18n.basename=forceChange:i18n/
feign.client.default-config=default
feign.client.default-to-properties=true
feign.client.config.default.connect-timeout=2000
feign.client.config.default.read-timeout=12000
feign.httpclient.enabled=true
minio.endpoint=http://localhost:30200
minio.accessKey=${REPLACE_ME}
minio.secretKey=${REPLACE_ME}
minio.fileTypes=doc,md,mp3,mp4
