spring.application.name=notification-apiserver
cloud.stream.bindings.tenant-input.destination=supOS_tenant
cloud.stream.bindings.tenant-input.content-type=application/json
cloud.stream.bindings.tenant-input.group=${spring.application.name}
management.health.db.enabled=false
server.port=30101
server.servlet.context-path=/
supfusion.notification.thread.coreSize=5
supfusion.notification.thread.maxPoolSzie=5
supfusion.notification.thread.queueSize=200
supfusion.cloud.i18n.basename=i18n/
supfusion.cloud.i18n.locale-modules[0]=notificationApiServer
supfusion.cloud.i18n.module-versions[0]=forceChange:notificationApiServer202101081213
supfusion.cloud.i18n.modules[0]=notificationApiServer
supfusion.cloud.tenant.sync-cache=false
supfusion.cloud.tenant.init-getter=false
supfusion.swagger.enable=true
