supfusion.cloud.datasource.connect.use-system=true
supfusion.cloud.datasource.connect.system.db-type=${SUPOS_SYSTEM_DB_TYPE:postgresql}
supfusion.cloud.datasource.connect.system.db-name=${SUPOS_SYSTEM_DB_NAME:adp}
supfusion.cloud.datasource.connect.system.host=${SUPOS_SYSTEM_DB_HOST:postgres}
supfusion.cloud.datasource.connect.system.port=${SUPOS_SYSTEM_DB_PORT:5432}
supfusion.cloud.datasource.connect.system.username=${SUPOS_SYSTEM_DB_USERNAME:adp}
supfusion.cloud.datasource.connect.system.password=${REPLACE_ME}
supfusion.cloud.datasource.druid.remove-abandoned=true
supfusion.cloud.datasource.druid.log-abandoned=true
supfusion.cloud.datasource.druid.init-pool-size=1
supfusion.cloud.datasource.druid.min-pool-size=1
supfusion.cloud.datasource.druid.max-pool-size=100
supfusion.cloud.datasource.druid.slow-sql-millis=30000
supfusion.cloud.datasource.druid.max-live-millis=90000
supfusion.cloud.datasource.druid.connection-timeout=30000
supfusion.cloud.datasource.druid.idle-live-millis=30000
supfusion.cloud.datasource.druid.idle-test-interval-millis=30000
supfusion.cloud.datasource.druid.test-while-idle=true
supfusion.cloud.datasource.druid.validationQuerySql=${VALIDATIONQUERYSQL:SELECT 1}
supfusion.cloud.datasource.script.script-root-dirs=classpath*:META-INF/
supfusion.cloud.datasource.script.version-prefix=forceChange:##
supfusion.cloud.tenant.sync-cache=false
supfusion.cloud.tenant.init-getter=false
supfusion.cloud.tenant.register=false
spring.datasource.type=com.supcon.supfusion.framework.scaffold.dbp.MultiTenantDatasource
spring.datasource.initialization-mode=never
