spring.application.name=printer
server.port=forceChange:30216
server.servlet.context-path=/
supfusion.cloud.i18n.locale-modules[0]=printer
supfusion.cloud.i18n.module-versions[0]=forceChange:printer202104101614
supfusion.cloud.i18n.modules[0]=printer
supfusion.cloud.i18n.heartbeat-seconds=3000
supfusion.cloud.i18n.basename=forceChange:i18n/
