spring.application.name=systemcode
server.port=30180
server.servlet.context-path=/
supfusion.cloud.system.top-level-domain=
supfusion.cloud.system.host-ip=
supfusion.cloud.system.deploy-mode=single
supfusion.cloud.i18n.enabled=true
supfusion.cloud.i18n.host=http://127.0.0.1:30130
supfusion.cloud.i18n.locale-modules[0]=systemCode
supfusion.cloud.i18n.module-versions[0]=forceChange:systemCode202106031654
supfusion.cloud.i18n.basename=forceChange:i18n/
#supfusion.cloud.i18n.modules[0]=systemCode
#supfusion.cloud.i18n.modules[1]=reg
#supfusion.cloud.i18n.modules[2]=sys
#supfusion.cloud.i18n.modules[3]=organization
supfusion.cloud.i18n.use-get-all-module=true
mybatis-plus.type-aliases-package=com.supcon.supfusion.systemcode.dao.po
management.health.db.enabled=false
