CREATE TABLE IF NOT EXISTS sms_boxsending (
  id BIGSERIAL PRIMARY KEY,
  appid VARCHAR(128),
  sender VARCHAR(128),
  receiver TEXT,
  content TEXT,
  sendtime VARCHAR(64),
  inserttime VARCHAR(64),
  retrytimes INTEGER DEFAULT 0,
  pri VARCHAR(64),
  inpool VARCHAR(64),
  inpooltime VARCHAR(64),
  task_batchname VARCHAR(256),
  addtion1 TEXT,
  addtion2 TEXT,
  addtion3 TEXT,
  moduleid VARCHAR(128),
  sendmode VARCHAR(64),
  configid VARCHAR(128),
  linkid1 VARCHAR(128),
  linkid2 VARCHAR(128),
  ifreceipt VARCHAR(64),
  validityperiod VARCHAR(64),
  outteruser VARCHAR(128),
  tenant_id VARCHAR(64)
);
