-- Complete the legacy BAP organization compatibility views used by workflow
-- and entity services.
CREATE OR REPLACE VIEW public.base_department (
  id,
  version,
  code,
  name,
  description,
  full_path_name,
  lay_no,
  lay_rec,
  sort,
  cid,
  parent_id,
  valid,
  leaf,
  create_staff_id,
  modify_staff_id,
  delete_staff_id,
  create_time,
  modify_time,
  delete_time,
  staff_id,
  objparame,
  objparamd,
  objparamc,
  objparamb,
  objparama,
  res_scparame,
  res_scparamd,
  res_scparamc,
  res_scparamb,
  res_scparama,
  charparame,
  charparamd,
  charparamc,
  charparamb,
  charparama,
  numberparame,
  numberparamd,
  numberparamc,
  numberparamb,
  numberparama,
  dateparame,
  dateparamd,
  dateparamc,
  dateparamb,
  dateparama,
  integerparame,
  integerparamd,
  integerparamc,
  integerparamb,
  integerparama,
  customer_field2,
  customer_field1,
  sc_nature,
  uuid,
  is_virtual
) AS
SELECT
  id,
  row_version AS version,
  code,
  name,
  description,
  full_path AS full_path_name,
  lay_no,
  lay_rec,
  sort,
  company_id AS cid,
  parent_id,
  valid,
  leaf,
  create_staff_id,
  modify_staff_id,
  NULL::BIGINT AS delete_staff_id,
  create_time,
  modify_time,
  NULL::TIMESTAMP AS delete_time,
  NULL::BIGINT AS staff_id,
  NULL::VARCHAR(255) AS objparame,
  NULL::VARCHAR(255) AS objparamd,
  NULL::VARCHAR(255) AS objparamc,
  NULL::VARCHAR(255) AS objparamb,
  NULL::VARCHAR(255) AS objparama,
  NULL::VARCHAR(255) AS res_scparame,
  NULL::VARCHAR(255) AS res_scparamd,
  NULL::VARCHAR(255) AS res_scparamc,
  NULL::VARCHAR(255) AS res_scparamb,
  NULL::VARCHAR(255) AS res_scparama,
  NULL::VARCHAR(255) AS charparame,
  NULL::VARCHAR(255) AS charparamd,
  NULL::VARCHAR(255) AS charparamc,
  NULL::VARCHAR(255) AS charparamb,
  NULL::VARCHAR(255) AS charparama,
  NULL::DOUBLE PRECISION AS numberparame,
  NULL::DOUBLE PRECISION AS numberparamd,
  NULL::DOUBLE PRECISION AS numberparamc,
  NULL::DOUBLE PRECISION AS numberparamb,
  NULL::DOUBLE PRECISION AS numberparama,
  NULL::TIMESTAMP AS dateparame,
  NULL::TIMESTAMP AS dateparamd,
  NULL::TIMESTAMP AS dateparamc,
  NULL::TIMESTAMP AS dateparamb,
  NULL::TIMESTAMP AS dateparama,
  NULL::INTEGER AS integerparame,
  NULL::INTEGER AS integerparamd,
  NULL::INTEGER AS integerparamc,
  NULL::INTEGER AS integerparamb,
  NULL::INTEGER AS integerparama,
  NULL::VARCHAR(255) AS customer_field2,
  NULL::VARCHAR(255) AS customer_field1,
  NULL::VARCHAR(255) AS sc_nature,
  NULL::VARCHAR(64) AS uuid,
  sys_flag AS is_virtual
FROM public.org_department;

CREATE OR REPLACE VIEW public.base_departmentwork (
  id,
  version,
  department_id,
  staff_id,
  valid,
  transfer_out_deal_time,
  transfer_in_deal_time,
  transfer_out_dealer_id,
  transfer_in_dealer_id,
  edit_date,
  end_time,
  start_time
) AS
SELECT
  id,
  row_version AS version,
  dept_id AS department_id,
  person_id AS staff_id,
  valid,
  NULL::TIMESTAMP AS transfer_out_deal_time,
  NULL::TIMESTAMP AS transfer_in_deal_time,
  NULL::BIGINT AS transfer_out_dealer_id,
  NULL::BIGINT AS transfer_in_dealer_id,
  NULL::TIMESTAMP AS edit_date,
  NULL::TIMESTAMP AS end_time,
  NULL::TIMESTAMP AS start_time
FROM public.org_person_department;

CREATE OR REPLACE VIEW public.base_position (
  id,
  version,
  code,
  name,
  description,
  full_path_name,
  lay_no,
  lay_rec,
  sort,
  cid,
  department_id,
  parent_id,
  valid,
  leaf,
  create_staff_id,
  modify_staff_id,
  delete_staff_id,
  create_time,
  modify_time,
  delete_time,
  objparame,
  objparamd,
  objparamc,
  objparamb,
  objparama,
  res_scparame,
  res_scparamd,
  res_scparamc,
  res_scparamb,
  res_scparama,
  charparame,
  charparamd,
  charparamc,
  charparamb,
  charparama,
  numberparame,
  numberparamd,
  numberparamc,
  numberparamb,
  numberparama,
  dateparame,
  dateparamd,
  dateparamc,
  dateparamb,
  dateparama,
  integerparame,
  integerparamd,
  integerparamc,
  integerparamb,
  integerparama,
  uuid,
  is_virtual,
  sc_nature
) AS
SELECT
  id,
  row_version AS version,
  code,
  name,
  description,
  full_path AS full_path_name,
  lay_no,
  lay_rec,
  sort,
  company_id AS cid,
  dep_id AS department_id,
  parent_id,
  valid,
  leaf,
  create_staff_id,
  modify_staff_id,
  NULL::BIGINT AS delete_staff_id,
  create_time,
  modify_time,
  NULL::TIMESTAMP AS delete_time,
  NULL::VARCHAR(255) AS objparame,
  NULL::VARCHAR(255) AS objparamd,
  NULL::VARCHAR(255) AS objparamc,
  NULL::VARCHAR(255) AS objparamb,
  NULL::VARCHAR(255) AS objparama,
  NULL::VARCHAR(255) AS res_scparame,
  NULL::VARCHAR(255) AS res_scparamd,
  NULL::VARCHAR(255) AS res_scparamc,
  NULL::VARCHAR(255) AS res_scparamb,
  NULL::VARCHAR(255) AS res_scparama,
  NULL::VARCHAR(255) AS charparame,
  NULL::VARCHAR(255) AS charparamd,
  NULL::VARCHAR(255) AS charparamc,
  NULL::VARCHAR(255) AS charparamb,
  NULL::VARCHAR(255) AS charparama,
  NULL::DOUBLE PRECISION AS numberparame,
  NULL::DOUBLE PRECISION AS numberparamd,
  NULL::DOUBLE PRECISION AS numberparamc,
  NULL::DOUBLE PRECISION AS numberparamb,
  NULL::DOUBLE PRECISION AS numberparama,
  NULL::TIMESTAMP AS dateparame,
  NULL::TIMESTAMP AS dateparamd,
  NULL::TIMESTAMP AS dateparamc,
  NULL::TIMESTAMP AS dateparamb,
  NULL::TIMESTAMP AS dateparama,
  NULL::INTEGER AS integerparame,
  NULL::INTEGER AS integerparamd,
  NULL::INTEGER AS integerparamc,
  NULL::INTEGER AS integerparamb,
  NULL::INTEGER AS integerparama,
  NULL::VARCHAR(64) AS uuid,
  sys_flag AS is_virtual,
  NULL::VARCHAR(255) AS sc_nature
FROM public.org_position;

CREATE OR REPLACE VIEW public.base_staff (
  id,
  version,
  code,
  name,
  sex,
  mobile,
  email,
  work_status,
  security_class,
  valid,
  user_id,
  user_name,
  main_position_id,
  create_staff_id,
  modify_staff_id,
  delete_staff_id,
  create_time,
  modify_time,
  delete_time,
  memo,
  customer_field2,
  customer_field1,
  uuid,
  sort,
  sys_flag,
  higher_leader_staff_id,
  leader_staff_id,
  ygxs,
  hukouxingzhi,
  hukoudi,
  dangandi,
  degree,
  educational,
  profession,
  biye_time,
  school,
  foreign_language,
  compute_level,
  height,
  virtual_mobile,
  politics_info,
  nation,
  marriage,
  id_card,
  native_place,
  birthday,
  avatar_url,
  sign_pic_url
) AS
SELECT
  op.id,
  op.row_version AS version,
  op.code,
  op.name,
  op.gender AS sex,
  op.phone AS mobile,
  op.email,
  op.status AS work_status,
  op.classified_level AS security_class,
  op.valid,
  au.id AS user_id,
  au.user_name,
  op.main_position AS main_position_id,
  op.create_staff_id,
  op.modify_staff_id,
  NULL::BIGINT AS delete_staff_id,
  op.create_time,
  op.modify_time,
  NULL::TIMESTAMP AS delete_time,
  op.description AS memo,
  NULL::VARCHAR(255) AS customer_field2,
  NULL::VARCHAR(255) AS customer_field1,
  NULL::VARCHAR(64) AS uuid,
  NULL::DOUBLE PRECISION AS sort,
  op.sys_flag,
  op.grand_leader_id AS higher_leader_staff_id,
  op.direct_leader_id AS leader_staff_id,
  NULL::VARCHAR(255) AS ygxs,
  NULL::VARCHAR(255) AS hukouxingzhi,
  NULL::VARCHAR(255) AS hukoudi,
  NULL::VARCHAR(255) AS dangandi,
  NULL::VARCHAR(255) AS degree,
  NULL::VARCHAR(255) AS educational,
  NULL::VARCHAR(255) AS profession,
  NULL::TIMESTAMP AS biye_time,
  NULL::VARCHAR(255) AS school,
  NULL::VARCHAR(255) AS foreign_language,
  NULL::VARCHAR(255) AS compute_level,
  NULL::DOUBLE PRECISION AS height,
  NULL::VARCHAR(255) AS virtual_mobile,
  NULL::VARCHAR(255) AS politics_info,
  NULL::VARCHAR(255) AS nation,
  NULL::VARCHAR(255) AS marriage,
  NULL::VARCHAR(255) AS id_card,
  NULL::VARCHAR(255) AS native_place,
  NULL::TIMESTAMP AS birthday,
  op.avatar_url,
  NULL::VARCHAR(512) AS sign_pic_url
FROM public.org_person op
LEFT JOIN public.auth_user au
  ON op.id = au.person_id
 AND au.valid = 1;
