-- The workbench homepage reads stationLetter protocol config on load and
-- expects a JSON configValue object. The entity uses AESEncryptHandler, so
-- seed the default disabled config as the encrypted value generated by the
-- notification-admin service.
INSERT INTO public.notice_protocol_config (
  id,
  protocol,
  config_value,
  creator,
  create_time,
  create_staff_id,
  modifier,
  modify_time,
  modify_staff_id
)
VALUES (
  1001,
  'stationLetter',
  '88P8TB3btR5htEARafSfyNV7aksK3tfbQt4ONd/BNG6s4/xYtpCgP6J7jHLSNz5SkYUlCMu3enAUwHXwaUtVOKg+N5ei8cyOn53qOAyOmb9KgroQfw4aYdCqze8rloYHncAWzUhxeS7Vse10IjdORbZfwcs1shblVvA+NvJ72XxCgz0/XLMsx+KIxWcj3hw6IWMwBao27cUwuKJ6RCBCNdRrKJM5Z3YE+gzgVQlwc9SvLUEjqdnMuuXEZW45RaeItizKzSurBFs8ptgDU3KedxdSaZ2NHXQss9el/kxyXqr3dMt210gGJjx4w7+jIwUhQ2e6D5vyM5BFn38qpab8QL6CSkftacUJaps0wTj0ZivAaAOsvT0hnzarZQxoTBt3RBAU+5x2UVNdX0qQJfMojaM4TONuKlw3Jb0HZcPDMzaCSwCpisbsNkLZ2DCltKTVhAkf2SanmohLFH5Om1Ctkg==',
  'default',
  CURRENT_TIMESTAMP,
  1,
  'default',
  CURRENT_TIMESTAMP,
  1
)
ON CONFLICT (id) DO UPDATE
SET protocol = EXCLUDED.protocol,
    config_value = EXCLUDED.config_value,
    modifier = EXCLUDED.modifier,
    modify_time = CURRENT_TIMESTAMP,
    modify_staff_id = EXCLUDED.modify_staff_id;
