-- Seed sysbase department reference views required by business-module special permissions.
-- These rows mirror the vendor configuration-init/project-init metadata for:
--   sysbase_1.0_department_departmentRefCustom
--   sysbase_1.0_department_deptReftreeSeg
--   sysbase_1.0_department_deptref

WITH view_rows (
  code,
  show_type,
  custom_flag_int,
  custom_flag_bool,
  open_type,
  view_type,
  title,
  display_name,
  name
) AS (
  VALUES
    (
      'sysbase_1.0_department_departmentRefCustom',
      'SINGLE',
      1,
      true,
      'dialog',
      'REFERENCE',
      'foundation.ec.entity.department.reference',
      'foundation.ec.entity.department.reference',
      'departmentRefCustom'
    ),
    (
      'sysbase_1.0_department_deptReftreeSeg',
      'PART',
      0,
      false,
      'frame',
      'REFTREE',
      'foundation.ec.entity.department.reftree',
      'foundation.ec.entity.department.reftree',
      'deptReftreeSeg'
    ),
    (
      'sysbase_1.0_department_deptref',
      'SINGLE',
      1,
      true,
      'dialog',
      'REFERENCE',
      'foundation.ec.entity.department.reference',
      'foundation.ec.entity.department.reference',
      'departmentRef'
    )
)
INSERT INTO public.ec_view (
  code,
  ec_env,
  version,
  valid,
  edit_view_type,
  has_custom_section,
  import_flag,
  mobile_enable_flag,
  mobile,
  only_for_query,
  module_code,
  control_print,
  is_permission,
  is_audit,
  is_print,
  is_hand_sign,
  is_sign,
  is_shadow,
  is_reference,
  include_children,
  used_for_tree,
  deal_info_show,
  has_attachment,
  is_control,
  close_page_after_save,
  show_type,
  custom_flag,
  url,
  ass_model_code,
  entity_code,
  main_ref,
  main_view,
  used_for_work_flow,
  open_type,
  type,
  title,
  display_name,
  name
)
SELECT
  code,
  'product',
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  'sysbase_1.0',
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  show_type,
  custom_flag_int,
  '/organization/#/reference?type=department',
  'sysbase_1.0_department_base_department',
  'sysbase_1.0_department',
  0,
  0,
  0,
  open_type,
  view_type,
  title,
  display_name,
  name
FROM view_rows
ON CONFLICT (code) DO NOTHING;

WITH view_rows (
  code,
  show_type,
  custom_flag_int,
  custom_flag_bool,
  open_type,
  view_type,
  title,
  display_name,
  name
) AS (
  VALUES
    (
      'sysbase_1.0_department_departmentRefCustom',
      'SINGLE',
      1,
      true,
      'dialog',
      'REFERENCE',
      'foundation.ec.entity.department.reference',
      'foundation.ec.entity.department.reference',
      'departmentRefCustom'
    ),
    (
      'sysbase_1.0_department_deptReftreeSeg',
      'PART',
      0,
      false,
      'frame',
      'REFTREE',
      'foundation.ec.entity.department.reftree',
      'foundation.ec.entity.department.reftree',
      'deptReftreeSeg'
    ),
    (
      'sysbase_1.0_department_deptref',
      'SINGLE',
      1,
      true,
      'dialog',
      'REFERENCE',
      'foundation.ec.entity.department.reference',
      'foundation.ec.entity.department.reference',
      'departmentRef'
    )
)
INSERT INTO public.runtime_view (
  code,
  ec_env,
  version,
  valid,
  edit_view_type,
  has_custom_section,
  import_flag,
  mobile_enable_flag,
  mobile,
  only_for_query,
  module_code,
  control_print,
  is_permission,
  is_audit,
  is_print,
  is_hand_sign,
  is_sign,
  is_shadow,
  is_reference,
  include_children,
  used_for_tree,
  deal_info_show,
  has_attachment,
  is_control,
  close_page_after_save,
  show_type,
  custom_flag,
  url,
  ass_model_code,
  entity_code,
  main_ref,
  main_view,
  used_for_work_flow,
  open_type,
  type,
  title,
  display_name,
  name
)
SELECT
  code,
  'product',
  0,
  true,
  0,
  false,
  false,
  false,
  false,
  false,
  'sysbase_1.0',
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  show_type,
  custom_flag_bool,
  '/organization/#/reference?type=department',
  'sysbase_1.0_department_base_department',
  'sysbase_1.0_department',
  false,
  false,
  false,
  open_type,
  view_type,
  title,
  display_name,
  name
FROM view_rows
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.ec_extra_view (
  code,
  ec_env,
  version,
  view_json,
  config,
  view_code
) VALUES
  (
    'sysbase_1.0_department_deptReftreeSeg',
    'product',
    1,
    '{"components":[{"funcbody":null,"layoutCode":"layout_1571893952882_8914","funcname":null,"buttons":[],"rootName":"foundation.organization.default.company","type":"layoutTree","dragOpen":false,"canMemory":false,"hasAttachment":false,"layoutmethod":"container","treeModelCode":"name","canDrag":false,"funcbody_es5":null,"events":[]}],"layoutmethod":"column","type":"layout","title":"foundation.ec.entity.department.reftree"}',
    '<?xml version="1.0" encoding="UTF-8"?><config><layout><layoutCode><![CDATA[layout_1571893952882_8914]]></layoutCode><pageConfig><rootName><![CDATA[foundation.organization.default.company]]></rootName><jsonSource><![CDATA[]]></jsonSource><treeModelCode><![CDATA[name]]></treeModelCode><onclickMethod><![CDATA[]]></onclickMethod><ondbclickMethod><![CDATA[]]></ondbclickMethod><canDrag><![CDATA[false]]></canDrag><dragOpen><![CDATA[false]]></dragOpen><canMemory><![CDATA[false]]></canMemory><beforeDrag><![CDATA[]]></beforeDrag><afterDrop><![CDATA[]]></afterDrop></pageConfig><sections><list><list-item><sectionCode><![CDATA[section_1571893998979_6799]]></sectionCode><regionType><![CDATA[BUTTON]]></regionType><cells><list/></cells></list-item></list></sections></layout></config>',
    'sysbase_1.0_department_deptReftreeSeg'
  ),
  (
    'sysbase_1.0_department_deptref',
    'product',
    0,
    NULL,
    NULL,
    'sysbase_1.0_department_deptref'
  ),
  (
    'sysbase_1.0_department_departmentRefCustom',
    'product',
    0,
    NULL,
    NULL,
    'sysbase_1.0_department_departmentRefCustom'
  )
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.runtime_extra_view (
  code,
  ec_env,
  version,
  view_code
) VALUES
  ('sysbase_1.0_department_deptReftreeSeg', 'product', 1, 'sysbase_1.0_department_deptReftreeSeg'),
  ('sysbase_1.0_department_deptref', 'product', 0, 'sysbase_1.0_department_deptref'),
  ('sysbase_1.0_department_departmentRefCustom', 'product', 0, 'sysbase_1.0_department_departmentRefCustom')
ON CONFLICT (code) DO NOTHING;
