-- Seed additional QCS unqualified-treatment activity/batch states.
-- The base WOM/QCS compatibility seed only restores the hard-coded qualified
-- and unqualified states. These rows expose concrete deal_type values used by
-- QCSUnQlfDealServiceImpl -> WOMQCSServiceImpl.syncRejectReport.

insert into public.baseset_act_bat_sta (
    id,
    version,
    create_staff_id,
    create_time,
    modify_staff_id,
    modify_time,
    valid,
    cid,
    sort,
    create_department_id,
    create_position_id,
    group_id,
    owner_department_id,
    owner_position_id,
    owner_staff_id,
    position_lay_rec,
    status,
    table_no,
    code,
    name,
    is_conclusion,
    is_qcs_deal_way,
    suitable_range,
    active_end,
    batch_use,
    deal_type,
    pass_state,
    remark,
    effective_state
) values
    (
        11010,
        0,
        1,
        now(),
        1,
        now(),
        true,
        1000,
        30,
        1,
        1,
        1000,
        1,
        1,
        1,
        '1',
        99,
        'BASESET_ACT_BAT_STA_11010',
        'degradedRelease',
        'degradedRelease',
        true,
        true,
        'BaseSet_suitableRange/manulfactorture',
        'BaseSet_activeEnd/keep',
        'BaseSet_batchUse/manufacture',
        'BaseSet_dealType/degradedRelease',
        'BaseSet_passState/degreeRelease',
        null,
        99
    ),
    (
        11011,
        0,
        1,
        now(),
        1,
        now(),
        true,
        1000,
        40,
        1,
        1,
        1000,
        1,
        1,
        1,
        '1',
        99,
        'BASESET_ACT_BAT_STA_11011',
        'return',
        'return',
        true,
        true,
        'BaseSet_suitableRange/manulfactorture',
        'BaseSet_activeEnd/termination',
        'BaseSet_batchUse/manufacture',
        'BaseSet_dealType/return',
        'BaseSet_passState/forbidenRelease',
        null,
        99
    )
on conflict (id) do update set
    valid = excluded.valid,
    cid = excluded.cid,
    sort = excluded.sort,
    status = excluded.status,
    table_no = excluded.table_no,
    code = excluded.code,
    name = excluded.name,
    is_conclusion = excluded.is_conclusion,
    is_qcs_deal_way = excluded.is_qcs_deal_way,
    suitable_range = excluded.suitable_range,
    active_end = excluded.active_end,
    batch_use = excluded.batch_use,
    deal_type = excluded.deal_type,
    pass_state = excluded.pass_state,
    remark = excluded.remark,
    effective_state = excluded.effective_state,
    modify_staff_id = excluded.modify_staff_id,
    modify_time = now();
