-- PostgreSQL compatibility for the recovered WorkAppointment work-plan flow.
--
-- The recovered work-plan package persists WAPS_WORK_TICKET_PLANS, but the
-- custom after-submit hook also updates WAPS_WORK_ACTIONS.  Some current ADP
-- base packages do not ship the action table yet; an empty compatible table is
-- enough for plan-only flows, and the columns below match the module init.xml
-- surface so later action rows have a stable landing table.

CREATE TABLE IF NOT EXISTS public.waps_work_actions (
    id bigint PRIMARY KEY,
    version integer DEFAULT 0,
    create_staff_id bigint,
    create_time timestamp without time zone,
    modify_staff_id bigint,
    modify_time timestamp without time zone,
    delete_staff_id bigint,
    delete_time timestamp without time zone,
    valid boolean DEFAULT true,
    cid bigint,
    sort integer,
    create_department_id bigint,
    create_position_id bigint,
    deployment_id bigint,
    effect_staff_id bigint,
    effect_time timestamp without time zone,
    effective_state integer,
    group_id bigint,
    owner_department_id bigint,
    owner_position_id bigint,
    owner_staff_id bigint,
    position_lay_rec character varying,
    process_key character varying,
    process_version integer,
    status integer,
    table_no character varying,
    table_info_id bigint,
    extra_col text,
    action_no character varying,
    work_area bigint,
    work_content text,
    remark text,
    ticket_maker bigint,
    ticket_maker_end_time timestamp without time zone,
    ticket_maker_start_time timestamp without time zone,
    work_time_end timestamp without time zone,
    work_time_start timestamp without time zone,
    guardian_inside bigint,
    guardian_outside bigint,
    action_status character varying,
    risk_level character varying,
    supplement character varying,
    action_sort integer,
    work_plan bigint,
    person_in_charge bigint,
    work_tool text,
    apply_attribute character varying
);

ALTER TABLE public.waps_work_actions
    ADD COLUMN IF NOT EXISTS version integer DEFAULT 0,
    ADD COLUMN IF NOT EXISTS create_staff_id bigint,
    ADD COLUMN IF NOT EXISTS create_time timestamp without time zone,
    ADD COLUMN IF NOT EXISTS modify_staff_id bigint,
    ADD COLUMN IF NOT EXISTS modify_time timestamp without time zone,
    ADD COLUMN IF NOT EXISTS delete_staff_id bigint,
    ADD COLUMN IF NOT EXISTS delete_time timestamp without time zone,
    ADD COLUMN IF NOT EXISTS valid boolean DEFAULT true,
    ADD COLUMN IF NOT EXISTS cid bigint,
    ADD COLUMN IF NOT EXISTS sort integer,
    ADD COLUMN IF NOT EXISTS create_department_id bigint,
    ADD COLUMN IF NOT EXISTS create_position_id bigint,
    ADD COLUMN IF NOT EXISTS deployment_id bigint,
    ADD COLUMN IF NOT EXISTS effect_staff_id bigint,
    ADD COLUMN IF NOT EXISTS effect_time timestamp without time zone,
    ADD COLUMN IF NOT EXISTS effective_state integer,
    ADD COLUMN IF NOT EXISTS group_id bigint,
    ADD COLUMN IF NOT EXISTS owner_department_id bigint,
    ADD COLUMN IF NOT EXISTS owner_position_id bigint,
    ADD COLUMN IF NOT EXISTS owner_staff_id bigint,
    ADD COLUMN IF NOT EXISTS position_lay_rec character varying,
    ADD COLUMN IF NOT EXISTS process_key character varying,
    ADD COLUMN IF NOT EXISTS process_version integer,
    ADD COLUMN IF NOT EXISTS status integer,
    ADD COLUMN IF NOT EXISTS table_no character varying,
    ADD COLUMN IF NOT EXISTS table_info_id bigint,
    ADD COLUMN IF NOT EXISTS extra_col text,
    ADD COLUMN IF NOT EXISTS action_no character varying,
    ADD COLUMN IF NOT EXISTS work_area bigint,
    ADD COLUMN IF NOT EXISTS work_content text,
    ADD COLUMN IF NOT EXISTS remark text,
    ADD COLUMN IF NOT EXISTS ticket_maker bigint,
    ADD COLUMN IF NOT EXISTS ticket_maker_end_time timestamp without time zone,
    ADD COLUMN IF NOT EXISTS ticket_maker_start_time timestamp without time zone,
    ADD COLUMN IF NOT EXISTS work_time_end timestamp without time zone,
    ADD COLUMN IF NOT EXISTS work_time_start timestamp without time zone,
    ADD COLUMN IF NOT EXISTS guardian_inside bigint,
    ADD COLUMN IF NOT EXISTS guardian_outside bigint,
    ADD COLUMN IF NOT EXISTS action_status character varying,
    ADD COLUMN IF NOT EXISTS risk_level character varying,
    ADD COLUMN IF NOT EXISTS supplement character varying,
    ADD COLUMN IF NOT EXISTS action_sort integer,
    ADD COLUMN IF NOT EXISTS work_plan bigint,
    ADD COLUMN IF NOT EXISTS person_in_charge bigint,
    ADD COLUMN IF NOT EXISTS work_tool text,
    ADD COLUMN IF NOT EXISTS apply_attribute character varying;

CREATE INDEX IF NOT EXISTS idx_waps_work_actions_work_plan
    ON public.waps_work_actions (work_plan);

CREATE INDEX IF NOT EXISTS idx_waps_work_actions_valid_plan
    ON public.waps_work_actions (valid, work_plan);
