-- Generated by deploy/docker/scripts/generate-module-access-workflow-sql.py
-- section: access
-- source: PATROL_6.0.4.0 source intake commit bd2124d064f98e9212d955002a9a359ebe746130
-- module_code: PATROL_1.0.0
-- menu_app_code: EAM
-- bootstrap_admin_user_id: 1
-- bootstrap_company_id: 1000
-- menu_count: 24
-- normalized_operation_count: 102
-- Stable ID range owner: 7181000000000000..7181000000999999

BEGIN;

CREATE TEMP TABLE adp_module_menu_seed (
    id bigint PRIMARY KEY,
    code text NOT NULL,
    name text NOT NULL,
    parent_code text,
    lay_no integer NOT NULL,
    sort double precision,
    url text,
    namespace text,
    action_url text,
    target text,
    css_class text,
    module_code text NOT NULL,
    entity_code text,
    leaf boolean NOT NULL,
    valid boolean NOT NULL,
    is_hide boolean NOT NULL,
    absolute_hidden boolean NOT NULL,
    system_default boolean NOT NULL
) ON COMMIT DROP;

INSERT INTO adp_module_menu_seed VALUES
        (7181000000100001, 'PATROL', '巡检管理', NULL, 1, 105.0, NULL, NULL, NULL, NULL, 'icon_ydxj currenticon_ydxj', 'PATROL_1.0.0', NULL, false, true, false, false, true),
        (7181000000100002, 'PatrolBaseSet', '基础设置', 'PATROL', 2, 1.0, NULL, NULL, NULL, NULL, 'icon-folder', 'PATROL_1.0.0', NULL, false, true, false, false, true),
        (7181000000100003, 'patrolBusiness', '业务管理', 'PATROL', 2, 2.0, NULL, NULL, NULL, NULL, 'icon-folder', 'PATROL_1.0.0', NULL, false, true, false, false, true),
        (7181000000100004, 'patrolHomaPage', '巡检首页', 'base_portlets', 2, 2.0, NULL, NULL, NULL, NULL, NULL, 'PATROL_1.0.0', NULL, true, true, true, false, true),
        (7181000000100005, 'patrolMonit', '巡检监控', 'PATROL', 2, 4.0, NULL, NULL, NULL, NULL, 'icon-folder', 'PATROL_1.0.0', NULL, false, true, false, false, true),
        (7181000000100006, 'patrolReport', '统计分析', 'PATROL', 2, 3.0, NULL, NULL, NULL, NULL, 'icon-folder', 'PATROL_1.0.0', NULL, false, true, false, false, true),
        (7181000000100007, 'PATROL_1.0.0_inputStandard_inputStanList', '录入标准', 'PatrolBaseSet', 3, 2.0, '/msService/PATROL/inputStandard/inputStandard/inputStanList', '/msService/PATROL/inputStandard/inputStandard', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_inputStandard', true, true, false, false, true),
        (7181000000100008, 'PATROL_1.0.0_patrolMonit_patrolMonitMap', '巡检监控地图', 'patrolMonit', 3, 1.0, '/msService/PATROL/patrolMonit/patrolMonit/patrolMonitMap', '/msService/PATROL/patrolMonit/patrolMonit', 'patrolMonitMap', 'BLANK', 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolMonit', true, true, false, false, true),
        (7181000000100009, 'PATROL_1.0.0_patrolPlan_createTaskList', '生成任务', 'patrolBusiness', 3, 2.0, '/msService/PATROL/patrolPlan/createTask/createTaskList', '/msService/PATROL/patrolPlan/createTask', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolPlan', true, true, false, false, true),
        (7181000000100010, 'PATROL_1.0.0_patrolPlan_potrolPlanList', '巡检计划', 'patrolBusiness', 3, 1.0, '/msService/PATROL/patrolPlan/patrolPlan/potrolPlanList', '/msService/PATROL/patrolPlan/patrolPlan', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolPlan', true, true, false, false, true),
        (7181000000100011, 'PATROL_1.0.0_patrolRoute_workGroupList', '巡检路线设置', 'PatrolBaseSet', 3, 3.0, '/msService/PATROL/patrolRoute/workGroup/workGroupList', '/msService/PATROL/patrolRoute/workGroup', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolRoute', true, true, false, false, true),
        (7181000000100012, 'PATROL_1.0.0_patrolRoute_workRouteLayout', '巡检路线查看', 'PatrolBaseSet', 3, 4.0, '/msService/PATROL/patrolRoute/workItem/workRouteLayout', '/msService/PATROL/patrolRoute/workItem', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolRoute', true, true, false, false, true),
        (7181000000100013, 'PATROL_1.0.0_patrolTask_abnormalSummary', '异常巡检结果汇总', 'patrolReport', 3, 2.0, '/msService/PATROL/patrolTask/taskDetail/abnormalSummary', '/msService/PATROL/patrolTask/taskDetail', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100014, 'PATROL_1.0.0_patrolTask_batchChangeList', '批量变更', 'patrolBusiness', 3, 5.0, '/msService/PATROL/patrolTask/potrolTask/batchChangeList', '/msService/PATROL/patrolTask/potrolTask', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100015, 'PATROL_1.0.0_patrolTask_enteringResultList', '巡检结果录入', 'patrolBusiness', 3, 6.0, '/msService/PATROL/patrolTask/potrolTask/enteringResultList', '/msService/PATROL/patrolTask/potrolTask', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100016, 'PATROL_1.0.0_patrolTask_errorAnalysisMenu', '采集数据误差分析', 'patrolReport', 3, 7.0, '/msService/PATROL/patrolTask/potrolTask/errorAnalysisMenu', '/PATROL/patrolTask/potrolTask', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100017, 'PATROL_1.0.0_patrolTask_potrolResultSummary', '巡检结果汇总', 'patrolReport', 3, 1.0, '/msService/PATROL/patrolTask/taskDetail/potrolResultSummary', '/msService/PATROL/patrolTask/taskDetail', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100018, 'PATROL_1.0.0_patrolTask_potrolTaskList', '巡检任务', 'patrolBusiness', 3, 3.0, '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100019, 'PATROL_1.0.0_patrolTask_stabilityRAMenu', '设备平稳率', 'patrolReport', 3, 6.0, '/msService/PATROL/patrolTask/potrolTask/stabilityRAMenu', '/PATROL/patrolTask/potrolTask', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100020, 'PATROL_1.0.0_patrolTask_taskFinishStatistics', '巡检任务完成情况', 'patrolReport', 3, 5.0, '/msService/PATROL/patrolTask/taskDetail/taskFinishStatistics', '/msService/PATROL/patrolTask/taskDetail', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100021, 'PATROL_1.0.0_patrolTask_taskOverviewList', '巡检任务概述', 'patrolReport', 3, 3.0, '/msService/PATROL/patrolTask/potrolTask/taskOverviewList', '/msService/PATROL/patrolTask/potrolTask', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100022, 'PATROL_1.0.0_patrolTask_tempTaskList', '临时任务', 'patrolBusiness', 3, 4.0, '/msService/PATROL/patrolTask/potrolTask/tempTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100023, 'PATROL_1.0.0_patrolTask_unusualSummary', '异常巡检情况概述', 'patrolReport', 3, 4.0, '/msService/PATROL/patrolTask/taskDetail/unusualSummary', '/PATROL/patrolTask/taskDetail', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_patrolTask', true, true, false, false, true),
        (7181000000100024, 'PATROL_1.0.0_publicItem_itemLayout', '公用项目', 'PatrolBaseSet', 3, 1.0, '/msService/PATROL/publicItem/publicItem/itemLayout', '/msService/PATROL/publicItem/publicItem', NULL, NULL, 'icon-set', 'PATROL_1.0.0', 'PATROL_1.0.0_publicItem', true, true, false, false, true);

DO $guard$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM adp_module_menu_seed seed
          JOIN public.rbac_menuinfo current_row ON current_row.id = seed.id
         WHERE current_row.code IS DISTINCT FROM seed.code
           AND NOT EXISTS (
               SELECT 1 FROM public.rbac_menuinfo logical_match
                WHERE logical_match.code = seed.code
           )
    ) THEN
        RAISE EXCEPTION 'PATROL menu deterministic ID range collides with existing data';
    END IF;
END $guard$;

DO $menus$
DECLARE
    target_lay_no integer;
BEGIN
    FOR target_lay_no IN
        SELECT generate_series(1, coalesce(max(lay_no), 1)) FROM adp_module_menu_seed
    LOOP
        INSERT INTO public.rbac_menuinfo (
            id, version, create_time, modify_time, creator, modifier,
            create_staff_id, modify_staff_id, valid, cid, security_class,
            absolute_hidden, three_role, show_type, request_type, hidden_type,
            menu_type, is_hide, group_only, entity_code, module_code,
            system_default, css_class, sort, action_url, namespace, url, target,
            memo, name, code, app, enable, lay_no, lay_rec, parent_id,
            full_path, full_path_name, source, edited, type, no_restrict,
            status, route
        )
        SELECT seed.id, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
               'codex_module_recovery', 'codex_module_recovery', 1, 1,
               seed.valid, 1000, 'SYSTEM/BAP', seed.absolute_hidden, false,
               0, 0, 0, 0, seed.is_hide, false, nullif(seed.entity_code, ''),
               seed.module_code, seed.system_default, nullif(seed.css_class, ''),
               seed.sort, nullif(seed.action_url, ''), nullif(seed.namespace, ''),
               nullif(seed.url, ''),
               CASE WHEN seed.target <> '' THEN seed.target
                    WHEN NOT seed.leaf AND seed.lay_no > 1 THEN 'SELF'
                    ELSE NULL END,
               NULL, seed.name, seed.code, 'EAM', true,
               seed.lay_no,
               CASE WHEN parent.id IS NULL OR parent.id = -1 THEN seed.id::text
                    ELSE concat_ws('-', parent.lay_rec, seed.id::text) END,
               coalesce(parent.id, -1),
               CASE WHEN parent.id IS NULL OR parent.id = -1 THEN seed.id::text
                    ELSE concat_ws('/', parent.full_path, seed.id::text) END,
               CASE WHEN parent.id IS NULL OR parent.id = -1 THEN seed.name
                    ELSE concat_ws('/', parent.full_path_name, seed.name) END,
               'ADP_RECOVERY', false, 0, false, 0, nullif(seed.url, '')
          FROM adp_module_menu_seed seed
          LEFT JOIN LATERAL (
              SELECT id, lay_rec, full_path, full_path_name
                FROM public.rbac_menuinfo
               WHERE code = seed.parent_code
                 AND coalesce(valid, true)
               ORDER BY id
               LIMIT 1
          ) parent ON seed.parent_code IS NOT NULL AND seed.parent_code <> ''
         WHERE seed.lay_no = target_lay_no
           AND NOT EXISTS (
               SELECT 1 FROM public.rbac_menuinfo current_row
                WHERE current_row.code = seed.code
           );
    END LOOP;
END $menus$;

UPDATE public.rbac_menuinfo current_row
   SET valid = seed.valid,
       enable = true,
       name = seed.name,
       module_code = seed.module_code,
       entity_code = nullif(seed.entity_code, ''),
       css_class = nullif(seed.css_class, ''),
       sort = seed.sort,
       action_url = nullif(seed.action_url, ''),
       namespace = nullif(seed.namespace, ''),
       url = nullif(seed.url, ''),
       route = nullif(seed.url, ''),
       is_hide = seed.is_hide,
       absolute_hidden = seed.absolute_hidden,
       system_default = seed.system_default,
       leaf = seed.leaf,
       app = 'EAM',
       modify_time = CURRENT_TIMESTAMP
 FROM adp_module_menu_seed seed
 WHERE current_row.code = seed.code;

DO $menu_paths$
DECLARE
    target_lay_no integer;
BEGIN
    FOR target_lay_no IN
        SELECT generate_series(1, coalesce(max(lay_no), 1)) FROM adp_module_menu_seed
    LOOP
        UPDATE public.rbac_menuinfo current_row
           SET lay_no = seed.lay_no,
               parent_id = coalesce(parent.id, -1),
               lay_rec = CASE
                   WHEN parent.id IS NULL OR parent.id = -1 THEN current_row.id::text
                   ELSE concat_ws('-', parent.lay_rec, current_row.id::text)
               END,
               full_path = CASE
                   WHEN parent.id IS NULL OR parent.id = -1 THEN current_row.id::text
                   ELSE concat_ws('/', parent.full_path, current_row.id::text)
               END,
               full_path_name = CASE
                   WHEN parent.id IS NULL OR parent.id = -1 THEN seed.name
                   ELSE concat_ws('/', parent.full_path_name, seed.name)
               END
          FROM adp_module_menu_seed seed
          LEFT JOIN LATERAL (
              SELECT id, lay_rec, full_path, full_path_name
                FROM public.rbac_menuinfo
               WHERE code = seed.parent_code
                 AND coalesce(valid, true)
               ORDER BY id
               LIMIT 1
          ) parent ON seed.parent_code IS NOT NULL AND seed.parent_code <> ''
         WHERE current_row.code = seed.code
           AND seed.lay_no = target_lay_no;
    END LOOP;
END $menu_paths$;

CREATE TEMP TABLE adp_module_operation_seed (
    id bigint PRIMARY KEY,
    menu_code text NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    url text,
    namespace text,
    action_url text,
    target text,
    memo text,
    sort double precision,
    icon_cls text,
    menuoperatetype text,
    deployment_id bigint,
    msg_assembled integer,
    flow_key text,
    flow_version text,
    flow_name text,
    power_flag boolean,
    ignore_permission boolean,
    is_hidden boolean,
    entity_code text,
    enable_grouprestrict boolean,
    enable_posrestrict boolean,
    enable_assignpos boolean,
    enable_assignstaff boolean,
    enable_norestrict boolean,
    enable_custompermission boolean,
    enable_datapermission boolean,
    is_orrelation boolean,
    is_query boolean,
    view_code text,
    valid integer
) ON COMMIT DROP;

INSERT INTO adp_module_operation_seed VALUES
        (7181000000200001, 'PATROL_1.0.0_inputStandard_inputStanList', 'PATROL_1.0.0_inputStandard_inputStanList_self', 'foundation.common.query', '/msService/PATROL/inputStandard/inputStandard/inputStanList', '/msService/PATROL/inputStandard/inputStandard', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_inputStandard', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_inputStandard_inputStanEdit', 1),
        (7181000000200002, 'PATROL_1.0.0_inputStandard_inputStanList', 'PATROL_1.0.0_inputStandard_inputStanList_self', 'foundation.common.query', '/msService/PATROL/inputStandard/inputStandard/inputStanList', '/msService/PATROL/inputStandard/inputStandard', 'inputStanList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_inputStandard', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_inputStandard_inputStanList', 1),
        (7181000000200003, 'PATROL_1.0.0_inputStandard_inputStanList', 'PATROL_1.0.0_inputStandard_inputStanList_self', 'foundation.common.query', '/msService/PATROL/inputStandard/inputStandard/inputStanList', '/msService/PATROL/inputStandard/inputStandard', 'inputStanList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, false, false, 'PATROL_1.0.0_inputStandard', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_inputStandard_inputStanList', 1),
        (7181000000200004, 'PATROL_1.0.0_inputStandard_inputStanList', 'inputStanList_add_add_PATROL_1.0.0_inputStandard_inputStanList', 'foundation.systemMaintenance.add', '/msService/PATROL/inputStandard/inputStandard/inputStanEdit', '/msService/PATROL/inputStandard/inputStandard', 'inputStanEdit', 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_inputStandard', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_inputStandard_inputStanList', 1),
        (7181000000200005, 'PATROL_1.0.0_inputStandard_inputStanList', 'inputStanList_delete_del_PATROL_1.0.0_inputStandard_inputStanList', '删除', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-del', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_inputStandard', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_inputStandard_inputStanList', 1),
        (7181000000200006, 'PATROL_1.0.0_inputStandard_inputStanList', 'inputStanList_import_import_PATROL_1.0.0_inputStandard_inputStanList', '导入', '/msService/PATROL/inputStandard/inputStandard/inputStanListImportExcel', NULL, 'import', 'SELF', NULL, 0.0, 'cui-btn-import', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_inputStandard', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_inputStandard_inputStanList', 1),
        (7181000000200007, 'PATROL_1.0.0_inputStandard_inputStanList', 'inputStanList_modify_modify_PATROL_1.0.0_inputStandard_inputStanList', 'ec.entity.wf.edit', '/msService/PATROL/inputStandard/inputStandard/inputStanEdit', '/msService/PATROL/inputStandard/inputStandard', 'inputStanEdit', 'SELF', NULL, 0.0, 'cui-btn-modify', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_inputStandard', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_inputStandard_inputStanList', 1),
        (7181000000200008, 'PATROL_1.0.0_inputStandard_inputStanList', 'inputStanList_run_add_PATROL_1.0.0_inputStandard_inputStanList', '启用', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_inputStandard', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_inputStandard_inputStanList', 1),
        (7181000000200009, 'PATROL_1.0.0_inputStandard_inputStanList', 'inputStanList_stop_add_PATROL_1.0.0_inputStandard_inputStanList', 'foundation.customProp.model.disable', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_inputStandard', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_inputStandard_inputStanList', 1),
        (7181000000200010, 'PATROL_1.0.0_patrolMonit_patrolMonitMap', 'PATROL_1.0.0_patrolMonit_patrolMonitMap_self', 'foundation.common.query', '/msService/PATROL/patrolMonit/patrolMonit/patrolMonitMap', '/PATROL/patrolMonit/patrolMonit', 'patrolMonitMap', NULL, NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolMonit', false, false, false, false, false, false, false, false, true, NULL, 1),
        (7181000000200011, 'PATROL_1.0.0_patrolMonit_patrolMonitMap', 'PATROL_1.0.0_patrolMonit_patrolMonitMap_self', 'foundation.common.query', '/msService/PATROL/patrolMonit/patrolMonit/patrolMonitMap', '/msService/PATROL/patrolMonit/patrolMonit', 'patrolMonitMap', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolMonit', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolMonit_patrolMonitMap', 1),
        (7181000000200012, 'PATROL_1.0.0_patrolPlan_createTaskList', 'PATROL_1.0.0_patrolPlan_createTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolPlan/createTask/createTaskList', '/msService/PATROL/patrolPlan/createTask', 'createTaskList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', false, false, false, false, false, false, false, false, true, 'PATROL_1.0.0_patrolPlan_createTaskList', 1),
        (7181000000200013, 'PATROL_1.0.0_patrolPlan_createTaskList', 'createTaskList_createTask_add_PATROL_1.0.0_patrolPlan_createTaskList', '生成任务', '/msService/PATROL/patrolPlan/createTask/createTaskEdit', '/msService/PATROL/patrolPlan/createTask', 'createTaskEdit', 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolPlan_createTaskList', 1),
        (7181000000200014, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'PATROL_1.0.0_patrolPlan_potrolPlanList_self', 'foundation.common.query', '/msService/PATROL/patrolPlan/patrolPlan/potrolPlanList', '/msService/PATROL/patrolPlan/patrolPlan', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolPlan_createTaskEdit', 1),
        (7181000000200015, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'PATROL_1.0.0_patrolPlan_potrolPlanList_self', 'foundation.common.query', '/msService/PATROL/patrolPlan/patrolPlan/potrolPlanList', '/msService/PATROL/patrolPlan/patrolPlan', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolPlan_exceptionPerodEdit', 1),
        (7181000000200016, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'PATROL_1.0.0_patrolPlan_potrolPlanList_self', 'foundation.common.query', '/msService/PATROL/patrolPlan/patrolPlan/potrolPlanList', '/msService/PATROL/patrolPlan/patrolPlan', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolPlan_patrolPlan', 1),
        (7181000000200017, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'PATROL_1.0.0_patrolPlan_potrolPlanList_self', 'foundation.common.query', '/msService/PATROL/patrolPlan/patrolPlan/potrolPlanList', '/msService/PATROL/patrolPlan/patrolPlan', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolPlan_patrolPlanView', 1),
        (7181000000200018, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'PATROL_1.0.0_patrolPlan_potrolPlanList_self', 'foundation.common.query', '/msService/PATROL/patrolPlan/patrolPlan/potrolPlanList', '/msService/PATROL/patrolPlan/patrolPlan', 'potrolPlanList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 1),
        (7181000000200019, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'PATROL_1.0.0_patrolPlan_potrolPlanList_self', 'foundation.common.query', '/msService/PATROL/patrolPlan/patrolPlan/potrolPlanList', '/msService/PATROL/patrolPlan/patrolPlan', 'potrolPlanList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, false, false, 'PATROL_1.0.0_patrolPlan', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 1),
        (7181000000200020, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'PATROL_1.0.0_patrolPlan_potrolPlanList_self', 'foundation.common.query', '/msService/PATROL/patrolPlan/patrolPlan/potrolPlanList', '/msService/PATROL/patrolPlan/patrolPlan', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolPlan_staffSearchView', 1),
        (7181000000200021, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'potrolPlanList_add_add_PATROL_1.0.0_patrolPlan_potrolPlanList', 'foundation.basic.extension.add', '/msService/PATROL/patrolPlan/patrolPlan/patrolPlan', '/msService/PATROL/patrolPlan/patrolPlan', 'patrolPlan', 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 1),
        (7181000000200022, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'potrolPlanList_delete_del_PATROL_1.0.0_patrolPlan_potrolPlanList', 'ec.entity.wf.del', '/msService/PATROL/patrolPlan/patrolplan/delete', '/msService/PATROL/patrolPlan/patrolplan', 'delete', 'SELF', NULL, 0.0, 'cui-btn-del', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 1),
        (7181000000200023, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'potrolPlanList_modify_modify_PATROL_1.0.0_patrolPlan_potrolPlanList', 'ec.entity.wf.edit', '/msService/PATROL/patrolPlan/patrolPlan/patrolPlan', '/msService/PATROL/patrolPlan/patrolPlan', 'patrolPlan', 'SELF', NULL, 0.0, 'cui-btn-modify', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 1),
        (7181000000200024, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'potrolPlanList_stopRun_add_PATROL_1.0.0_patrolPlan_potrolPlanList', '停用', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 1),
        (7181000000200025, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'potrolPlanList_updateRun_add_PATROL_1.0.0_patrolPlan_potrolPlanList', '启用', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolPlan', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolPlan_potrolPlanList', 1),
        (7181000000200026, 'PATROL_1.0.0_patrolRoute_workGroupList', 'PATROL_1.0.0_patrolRoute_WorkArea_dg1575465284449', '巡检路线', NULL, NULL, NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, true, true, true, true, false, false, false, true, NULL, 1),
        (7181000000200027, 'PATROL_1.0.0_patrolRoute_workGroupList', 'PATROL_1.0.0_patrolRoute_WorkArea_dg1575506226708', '巡检路线', NULL, NULL, NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workGroupList', 1),
        (7181000000200028, 'PATROL_1.0.0_patrolRoute_workGroupList', 'PATROL_1.0.0_patrolRoute_WorkGroup_dg1575465277647', '巡检路线', NULL, NULL, NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, true, true, true, true, false, false, false, true, NULL, 1),
        (7181000000200029, 'PATROL_1.0.0_patrolRoute_workGroupList', 'PATROL_1.0.0_patrolRoute_WorkGroup_dg1575506219664', '巡检路线', NULL, NULL, NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workGroupList', 1),
        (7181000000200030, 'PATROL_1.0.0_patrolRoute_workGroupList', 'PATROL_1.0.0_patrolRoute_WorkItem_dg1575507309041', '巡检路线', NULL, NULL, NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workGroupList', 1),
        (7181000000200031, 'PATROL_1.0.0_patrolRoute_workGroupList', 'PATROL_1.0.0_patrolRoute_workGroupList_self', 'foundation.common.query', '/msService/PATROL/patrolRoute/workGroup/workGroupList', '/msService/PATROL/patrolRoute/workGroup', 'workGroupList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, false, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workGroupList', 1),
        (7181000000200032, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_add_add_PATROL_1.0.0_patrolRoute_workGroupList', 'foundation.basic.extension.add', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200033, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_delete_add_PATROL_1.0.0_patrolRoute_workGroupList', 'ec.print.template.delete', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-del', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200034, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_delete_del_PATROL_1.0.0_patrolRoute_workGroupList', '删行', '/PATROL/patrolRoute/workgroup/delete', '/PATROL/patrolRoute/workgroup', 'delete', 'SELF', NULL, 0.0, 'cui-btn-del', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, true, false, false, false, false, 'PATROL_1.0.0_patrolRoute_workGroupList', 1),
        (7181000000200035, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_import_import_PATROL_1.0.0_patrolRoute_workGroupList', 'ec.print.template.import', '/PATROL/patrolRoute/workGroup/workGroupListImportExcel', NULL, 'import', 'SELF', NULL, 0.0, 'cui-btn-import', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolRoute_workGroupList', 1),
        (7181000000200036, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_modify_add_PATROL_1.0.0_patrolRoute_workGroupList', 'ec.scheduler.datasource.edit', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-modify', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200037, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_modify_modify_PATROL_1.0.0_patrolRoute_workGroupList', 'com.supcon.orcid.audit.update', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-modify', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200038, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_run_add_PATROL_1.0.0_patrolRoute_workGroupList', '启用', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200039, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_start_add_PATROL_1.0.0_patrolRoute_workGroupList', '启用', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolRoute_workGroupList', 1),
        (7181000000200040, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_stop_add_PATROL_1.0.0_patrolRoute_workGroupList', '停用', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolRoute_workGroupList', 1),
        (7181000000200041, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_workAreaSet_add_PATROL_1.0.0_patrolRoute_workGroupList', '巡检区域设置', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200042, 'PATROL_1.0.0_patrolRoute_workGroupList', 'workGroupList_workItemSet_add_PATROL_1.0.0_patrolRoute_workGroupList', '巡检项设置', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200043, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 'PATROL_1.0.0_patrolRoute_workRouteLayout_self', 'foundation.common.query', '/msService/PATROL/patrolRoute/workItem/workRouteLayout', '/msService/PATROL/patrolRoute/workItem', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_exeRuleEdit', 1),
        (7181000000200044, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 'PATROL_1.0.0_patrolRoute_workRouteLayout_self', 'foundation.common.query', '/msService/PATROL/patrolRoute/workItem/workRouteLayout', '/msService/PATROL/patrolRoute/workItem', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workAreaEdit', 1),
        (7181000000200045, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 'PATROL_1.0.0_patrolRoute_workRouteLayout_self', 'foundation.common.query', '/msService/PATROL/patrolRoute/workItem/workRouteLayout', '/msService/PATROL/patrolRoute/workItem', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workAreaPtEdit', 1),
        (7181000000200046, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 'PATROL_1.0.0_patrolRoute_workRouteLayout_self', 'foundation.common.query', '/msService/PATROL/patrolRoute/workItem/workRouteLayout', '/msService/PATROL/patrolRoute/workItem', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workGroupEdit', 1),
        (7181000000200047, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 'PATROL_1.0.0_patrolRoute_workRouteLayout_self', 'foundation.common.query', '/msService/PATROL/patrolRoute/workItem/workRouteLayout', '/msService/PATROL/patrolRoute/workItem', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workGroupView', 1),
        (7181000000200048, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 'PATROL_1.0.0_patrolRoute_workRouteLayout_self', 'foundation.common.query', '/msService/PATROL/patrolRoute/workItem/workRouteLayout', '/msService/PATROL/patrolRoute/workItem', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workItemPtEdit', 1),
        (7181000000200049, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 'PATROL_1.0.0_patrolRoute_workRouteLayout_self', 'foundation.common.query', '/msService/PATROL/patrolRoute/workItem/workRouteLayout', '/msService/PATROL/patrolRoute/workItem', 'workRouteLayout', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 1),
        (7181000000200050, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 'PATROL_1.0.0_patrolRoute_workRouteLayout_self', 'foundation.common.query', '/msService/PATROL/patrolRoute/workItem/workRouteLayout', '/msService/PATROL/patrolRoute/workItem', 'workRouteLayout', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, false, false, 'PATROL_1.0.0_patrolRoute', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolRoute_workRouteLayout', 1),
        (7181000000200051, 'PATROL_1.0.0_patrolTask_abnormalSummary', 'PATROL_1.0.0_patrolTask_abnormalSummary_self', 'foundation.common.query', '/msService/PATROL/patrolTask/taskDetail/abnormalSummary', '/msService/PATROL/patrolTask/taskDetail', 'abnormalSummary', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, 'PATROL_1.0.0_patrolTask_abnormalSummary', 1),
        (7181000000200052, 'PATROL_1.0.0_patrolTask_batchChangeList', 'PATROL_1.0.0_patrolTask_batchChangeList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/batchChangeList', '/msService/PATROL/patrolTask/potrolTask', 'batchChangeList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, 'PATROL_1.0.0_patrolTask_batchChangeList', 1),
        (7181000000200053, 'PATROL_1.0.0_patrolTask_batchChangeList', 'batchChangeList_assignStaff_add_PATROL_1.0.0_patrolTask_batchChangeList', '指派负责人', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolTask_batchChangeList', 1),
        (7181000000200054, 'PATROL_1.0.0_patrolTask_batchChangeList', 'batchChangeList_taskStateChange_add_PATROL_1.0.0_patrolTask_batchChangeList', '状态变更', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolTask_batchChangeList', 1),
        (7181000000200055, 'PATROL_1.0.0_patrolTask_enteringResultList', 'PATROL_1.0.0_patrolTask_enteringResultList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/enteringResultList', '/msService/PATROL/patrolTask/potrolTask', 'enteringResultList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, 'PATROL_1.0.0_patrolTask_enteringResultList', 1),
        (7181000000200056, 'PATROL_1.0.0_patrolTask_enteringResultList', 'enteringResultList_entr_modify_PATROL_1.0.0_patrolTask_enteringResultList', '录入结果', '/msService/PATROL/patrolTask/potrolTask/enteringResultEdit', '/msService/PATROL/patrolTask/potrolTask', 'enteringResultEdit', 'SELF', NULL, 0.0, 'cui-btn-modify', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolTask_enteringResultList', 1),
        (7181000000200057, 'PATROL_1.0.0_patrolTask_errorAnalysisMenu', 'PATROL_1.0.0_patrolTask_errorAnalysisMenu_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/errorAnalysisMenu', '/PATROL/patrolTask/potrolTask', 'errorAnalysisMenu', NULL, NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, NULL, 1),
        (7181000000200058, 'PATROL_1.0.0_patrolTask_errorAnalysisMenu', 'PATROL_1.0.0_patrolTask_errorAnalysisMenu_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/errorAnalysisMenu', '/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_errorAnalysisMenu', 1),
        (7181000000200059, 'PATROL_1.0.0_patrolTask_potrolResultSummary', 'PATROL_1.0.0_patrolTask_potrolResultSummary_self', 'foundation.common.query', '/msService/PATROL/patrolTask/taskDetail/potrolResultSummary', '/msService/PATROL/patrolTask/taskDetail', 'potrolResultSummary', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, 'PATROL_1.0.0_patrolTask_potrolResultSummary', 1),
        (7181000000200060, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_MPS_Patrol', '巡检管理', NULL, NULL, NULL, NULL, NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, NULL, false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200061, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_abnormalIndex', 1),
        (7181000000200062, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_enteringResultEdit', 1),
        (7181000000200063, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_errorAnalysis', 1),
        (7181000000200064, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_patrolStateEdit', 1),
        (7181000000200065, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_potrolTaskEdit', 1),
        (7181000000200066, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', 'potrolTaskList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_potrolTaskList', 1),
        (7181000000200067, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', 'potrolTaskList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_potrolTaskList', 1),
        (7181000000200068, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_potrolTaskView', 1),
        (7181000000200069, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_qrInfo', 1),
        (7181000000200070, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_stabilityRateAnalys', 1),
        (7181000000200071, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_staffChangeEdit', 1),
        (7181000000200072, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_taskComplete', 1),
        (7181000000200073, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_taskFaultDeal', 1),
        (7181000000200074, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_taskFinishIndex', 1),
        (7181000000200075, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_tempTaskEdit', 1),
        (7181000000200076, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/potrolTaskList', '/msService/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_tempTaskView', 1),
        (7181000000200077, 'PATROL_1.0.0_patrolTask_stabilityRAMenu', 'PATROL_1.0.0_patrolTask_stabilityRAMenu_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/stabilityRAMenu', '/PATROL/patrolTask/potrolTask', 'stabilityRAMenu', NULL, NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, NULL, 1),
        (7181000000200078, 'PATROL_1.0.0_patrolTask_stabilityRAMenu', 'PATROL_1.0.0_patrolTask_stabilityRAMenu_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/stabilityRAMenu', '/PATROL/patrolTask/potrolTask', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_stabilityRAMenu', 1),
        (7181000000200079, 'PATROL_1.0.0_patrolTask_taskFinishStatistics', 'PATROL_1.0.0_patrolTask_taskFinishStatistics_self', 'foundation.common.query', '/msService/PATROL/patrolTask/taskDetail/taskFinishStatistics', '/msService/PATROL/patrolTask/taskDetail', 'taskFinishStatistics', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, 'PATROL_1.0.0_patrolTask_taskFinishStatistics', 1),
        (7181000000200080, 'PATROL_1.0.0_patrolTask_taskOverviewList', 'PATROL_1.0.0_patrolTask_PatrolTaskArea_dg1586331214550', '巡检任务概况', NULL, NULL, NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_taskOverviewList', 1),
        (7181000000200081, 'PATROL_1.0.0_patrolTask_taskOverviewList', 'PATROL_1.0.0_patrolTask_PotrolTask_dg1586331011160', '巡检任务概况', NULL, NULL, NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_taskOverviewList', 1),
        (7181000000200082, 'PATROL_1.0.0_patrolTask_taskOverviewList', 'PATROL_1.0.0_patrolTask_taskOverviewList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/taskOverviewList', '/msService/PATROL/patrolTask/potrolTask', 'taskOverviewList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, 'PATROL_1.0.0_patrolTask_taskOverviewList', 1),
        (7181000000200083, 'PATROL_1.0.0_patrolTask_taskOverviewList', 'taskOverviewList_seeTrack_add_PATROL_1.0.0_patrolTask_taskOverviewList', '查看巡检轨迹', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_patrolTask_taskOverviewList', 1),
        (7181000000200084, 'PATROL_1.0.0_patrolTask_tempTaskList', 'PATROL_1.0.0_patrolTask_tempTaskList_self', 'foundation.common.query', '/msService/PATROL/patrolTask/potrolTask/tempTaskList', '/msService/PATROL/patrolTask/potrolTask', 'tempTaskList', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, 'PATROL_1.0.0_patrolTask_tempTaskList', 1),
        (7181000000200085, 'PATROL_1.0.0_patrolTask_unusualSummary', 'PATROL_1.0.0_patrolTask_unusualSummary_self', 'foundation.common.query', '/msService/PATROL/patrolTask/taskDetail/unusualSummary', '/PATROL/patrolTask/taskDetail', 'unusualSummary', NULL, NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', false, false, false, false, false, false, false, false, true, NULL, 1),
        (7181000000200086, 'PATROL_1.0.0_patrolTask_unusualSummary', 'PATROL_1.0.0_patrolTask_unusualSummary_self', 'foundation.common.query', '/msService/PATROL/patrolTask/taskDetail/unusualSummary', '/PATROL/patrolTask/taskDetail', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_patrolTask', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_patrolTask_unusualSummary', 1),
        (7181000000200087, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_itemList_add_add_PATROL_1.0.0_publicItem_itemList', 'foundation.basic.extension.add', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200088, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_itemList_delete_del_PATROL_1.0.0_publicItem_itemList', 'common.operation.delete', '/msService/PATROL/publicItem/publicitem/delete', '/msService/PATROL/publicItem/publicitem', 'delete', 'SELF', NULL, 0.0, 'cui-btn-del', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200089, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_itemList_modify_modify_PATROL_1.0.0_publicItem_itemList', 'ec.entity.wf.edit', '/msService/PATROL/publicItem/publicItem/itemEdit', '/msService/PATROL/publicItem/publicItem', 'itemEdit', 'SELF', NULL, 0.0, 'cui-btn-modify', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200090, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_itemList_run_add_PATROL_1.0.0_publicItem_itemList', '启用', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200091, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_itemList_stop_add_PATROL_1.0.0_publicItem_itemList', 'foundation.basic.extension.unused', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200092, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_itemTree_add_add_PATROL_1.0.0_publicItem_itemTree', 'foundation.basic.extension.add', NULL, NULL, NULL, 'SELF', NULL, 0.0, 'cui-btn-add', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200093, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_itemTree_delete_del_PATROL_1.0.0_publicItem_itemTree', 'common.operation.delete', '/msService/PATROL/publicItem/publicitemtree/delete', '/msService/PATROL/publicItem/publicitemtree', 'delete', 'SELF', NULL, 0.0, 'cui-btn-del', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200094, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_itemTree_modify_modify_PATROL_1.0.0_publicItem_itemTree', 'ec.entity.wf.edit', '/msService/PATROL/publicItem/publicItemTree/itemTreeEdit', '/msService/PATROL/publicItem/publicItemTree', 'itemTreeEdit', 'SELF', NULL, 0.0, 'cui-btn-modify', NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', false, false, false, false, false, false, false, false, false, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200095, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_self', 'foundation.common.query', '/msService/PATROL/publicItem/publicItem/itemLayout', '/msService/PATROL/publicItem/publicItem', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_publicItem_itemEdit', 1),
        (7181000000200096, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_self', 'foundation.common.query', '/msService/PATROL/publicItem/publicItem/itemLayout', '/msService/PATROL/publicItem/publicItem', 'itemLayout', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200097, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_self', 'foundation.common.query', '/msService/PATROL/publicItem/publicItem/itemLayout', '/msService/PATROL/publicItem/publicItem', 'itemLayout', 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, false, false, 'PATROL_1.0.0_publicItem', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_publicItem_itemLayout', 1),
        (7181000000200098, 'PATROL_1.0.0_publicItem_itemLayout', 'PATROL_1.0.0_publicItem_itemLayout_self', 'foundation.common.query', '/msService/PATROL/publicItem/publicItem/itemLayout', '/msService/PATROL/publicItem/publicItem', NULL, 'SELF', NULL, 0.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, false, false, 'PATROL_1.0.0_publicItem', true, true, true, true, true, false, false, false, true, 'PATROL_1.0.0_publicItem_itemTreeEdit', 1),
        (7181000000200099, 'patrolHomaPage', 'PATROL_patrolInfo_portlet_view', '巡检信息', '/msService/PATROL/homePage/patrolInfo.html?__pc__=UEFUUk9MX3BhdHJvbEluZm9fcG9ydGxldF92aWV3fA__', '/msService/PATROL/homePage', 'patrolInfo.html?__pc__=UEFUUk9MX3BhdHJvbEluZm9fcG9ydGxldF92aWV3fA__', NULL, NULL, 0.0, NULL, 'NORMAL', NULL, NULL, NULL, NULL, NULL, false, false, false, NULL, false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200100, 'patrolHomaPage', 'PATROL_qr_portlet_view', 'app下载', '/msService/PATROL/homePage/qr.html?__pc__=UEFUUk9MX3FyX3BvcnRsZXRfdmlld3w_', '/msService/PATROL/homePage', 'qr.html?__pc__=UEFUUk9MX3FyX3BvcnRsZXRfdmlld3w_', NULL, NULL, 0.0, NULL, 'NORMAL', NULL, NULL, NULL, NULL, NULL, false, false, false, NULL, false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200101, 'patrolHomaPage', 'PATROL_taskComplete_portlet_view', '巡检任务完成情况', '/msService/PATROL/homePage/taskComplete.html?__pc__=UEFUUk9MX3Rhc2tDb21wbGV0ZV9wb3J0bGV0X3ZpZXd8', '/msService/PATROL/homePage', 'taskComplete.html?__pc__=UEFUUk9MX3Rhc2tDb21wbGV0ZV9wb3J0bGV0X3ZpZXd8', NULL, NULL, 0.0, NULL, 'NORMAL', NULL, NULL, NULL, NULL, NULL, false, false, false, NULL, false, false, false, false, true, false, false, false, false, NULL, 1),
        (7181000000200102, 'patrolHomaPage', 'PATROL_taskFaultDeal_portlet_view', '巡检隐患处理情况', '/msService/PATROL/homePage/taskFaultDeal.html?__pc__=UEFUUk9MX3Rhc2tGYXVsdERlYWxfcG9ydGxldF92aWV3fA__', '/msService/PATROL/homePage', 'taskFaultDeal.html?__pc__=UEFUUk9MX3Rhc2tGYXVsdERlYWxfcG9ydGxldF92aWV3fA__', NULL, NULL, 0.0, NULL, 'NORMAL', NULL, NULL, NULL, NULL, NULL, false, false, false, NULL, false, false, false, false, true, false, false, false, false, NULL, 1);

DO $guard$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM adp_module_operation_seed seed
          JOIN public.rbac_menuoperate current_row ON current_row.id = seed.id
         WHERE current_row.code IS DISTINCT FROM seed.code
           AND NOT EXISTS (
               SELECT 1
                 FROM public.rbac_menuoperate logical_match
                 JOIN public.rbac_menuinfo menu ON menu.id = logical_match.menuinfo_id
                WHERE menu.code = seed.menu_code
                  AND logical_match.code = seed.code
                  AND coalesce(logical_match.view_code, '') = coalesce(seed.view_code, '')
                  AND coalesce(logical_match.action_url, '') = coalesce(seed.action_url, '')
                  AND coalesce(logical_match.url, '') = coalesce(seed.url, '')
                  AND coalesce(logical_match.power_flag, false) = coalesce(seed.power_flag, false)
           )
    ) THEN
        RAISE EXCEPTION 'PATROL operation deterministic ID range collides with existing data';
    END IF;
END $guard$;

INSERT INTO public.rbac_menuoperate (
    id, row_version, version, create_time, modify_time, creator, modifier,
    create_staff_id, modify_staff_id, valid, cid, is_allow_proxy, is_hidden,
    three_role, view_code, is_query, is_orrelation, enable_datapermission,
    enable_custompermission, for_flow_permission, enable_norestrict,
    enable_dealerpermission, enable_assignstaff, enable_assignpos,
    enable_posrestrict, enable_deptrict, enable_assigndept,
    enable_grouprestrict, entity_code, ignore_permission, power_flag,
    flow_version, flow_key, msg_assembled, deployment_id, menuoperatetype,
    menuinfo_id, icon_cls, module_code, sort, memo, target, action_url,
    namespace, url, name, code, app, default_operate, edited
)
SELECT seed.id, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
       'codex_module_recovery', 'codex_module_recovery', 1, 1, seed.valid,
       1000, false, seed.is_hidden, false, nullif(seed.view_code, ''),
       seed.is_query, seed.is_orrelation, seed.enable_datapermission,
       seed.enable_custompermission, false, seed.enable_norestrict, false,
       seed.enable_assignstaff, seed.enable_assignpos, seed.enable_posrestrict,
       false, false, seed.enable_grouprestrict, nullif(seed.entity_code, ''),
       seed.ignore_permission, seed.power_flag, nullif(seed.flow_version, ''),
       nullif(seed.flow_key, ''), seed.msg_assembled, seed.deployment_id,
       nullif(seed.menuoperatetype, ''), menu.id, nullif(seed.icon_cls, ''),
       'PATROL_1.0.0', seed.sort, nullif(seed.memo, ''),
       nullif(seed.target, ''), nullif(seed.action_url, ''),
       nullif(seed.namespace, ''), nullif(seed.url, ''), seed.name, seed.code,
       'EAM', false, false
  FROM adp_module_operation_seed seed
  JOIN LATERAL (
      SELECT id FROM public.rbac_menuinfo
       WHERE code = seed.menu_code ORDER BY id LIMIT 1
  ) menu ON true
 WHERE NOT EXISTS (
     SELECT 1
       FROM public.rbac_menuoperate current_row
      WHERE current_row.menuinfo_id = menu.id
        AND current_row.code = seed.code
        AND coalesce(current_row.view_code, '') = coalesce(seed.view_code, '')
        AND coalesce(current_row.action_url, '') = coalesce(seed.action_url, '')
        AND coalesce(current_row.url, '') = coalesce(seed.url, '')
        AND coalesce(current_row.power_flag, false) = coalesce(seed.power_flag, false)
 );

WITH matched AS (
    SELECT DISTINCT ON (
               current_row.menuinfo_id, current_row.code,
               coalesce(current_row.view_code, ''),
               coalesce(current_row.action_url, ''),
               coalesce(current_row.url, ''),
               coalesce(current_row.power_flag, false)
           )
           current_row.id,
           seed.valid,
           seed.is_hidden,
           seed.is_query,
           seed.is_orrelation,
           seed.name,
           seed.ignore_permission,
           seed.enable_datapermission,
           seed.enable_custompermission,
           seed.enable_norestrict,
           seed.enable_assignstaff,
           seed.enable_assignpos,
           seed.enable_posrestrict,
           seed.enable_grouprestrict
      FROM adp_module_operation_seed seed
      JOIN public.rbac_menuinfo menu ON menu.code = seed.menu_code
      JOIN public.rbac_menuoperate current_row
        ON current_row.menuinfo_id = menu.id
       AND current_row.code = seed.code
       AND coalesce(current_row.view_code, '') = coalesce(seed.view_code, '')
       AND coalesce(current_row.action_url, '') = coalesce(seed.action_url, '')
       AND coalesce(current_row.url, '') = coalesce(seed.url, '')
       AND coalesce(current_row.power_flag, false) = coalesce(seed.power_flag, false)
     ORDER BY current_row.menuinfo_id, current_row.code,
              coalesce(current_row.view_code, ''),
              coalesce(current_row.action_url, ''),
              coalesce(current_row.url, ''),
              coalesce(current_row.power_flag, false), current_row.id
)
UPDATE public.rbac_menuoperate current_row
   SET valid = matched.valid,
       module_code = 'PATROL_1.0.0',
       app = 'EAM',
       is_hidden = matched.is_hidden,
       is_query = matched.is_query,
       is_orrelation = matched.is_orrelation,
       name = matched.name,
       ignore_permission = matched.ignore_permission,
       enable_datapermission = matched.enable_datapermission,
       enable_custompermission = matched.enable_custompermission,
       enable_norestrict = matched.enable_norestrict,
       enable_assignstaff = matched.enable_assignstaff,
       enable_assignpos = matched.enable_assignpos,
       enable_posrestrict = matched.enable_posrestrict,
       enable_grouprestrict = matched.enable_grouprestrict,
       modify_time = CURRENT_TIMESTAMP
  FROM matched
 WHERE current_row.id = matched.id;

WITH ranked AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY menuinfo_id, code, coalesce(view_code, ''),
                            coalesce(action_url, ''), coalesce(url, ''),
                            coalesce(power_flag, false)
               ORDER BY (
                   coalesce(enable_grouprestrict, false)::integer
                   + coalesce(enable_posrestrict, false)::integer
                   + coalesce(enable_assignpos, false)::integer
                   + coalesce(enable_assignstaff, false)::integer
                   + coalesce(enable_norestrict, false)::integer
                   + coalesce(enable_custompermission, false)::integer
                   + coalesce(enable_datapermission, false)::integer
               ) DESC,
               id
           ) AS duplicate_rank
      FROM public.rbac_menuoperate
     WHERE module_code = 'PATROL_1.0.0'
)
UPDATE public.rbac_menuoperate current_row
   SET valid = 0,
       modify_time = CURRENT_TIMESTAMP,
       modifier = 'codex_patrol_dedup'
  FROM ranked
 WHERE current_row.id = ranked.id
   AND ranked.duplicate_rank > 1;

WITH canonical_operations AS (
    SELECT DISTINCT ON (
               current_row.menuinfo_id, current_row.code,
               coalesce(current_row.view_code, ''),
               coalesce(current_row.action_url, ''),
               coalesce(current_row.url, ''),
               coalesce(current_row.power_flag, false)
           )
           current_row.id AS menuoperate_id,
           row_number() OVER (ORDER BY current_row.id) AS rn
      FROM public.rbac_menuoperate current_row
     WHERE current_row.module_code = 'PATROL_1.0.0'
       AND coalesce(current_row.valid, 0) = 1
     ORDER BY current_row.menuinfo_id, current_row.code,
              coalesce(current_row.view_code, ''),
              coalesce(current_row.action_url, ''),
              coalesce(current_row.url, ''),
              coalesce(current_row.power_flag, false), current_row.id
),
missing_permissions AS (
    SELECT canonical_operations.*
      FROM canonical_operations
     WHERE NOT EXISTS (
         SELECT 1 FROM public.rbac_rolepermission current_permission
          WHERE current_permission.role_id = 1
            AND current_permission.menuoperate_id = canonical_operations.menuoperate_id
     )
)
INSERT INTO public.rbac_rolepermission (
    id, cid, version, role_id, menuoperate_id, position_flag,
    department_flag, group_flag, assign_staff_flag, assign_pos_flag,
    assign_dept_flag, dealer_permission_flag, no_restrict_flag,
    assign_datapermission_flag, assign_custompermission_flag,
    create_time, modify_time, creator, modifier, create_staff_id,
    modify_staff_id
)
SELECT 7181000000300000 + missing_permissions.rn, 1000, 0, 1,
       missing_permissions.menuoperate_id, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'codex_module_recovery',
       'codex_module_recovery', 1, 1
  FROM missing_permissions
ON CONFLICT (role_id, menuoperate_id) WHERE role_id IS NOT NULL AND menuoperate_id IS NOT NULL
DO UPDATE SET no_restrict_flag = 1, modify_time = CURRENT_TIMESTAMP;

CREATE TEMP TABLE adp_module_user_permission_seed (
    id bigint PRIMARY KEY,
    menuoperate_id bigint NOT NULL,
    menuoperate_code text NOT NULL
) ON COMMIT DROP;

INSERT INTO adp_module_user_permission_seed
WITH canonical_operations AS (
    SELECT current_row.id AS menuoperate_id,
           current_row.code AS menuoperate_code,
           row_number() OVER (ORDER BY current_row.id) AS rn
      FROM public.rbac_menuoperate current_row
     WHERE current_row.module_code = 'PATROL_1.0.0'
       AND coalesce(current_row.valid, 0) = 1
)
SELECT 7181000000350000 + canonical_operations.rn,
       canonical_operations.menuoperate_id,
       canonical_operations.menuoperate_code
  FROM canonical_operations
 WHERE NOT EXISTS (
     SELECT 1
       FROM public.rbac_userpermission current_permission
      WHERE current_permission.user_id = 1
        AND current_permission.cid = 1000
        AND current_permission.menuoperate_id = canonical_operations.menuoperate_id
 );

DO $user_permission_guard$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM adp_module_user_permission_seed seed
          JOIN public.rbac_userpermission current_permission
            ON current_permission.id = seed.id
         WHERE current_permission.user_id IS DISTINCT FROM 1
            OR current_permission.cid IS DISTINCT FROM 1000
            OR current_permission.menuoperate_id IS DISTINCT FROM seed.menuoperate_id
    ) THEN
        RAISE EXCEPTION 'PATROL user-permission deterministic ID range collides with existing data';
    END IF;
END $user_permission_guard$;

INSERT INTO public.rbac_userpermission (
    id, version, user_id, deal_staff, cid, menuoperate_id, purview_type,
    position_flag, department_flag, group_flag, assign_staff_flag,
    assign_pos_flag, assign_dept_flag, dealer_permission_flag,
    no_restrict_flag, assign_datapermission_flag,
    assign_custompermission_flag, url_pattern, menuoperate_code,
    modify_time, create_time, modifier, creator, create_staff_id,
    modify_staff_id
)
SELECT seed.id, 0, 1, NULL, 1000,
       seed.menuoperate_id, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, NULL,
       seed.menuoperate_code, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
       'codex_module_recovery', 'codex_module_recovery',
       1, 1
  FROM adp_module_user_permission_seed seed;

UPDATE public.rbac_userpermission current_permission
   SET no_restrict_flag = 1,
       purview_type = 0,
       menuoperate_code = operation.code,
       modify_time = CURRENT_TIMESTAMP,
       modifier = 'codex_module_recovery'
  FROM public.rbac_menuoperate operation
 WHERE current_permission.user_id = 1
   AND current_permission.cid = 1000
   AND current_permission.menuoperate_id = operation.id
   AND operation.module_code = 'PATROL_1.0.0'
   AND coalesce(operation.valid, 0) = 1;

CREATE TEMP TABLE adp_module_company_menu_seed (
    id bigint PRIMARY KEY,
    menuinfo_id bigint NOT NULL
) ON COMMIT DROP;

INSERT INTO adp_module_company_menu_seed
SELECT 7181000000360000 + row_number() OVER (ORDER BY menu.id),
       menu.id
  FROM public.rbac_menuinfo menu
 WHERE menu.module_code = 'PATROL_1.0.0'
   AND coalesce(menu.valid, false)
   AND NOT EXISTS (
       SELECT 1
         FROM public.rbac_menuinfo_company_ref current_ref
        WHERE current_ref.menuinfo_id = menu.id
          AND current_ref.company_id IN (1000, -1)
   );

DO $company_menu_guard$
BEGIN
    IF EXISTS (
        SELECT 1
          FROM adp_module_company_menu_seed seed
          JOIN public.rbac_menuinfo_company_ref current_ref
            ON current_ref.id = seed.id
         WHERE current_ref.menuinfo_id IS DISTINCT FROM seed.menuinfo_id
            OR current_ref.company_id NOT IN (1000, -1)
    ) THEN
        RAISE EXCEPTION 'PATROL company-menu deterministic ID range collides with existing data';
    END IF;
END $company_menu_guard$;

INSERT INTO public.rbac_menuinfo_company_ref (
    id, menuinfo_id, company_id, valid, creator, modifier,
    create_time, modify_time, create_staff_id, modify_staff_id, appid
)
SELECT seed.id, seed.menuinfo_id, -1, false,
       'codex_module_recovery', 'codex_module_recovery',
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1,
       1, 'EAM'
  FROM adp_module_company_menu_seed seed;

UPDATE public.rbac_menuinfo_company_ref current_ref
   SET appid = 'EAM',
       modify_time = CURRENT_TIMESTAMP,
       modifier = 'codex_module_recovery'
  FROM public.rbac_menuinfo menu
 WHERE current_ref.menuinfo_id = menu.id
   AND current_ref.company_id IN (1000, -1)
   AND menu.module_code = 'PATROL_1.0.0';


INSERT INTO public.supos_app(code, valid, name, app_type, memory, modules, menus, create_time)
SELECT 'eamms', 1, '设备巡检管理', 0, 2700, '', '', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM public.supos_app WHERE code = 'eamms');

DO $app$
DECLARE
    current_modules text;
    current_menus text;
    item text;
BEGIN
    SELECT coalesce(modules, ''), coalesce(menus, '')
      INTO current_modules, current_menus
      FROM public.supos_app
     WHERE code = 'eamms'
     FOR UPDATE;

    FOREACH item IN ARRAY ARRAY['PATROL_1.0.0']::text[]
    LOOP
        IF NOT (item = ANY(string_to_array(current_modules, ','))) THEN
            current_modules := concat_ws(',', nullif(current_modules, ''), item);
        END IF;
    END LOOP;

    FOREACH item IN ARRAY ARRAY['PATROL_1.0.0_patrolMonit_patrolMonitMap', 'PATROL_1.0.0_patrolTask_errorAnalysisMenu', 'PATROL_1.0.0_patrolTask_stabilityRAMenu', 'PATROL_1.0.0_patrolTask_taskFinishStatistics', 'PATROL_1.0.0_patrolTask_unusualSummary', 'PATROL_1.0.0_patrolTask_taskOverviewList', 'PATROL_1.0.0_patrolTask_abnormalSummary', 'PATROL_1.0.0_patrolTask_potrolResultSummary', 'PATROL_1.0.0_patrolTask_enteringResultList', 'PATROL_1.0.0_patrolTask_batchChangeList', 'PATROL_1.0.0_patrolTask_tempTaskList', 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolPlan_createTaskList', 'PATROL_1.0.0_patrolPlan_potrolPlanList', 'PATROL_1.0.0_patrolRoute_workRouteLayout', 'PATROL_1.0.0_patrolRoute_workGroupList', 'PATROL_1.0.0_inputStandard_inputStanList', 'PATROL_1.0.0_publicItem_itemLayout']::text[]
    LOOP
        IF NOT (item = ANY(string_to_array(current_menus, ','))) THEN
            current_menus := concat_ws(',', nullif(current_menus, ''), item);
        END IF;
    END LOOP;

    UPDATE public.supos_app
       SET valid = 1,
           name = coalesce(nullif(name, ''), '设备巡检管理'),
           app_type = coalesce(app_type, 0),
           memory = coalesce(memory, 2700),
           modules = current_modules,
           menus = current_menus,
           modify_time = CURRENT_TIMESTAMP
     WHERE code = 'eamms';
END $app$;

CREATE INDEX IF NOT EXISTS idx_rbac_menuinfo_patrol_module_code
    ON public.rbac_menuinfo(module_code, code);
CREATE INDEX IF NOT EXISTS idx_rbac_menuoperate_patrol_module_code
    ON public.rbac_menuoperate(module_code, menuinfo_id);

COMMIT;
