-- Generated by deploy/docker/scripts/generate-module-access-workflow-sql.py
-- section: workflow
-- source: PATROL_6.0.4.0 source intake commit bd2124d064f98e9212d955002a9a359ebe746130
-- module_code: PATROL_1.0.0
-- workflow_count: 2
-- Stable ID range owner: 7181000000000000..7181000000999999

BEGIN;

CREATE TEMP TABLE adp_module_workflow_seed (
    id bigint PRIMARY KEY,
    jbpm_id bigint NOT NULL UNIQUE,
    process_key text NOT NULL UNIQUE,
    process_name text NOT NULL,
    name text NOT NULL,
    display_name text NOT NULL,
    description text,
    menu_code text NOT NULL,
    entity_code text NOT NULL,
    process_xml text NOT NULL,
    entry_url text,
    is_suspended integer NOT NULL,
    mobile_query integer NOT NULL,
    mobile_initiate integer NOT NULL,
    mobile_approve integer NOT NULL,
    allow_invalid integer NOT NULL,
    gradually_reject integer NOT NULL,
    recall_able integer NOT NULL,
    recall_remain_time bigint NOT NULL,
    main_view_code text
) ON COMMIT DROP;

INSERT INTO adp_module_workflow_seed VALUES
        (7181000000401000, 7181000000501000, 'potrolTaskWF', 'potrolTaskWF', '巡检任务', '巡检任务', NULL, 'PATROL_1.0.0_patrolTask_potrolTaskList', 'PATROL_1.0.0_patrolTask', '<?xml version="1.0" encoding="UTF-8"?> <process name="potrolTaskWF" systemVersion="" xmlns="http://jbpm.org/4.4/jpdl" lastModify="2021-06-23 10:45">
  <description text="巡检任务">
  </description>
  <start name="start_qdlm6iv" desc="开始活动" g="715,363,40,40" internationalKey="PATROL_1.0.0.workflow.randon1577320539832.flag" doURL="/msService/PATROL/patrolTask/potrolTask/potrolTaskEdit" viewName="巡检任务编辑" viewCode="PATROL_1.0.0_patrolTask_potrolTaskEdit" ignorePermission="false">
   <transition name="SequenceFlow_03mp4qu" desc="制定" to="TaskEvent_0zg7ttg" px="818,367" reject="0" internationalKey="ec.pending.start" encode="SequenceFlow_03mp4qu">
   </transition>
  </start>
  <end name="end_vtxcxms" desc="结束活动" g="1139,363,40,40" internationalKey="PATROL_1.0.0.workflow.randon1577321323483.flag" effectFlag="true">
  </end>
  <task name="TaskEvent_0zg7ttg" desc="编辑" g="860,363,40,40" internationalKey="ec.view.edit" dealSet="0" recallAble="true" showInSimpleDealInfo="true" mobileApprove="true" ignorePermission="false" isAllowProxy="true">
   <assignment-handler class="com.supcon.orchid.workflow.engine.handlers.assignment.GetUserListHandler">
    <field name="inputorFlag">
     <string value="true">
     </string>
    </field>
    <field name="leaderFlag">
     <string value="false">
     </string>
    </field>
    <field name="bigLeaderFlag">
     <string value="false">
     </string>
    </field>
    <field name="activityDealFlag">
     <string value="false">
     </string>
    </field>
    <field name="flowDealFlag">
     <string value="false">
     </string>
    </field>
    <field name="attentFlag">
     <string value="false">
     </string>
    </field>
    <field name="staffIds">
     <string value="">
     </string>
    </field>
   </assignment-handler>
   <open-action url="/msService/PATROL/patrolTask/potrolTask/potrolTaskEdit" name="巡检任务编辑" viewType="EDIT" viewCode="PATROL_1.0.0_patrolTask_potrolTaskEdit" target="_blank">
   </open-action>
   <transition name="SequenceFlow_1tb4vvh" desc="提交" to="TaskEvent_146dnjp" px="950,367" reject="0" internationalKey="ec.flow.submit" encode="SequenceFlow_1tb4vvh">
   </transition>
   <transition name="SequenceFlow_16elo3z" desc="作废" to="EndCancelEvent_1rxzv5y" px="905,440" reject="0" internationalKey="ec.pending.invalid" encode="SequenceFlow_16elo3z" cancel="1">
   </transition>
  </task>
  <task name="TaskEvent_146dnjp" desc="审批" g="980,363,40,40" internationalKey="PATROL_1.0.0.workflow.randon1577320783173.flag" dealSet="0" recallAble="true" showInSimpleDealInfo="true" mobileApprove="true" ignorePermission="false" isAllowProxy="true">
   <assignment-handler class="com.supcon.orchid.workflow.engine.handlers.assignment.GetUserListHandler">
    <field name="inputorFlag">
     <string value="false">
     </string>
    </field>
    <field name="leaderFlag">
     <string value="false">
     </string>
    </field>
    <field name="bigLeaderFlag">
     <string value="false">
     </string>
    </field>
    <field name="activityDealFlag">
     <string value="false">
     </string>
    </field>
    <field name="flowDealFlag">
     <string value="false">
     </string>
    </field>
    <field name="attentFlag">
     <string value="false">
     </string>
    </field>
    <field name="staffIds">
     <string value="">
     </string>
    </field>
   </assignment-handler>
   <open-action url="/msService/PATROL/patrolTask/potrolTask/potrolTaskView" name="巡检任务查看" viewType="VIEW" viewCode="PATROL_1.0.0_patrolTask_potrolTaskView" target="_blank">
   </open-action>
   <transition name="SequenceFlow_0dcu4lg" desc="生效" to="end_vtxcxms" px="1090,367" reject="0" internationalKey="ec.pending.over" encode="SequenceFlow_0dcu4lg">
   </transition>
   <transition name="SequenceFlow_1hlrxzk" desc="驳回" to="TaskEvent_0zg7ttg" px="950.5,308" reject="1" internationalKey="ec.flow.reject" encode="SequenceFlow_1hlrxzk" g="1020,324,900,324">
   </transition>
  </task>
  <end-cancel name="EndCancelEvent_1rxzv5y" desc="作废" g="860,479,40,40" internationalKey="PATROL_1.0.0.workflow.randon1577321323495.flag">
  </end-cancel>
 </process>', '/msService/PATROL/patrolTask/potrolTask/potrolTaskEdit', 0, 0, 0, 1, 1, 0, 1, 3600, NULL),
        (7181000000402000, 7181000000502000, 'tempTaskWF', 'tempTaskWF', '临时巡检任务', '临时巡检任务', NULL, 'PATROL_1.0.0_patrolTask_tempTaskList', 'PATROL_1.0.0_patrolTask', '<?xml version="1.0" encoding="UTF-8"?> <process name="tempTaskWF" systemVersion="" xmlns="http://jbpm.org/4.4/jpdl" lastModify="2021-06-23 10:45">
  <description text="临时巡检任务">
  </description>
  <start name="start_ml5tgr8" desc="开始活动" g="715,363,40,40" internationalKey="PATROL_1.0.0.workflow.randon1578211252951.flag" doURL="/msService/PATROL/patrolTask/potrolTask/tempTaskEdit" viewName="临时巡检任务编辑" viewCode="PATROL_1.0.0_patrolTask_tempTaskEdit" ignorePermission="false">
   <transition name="SequenceFlow_0f1weqk" desc="制定" to="TaskEvent_11icizp" px="811,367" reject="0" internationalKey="ec.pending.start" encode="SequenceFlow_0f1weqk">
   </transition>
  </start>
  <end name="end_5btwq85" desc="结束活动" g="1139,363,40,40" internationalKey="PATROL_1.0.0.workflow.randon1578211530581.flag" effectFlag="true">
  </end>
  <task name="TaskEvent_11icizp" desc="编辑" g="846,363,40,40" internationalKey="ec.dataClassific.condition.edit" dealSet="0" recallAble="true" showInSimpleDealInfo="true" mobileApprove="true" ignorePermission="false" isAllowProxy="true">
   <assignment-handler class="com.supcon.orchid.workflow.engine.handlers.assignment.GetUserListHandler">
    <field name="inputorFlag">
     <string value="true">
     </string>
    </field>
    <field name="leaderFlag">
     <string value="false">
     </string>
    </field>
    <field name="bigLeaderFlag">
     <string value="false">
     </string>
    </field>
    <field name="activityDealFlag">
     <string value="false">
     </string>
    </field>
    <field name="flowDealFlag">
     <string value="false">
     </string>
    </field>
    <field name="attentFlag">
     <string value="false">
     </string>
    </field>
    <field name="staffIds">
     <string value="">
     </string>
    </field>
   </assignment-handler>
   <open-action url="/msService/PATROL/patrolTask/potrolTask/tempTaskEdit" name="临时巡检任务编辑" viewType="EDIT" viewCode="PATROL_1.0.0_patrolTask_tempTaskEdit" target="_blank">
   </open-action>
   <transition name="SequenceFlow_089pa68" desc="提交" to="TaskEvent_1ny8a19" px="944,367" reject="0" internationalKey="ec.flow.submit" encode="SequenceFlow_089pa68">
   </transition>
   <transition name="SequenceFlow_0xd4ki3" desc="作废" to="EndCancelEvent_1uypeg3" px="891,439" reject="0" internationalKey="EditView.operate.button.cancel" encode="SequenceFlow_0xd4ki3" cancel="1">
   </transition>
  </task>
  <task name="TaskEvent_1ny8a19" desc="审批" g="981,363,40,40" internationalKey="PATROL_1.0.0.workflow.randon1577320783173.flag" dealSet="0" recallAble="true" showInSimpleDealInfo="true" mobileApprove="true" ignorePermission="false" isAllowProxy="true">
   <assignment-handler class="com.supcon.orchid.workflow.engine.handlers.assignment.GetUserListHandler">
    <field name="inputorFlag">
     <string value="false">
     </string>
    </field>
    <field name="leaderFlag">
     <string value="false">
     </string>
    </field>
    <field name="bigLeaderFlag">
     <string value="false">
     </string>
    </field>
    <field name="activityDealFlag">
     <string value="false">
     </string>
    </field>
    <field name="flowDealFlag">
     <string value="false">
     </string>
    </field>
    <field name="attentFlag">
     <string value="false">
     </string>
    </field>
    <field name="staffIds">
     <string value="">
     </string>
    </field>
   </assignment-handler>
   <open-action url="/msService/PATROL/patrolTask/potrolTask/tempTaskView" name="临时巡检任务查看" viewType="VIEW" viewCode="PATROL_1.0.0_patrolTask_tempTaskView" target="_blank">
   </open-action>
   <transition name="SequenceFlow_1x8x0j6" desc="生效" to="end_5btwq85" px="1090,367" reject="0" internationalKey="ec.pending.over" encode="SequenceFlow_1x8x0j6">
   </transition>
   <transition name="SequenceFlow_025v7o4" desc="驳回" to="TaskEvent_11icizp" px="943.5,308" reject="1" internationalKey="EditView.operate.button.reject" encode="SequenceFlow_025v7o4" g="1021,324,886,324">
   </transition>
  </task>
  <end-cancel name="EndCancelEvent_1uypeg3" desc="作废" g="846,476,40,40" internationalKey="PATROL_1.0.0.workflow.randon1578211530592.flag">
  </end-cancel>
 </process>', '/msService/PATROL/patrolTask/potrolTask/tempTaskEdit', 0, 0, 0, 1, 1, 0, 1, 3600, NULL);

DO $deployments$
DECLARE
    seed adp_module_workflow_seed%ROWTYPE;
    current_id bigint;
    process_oid oid;
    temp_process_oid oid;
BEGIN
    FOR seed IN SELECT * FROM adp_module_workflow_seed ORDER BY process_key
    LOOP
        SELECT id INTO current_id
          FROM public.wf_deployment
         WHERE process_key = seed.process_key
         ORDER BY coalesce(is_current_version, 0) DESC,
                  coalesce(process_version, 0) DESC, id DESC
         LIMIT 1;

        IF NOT EXISTS (
            SELECT 1 FROM public.rbac_menuinfo WHERE code = seed.menu_code
        ) THEN
            RAISE EXCEPTION 'PATROL workflow % cannot resolve menu %', seed.process_key, seed.menu_code;
        END IF;

        IF current_id IS NULL THEN
            IF EXISTS (SELECT 1 FROM public.wf_deployment WHERE id = seed.id) THEN
                RAISE EXCEPTION 'PATROL workflow deterministic ID % collides with existing data', seed.id;
            END IF;
            process_oid := lo_from_bytea(0, convert_to(seed.process_xml, 'UTF8'));
            temp_process_oid := lo_from_bytea(0, convert_to(seed.process_xml, 'UTF8'));
            INSERT INTO public.wf_deployment (
                id, process_key, process_version, name, name_zh_cn, valid,
                is_current_version, version, create_time, modify_time,
                create_staff_id, modify_staff_id, signature_enable,
                publish_time, main_view_view_code, recall_remain_time,
                recall_able, gradually_reject, allow_invalid, mobileapprove,
                mobileinitiate, mobilequery, flow_edit_flag, temp_process_xml,
                entry_url, process_xml, publish_flag, entity_code, menu_code,
                menu_info_id, process_definition_id, is_suspended,
                deployment_id, process_name, description, cid,
                cross_company_flag, process_xml_text_backup,
                temp_process_xml_text_backup
            )
            SELECT seed.id, seed.process_key, 1, seed.name, seed.display_name,
                   1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, 0,
                   CURRENT_TIMESTAMP, nullif(seed.main_view_code, ''),
                   seed.recall_remain_time, seed.recall_able,
                   seed.gradually_reject, seed.allow_invalid,
                   seed.mobile_approve, seed.mobile_initiate,
                   seed.mobile_query, 0, temp_process_oid,
                   nullif(seed.entry_url, ''), process_oid, 1,
                   seed.entity_code, seed.menu_code, menu.id,
                   seed.process_key || '-1', seed.is_suspended,
                   seed.jbpm_id::text, seed.process_name,
                   nullif(seed.description, ''), 1000, 0,
                   seed.process_xml, seed.process_xml
              FROM public.rbac_menuinfo menu
             WHERE menu.code = seed.menu_code
             ORDER BY menu.id
             LIMIT 1;
            current_id := seed.id;
        ELSE
            UPDATE public.wf_deployment current_row
               SET valid = 1,
                   is_current_version = CASE WHEN current_row.id = current_id THEN 1 ELSE 0 END,
                   process_version = CASE WHEN current_row.id = current_id THEN 1 ELSE current_row.process_version END,
                   name = seed.name,
                   name_zh_cn = seed.display_name,
                   publish_flag = CASE WHEN current_row.id = current_id THEN 1 ELSE current_row.publish_flag END,
                   menu_code = seed.menu_code,
                   menu_info_id = (SELECT id FROM public.rbac_menuinfo WHERE code = seed.menu_code ORDER BY id LIMIT 1),
                   entity_code = seed.entity_code,
                   process_definition_id = CASE WHEN current_row.id = current_id THEN seed.process_key || '-1' ELSE current_row.process_definition_id END,
                   deployment_id = CASE WHEN current_row.id = current_id THEN seed.jbpm_id::text ELSE current_row.deployment_id END,
                   process_xml_text_backup = CASE WHEN current_row.id = current_id THEN seed.process_xml ELSE current_row.process_xml_text_backup END,
                   temp_process_xml_text_backup = CASE WHEN current_row.id = current_id THEN seed.process_xml ELSE current_row.temp_process_xml_text_backup END,
                   modify_time = CURRENT_TIMESTAMP
             WHERE current_row.process_key = seed.process_key;

            UPDATE public.wf_deployment
               SET process_xml = lo_from_bytea(0, convert_to(seed.process_xml, 'UTF8'))
             WHERE id = current_id AND process_xml IS NULL;
            UPDATE public.wf_deployment
               SET temp_process_xml = lo_from_bytea(0, convert_to(seed.process_xml, 'UTF8'))
             WHERE id = current_id AND temp_process_xml IS NULL;
        END IF;
    END LOOP;
END $deployments$;

CREATE TEMP TABLE adp_module_task_seed (
    process_key text NOT NULL,
    offset_id bigint NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    display_name text NOT NULL,
    task_type integer NOT NULL,
    view_code text,
    open_mode text,
    ignore_permission integer,
    deal_set integer,
    is_allow_proxy integer,
    show_in_simple_dealinfo integer,
    mobile_approve integer,
    recall_able integer
) ON COMMIT DROP;

INSERT INTO adp_module_task_seed VALUES
        ('potrolTaskWF', 101, 'start_qdlm6iv', '开始活动', '开始活动', 1, 'PATROL_1.0.0_patrolTask_potrolTaskEdit', NULL, 0, 0, 0, 0, 0, 0),
        ('potrolTaskWF', 102, 'end_vtxcxms', '结束活动', '结束活动', 2, NULL, NULL, 0, 0, 0, 0, 0, 0),
        ('potrolTaskWF', 103, 'TaskEvent_0zg7ttg', 'ec.view.edit', '编辑', 4, 'PATROL_1.0.0_patrolTask_potrolTaskEdit', '_blank', 0, 0, 1, 1, 1, 1),
        ('potrolTaskWF', 104, 'TaskEvent_146dnjp', '审批', '审批', 4, 'PATROL_1.0.0_patrolTask_potrolTaskView', '_blank', 0, 0, 1, 1, 1, 1),
        ('potrolTaskWF', 105, 'EndCancelEvent_1rxzv5y', '作废', '作废', 3, NULL, NULL, 0, 0, 0, 0, 0, 0),
        ('tempTaskWF', 101, 'start_ml5tgr8', '开始活动', '开始活动', 1, 'PATROL_1.0.0_patrolTask_tempTaskEdit', NULL, 0, 0, 0, 0, 0, 0),
        ('tempTaskWF', 102, 'end_5btwq85', '结束活动', '结束活动', 2, NULL, NULL, 0, 0, 0, 0, 0, 0),
        ('tempTaskWF', 103, 'TaskEvent_11icizp', 'ec.dataClassific.condition.edit', '编辑', 4, 'PATROL_1.0.0_patrolTask_tempTaskEdit', '_blank', 0, 0, 1, 1, 1, 1),
        ('tempTaskWF', 104, 'TaskEvent_1ny8a19', '审批', '审批', 4, 'PATROL_1.0.0_patrolTask_tempTaskView', '_blank', 0, 0, 1, 1, 1, 1),
        ('tempTaskWF', 105, 'EndCancelEvent_1uypeg3', '作废', '作废', 3, NULL, NULL, 0, 0, 0, 0, 0, 0);

INSERT INTO public.wf_task (
    id, version, create_time, modify_time, create_staff_id, modify_staff_id,
    valid, ignore_permission, web_signet_flag, deal_set, is_allow_proxy,
    show_in_simple_dealinfo, mobile_approve, recall_able, process_version,
    process_key, open_mode, view_code, type, deployment_id, code,
    name_zh_cn, name, cid
)
SELECT deployment.id + seed.offset_id, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
       1, 1, 1, seed.ignore_permission, 0, seed.deal_set,
       seed.is_allow_proxy, seed.show_in_simple_dealinfo,
       seed.mobile_approve, seed.recall_able, 1, seed.process_key,
       nullif(seed.open_mode, ''), nullif(seed.view_code, ''), seed.task_type,
       deployment.id, seed.code, seed.display_name, seed.name, 1000
  FROM adp_module_task_seed seed
  JOIN public.wf_deployment deployment
    ON deployment.process_key = seed.process_key
   AND coalesce(deployment.is_current_version, 0) = 1
 WHERE NOT EXISTS (
     SELECT 1 FROM public.wf_task current_row
      WHERE current_row.deployment_id = deployment.id
        AND current_row.code = seed.code
 );

CREATE TEMP TABLE adp_module_transition_seed (
    process_key text NOT NULL,
    offset_id bigint NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    display_name text NOT NULL,
    from_node_code text NOT NULL,
    to_node_code text NOT NULL,
    transition_type integer NOT NULL
) ON COMMIT DROP;

INSERT INTO adp_module_transition_seed VALUES
        ('potrolTaskWF', 201, 'SequenceFlow_03mp4qu', 'ec.pending.start', '制定', 'start_qdlm6iv', 'TaskEvent_0zg7ttg', 1),
        ('potrolTaskWF', 202, 'SequenceFlow_1tb4vvh', 'ec.flow.submit', '提交', 'TaskEvent_0zg7ttg', 'TaskEvent_146dnjp', 1),
        ('potrolTaskWF', 203, 'SequenceFlow_16elo3z', 'ec.pending.invalid', '作废', 'TaskEvent_0zg7ttg', 'EndCancelEvent_1rxzv5y', 3),
        ('potrolTaskWF', 204, 'SequenceFlow_0dcu4lg', 'ec.pending.over', '生效', 'TaskEvent_146dnjp', 'end_vtxcxms', 1),
        ('potrolTaskWF', 205, 'SequenceFlow_1hlrxzk', 'ec.flow.reject', '驳回', 'TaskEvent_146dnjp', 'TaskEvent_0zg7ttg', 2),
        ('tempTaskWF', 201, 'SequenceFlow_0f1weqk', 'ec.pending.start', '制定', 'start_ml5tgr8', 'TaskEvent_11icizp', 1),
        ('tempTaskWF', 202, 'SequenceFlow_089pa68', 'ec.flow.submit', '提交', 'TaskEvent_11icizp', 'TaskEvent_1ny8a19', 1),
        ('tempTaskWF', 203, 'SequenceFlow_0xd4ki3', 'EditView.operate.button.cancel', '作废', 'TaskEvent_11icizp', 'EndCancelEvent_1uypeg3', 3),
        ('tempTaskWF', 204, 'SequenceFlow_1x8x0j6', 'ec.pending.over', '生效', 'TaskEvent_1ny8a19', 'end_5btwq85', 1),
        ('tempTaskWF', 205, 'SequenceFlow_025v7o4', 'EditView.operate.button.reject', '驳回', 'TaskEvent_1ny8a19', 'TaskEvent_11icizp', 2);

INSERT INTO public.wf_transition (
    id, version, create_time, modify_time, create_staff_id, modify_staff_id,
    valid, default_staff, required_staff, select_staff, deployment_id,
    to_node_code, from_node_code, type, code, name_zh_cn, name
)
SELECT deployment.id + seed.offset_id, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
       1, 1, 1, 0, 0, '0', deployment.id, seed.to_node_code,
       seed.from_node_code, seed.transition_type, seed.code,
       seed.display_name, seed.name
  FROM adp_module_transition_seed seed
  JOIN public.wf_deployment deployment
    ON deployment.process_key = seed.process_key
   AND coalesce(deployment.is_current_version, 0) = 1
 WHERE NOT EXISTS (
     SELECT 1 FROM public.wf_transition current_row
      WHERE current_row.deployment_id = deployment.id
        AND current_row.code = seed.code
 );

CREATE TEMP TABLE adp_module_flow_permission_seed (
    process_key text NOT NULL,
    offset_id bigint NOT NULL,
    activity_code text NOT NULL
) ON COMMIT DROP;

INSERT INTO adp_module_flow_permission_seed VALUES
        ('potrolTaskWF', 403, 'TaskEvent_0zg7ttg'),
        ('potrolTaskWF', 404, 'TaskEvent_146dnjp'),
        ('tempTaskWF', 403, 'TaskEvent_11icizp'),
        ('tempTaskWF', 404, 'TaskEvent_1ny8a19');

INSERT INTO public.rbac_flow_permission (
    id, version, create_time, modify_time, create_staff_id, modify_staff_id,
    cid, entity_code, purview_distribution, purview_state, memo,
    unlimited_power, group_power_flag, assign_staff_flag, assign_pos_flag,
    position_power_flag, flow_permission_type, type_id, activity_code,
    flow_version, flow_key, flow_name, flow_name_display
)
SELECT deployment.id + seed.offset_id, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
       1, 1, 1000, deployment.entity_code, 3, 1, '', true, false, false,
       false, false, 'USER', 1, seed.activity_code, '1',
       seed.process_key, deployment.name, deployment.name_zh_cn
  FROM adp_module_flow_permission_seed seed
  JOIN public.wf_deployment deployment
    ON deployment.process_key = seed.process_key
   AND coalesce(deployment.is_current_version, 0) = 1
 WHERE NOT EXISTS (
     SELECT 1 FROM public.rbac_flow_permission current_row
      WHERE current_row.flow_key = seed.process_key
        AND current_row.activity_code = seed.activity_code
        AND current_row.flow_permission_type = 'USER'
        AND current_row.type_id = 1
 );

DO $jbpm$
DECLARE
    seed adp_module_workflow_seed%ROWTYPE;
BEGIN
    FOR seed IN SELECT * FROM adp_module_workflow_seed ORDER BY process_key
    LOOP
        IF EXISTS (
            SELECT 1 FROM public.jbpm4_deployment current_row
             WHERE current_row.dbid_ = seed.jbpm_id
               AND NOT EXISTS (
                   SELECT 1 FROM public.jbpm4_deployprop prop
                    WHERE prop.deployment_ = seed.jbpm_id
                      AND prop.key_ = 'pdkey'
                      AND prop.stringval_ = seed.process_key
               )
        ) THEN
            RAISE EXCEPTION 'PATROL JBPM deterministic ID % collides with existing data', seed.jbpm_id;
        END IF;

        INSERT INTO public.jbpm4_deployment(dbid_, name_, timestamp_, state_)
        VALUES (seed.jbpm_id, '', 0, CASE WHEN seed.is_suspended = 1 THEN 'suspended' ELSE 'active' END)
        ON CONFLICT (dbid_) DO UPDATE SET state_ = EXCLUDED.state_;

        INSERT INTO public.jbpm4_deployprop(dbid_, deployment_, objname_, key_, stringval_, longval_)
        VALUES
            (seed.jbpm_id + 1, seed.jbpm_id, seed.process_key, 'langid', 'jpdl-4.4', NULL),
            (seed.jbpm_id + 2, seed.jbpm_id, seed.process_key, 'pdid', seed.process_key || '-1', NULL),
            (seed.jbpm_id + 3, seed.jbpm_id, seed.process_key, 'pdkey', seed.process_key, NULL),
            (seed.jbpm_id + 4, seed.jbpm_id, seed.process_key, 'pdversion', NULL, 1)
        ON CONFLICT (dbid_) DO UPDATE SET
            deployment_ = EXCLUDED.deployment_, objname_ = EXCLUDED.objname_,
            key_ = EXCLUDED.key_, stringval_ = EXCLUDED.stringval_,
            longval_ = EXCLUDED.longval_;

        IF NOT EXISTS (SELECT 1 FROM public.jbpm4_lob WHERE dbid_ = seed.jbpm_id + 10) THEN
            INSERT INTO public.jbpm4_lob(dbid_, dbversion_, blob_value_, deployment_, name_)
            VALUES (
                seed.jbpm_id + 10, 0,
                lo_from_bytea(0, convert_to(seed.process_xml, 'UTF8')),
                seed.jbpm_id, seed.process_key || '.jpdl.xml'
            );
        END IF;
    END LOOP;
END $jbpm$;

CREATE INDEX IF NOT EXISTS idx_wf_task_patrol_deployment_code
    ON public.wf_task(deployment_id, code);
CREATE INDEX IF NOT EXISTS idx_wf_transition_patrol_deployment_from
    ON public.wf_transition(deployment_id, from_node_code);
CREATE INDEX IF NOT EXISTS idx_rbac_flow_permission_patrol_activity
    ON public.rbac_flow_permission(flow_key, activity_code, purview_state);

COMMIT;
