-- Source: systemcode.xml
-- Source SHA-256: c9840e62d01e7104117336f1ab678029de2ea47602079897a5f39fb29d6c5689
-- Generated by deploy/docker/scripts/generate-module-system-code-sql.py

BEGIN;

WITH source(id, type, code, name, display_name, module_id, cid, valid, multi_flag, sys_default, memo) AS (
    VALUES
        (7056663103993698, 'list', 'PATROL_dateWindow', 'PATROL.systemEntityname.randon1589771192925', 'PATROL.systemEntityname.randon1589771192925', 'PATROL', 1000, 1, 0, 0, ''),
        (7106243149244106, 'list', 'PATROL_finishType', 'PATROL.systemEntityname.randon1576746169451', 'PATROL.systemEntityname.randon1576746169451', 'PATROL', 1000, 1, 0, 0, ''),
        (7245952316070556, 'list', 'PATROL_monthRepeatType', 'PATROL.systemEntityname.randon1576747761701', 'PATROL.systemEntityname.randon1576747761701', 'PATROL', 1000, 1, 0, 0, ''),
        (7278478381771007, 'list', 'PATROL_staffAssign', 'PATROL.systemEntityname.randon1576830784001', 'PATROL.systemEntityname.randon1576830784001', 'PATROL', 1000, 1, 0, 0, ''),
        (7131494576679920, 'list', 'PATROL_week', 'PATROL.systemEntityname.randon1576309705399', 'PATROL.systemEntityname.randon1576309705399', 'PATROL', 1000, 1, 0, 0, ''),
        (7001078441312311, 'list', 'PATROL_taskState', 'PATROL.systemEntityname.randon1577193574613', 'PATROL.systemEntityname.randon1577193574613', 'PATROL', 1000, 1, 0, 0, ''),
        (7181208845407229, 'list', 'PATROL_editType', 'PATROL.systemEntityname.randon1575354684864', 'PATROL.systemEntityname.randon1575354684864', 'PATROL', 1000, 1, 0, 0, ''),
        (7002737278180859, 'list', 'PATROL_valueType', 'PATROL.systemEntityname.randon1575354987758', 'PATROL.systemEntityname.randon1575354987758', 'PATROL', 1000, 1, 0, 0, ''),
        (7165435745504816, 'list', 'PATROL_assignType', 'PATROL.systemEntityname.randon1576648945152', 'PATROL.systemEntityname.randon1576648945152', 'PATROL', 1000, 1, 0, 0, ''),
        (7062333072128693, 'list', 'PATROL_dayRepeatType', 'PATROL.systemEntityname.randon1576747895875', 'PATROL.systemEntityname.randon1576747895875', 'PATROL', 1000, 1, 0, 0, ''),
        (7229269567033406, 'list', 'PATROL_passReason', 'PATROL.systemEntityname.randon1584601398319', 'PATROL.systemEntityname.randon1584601398319', 'PATROL', 1000, 1, 0, 0, ''),
        (7081508402746840, 'list', 'PATROL_faultStatus', 'PATROL.systemEntityname.randon1589593829054', 'PATROL.systemEntityname.randon1589593829054', 'PATROL', 1000, 1, 0, 0, ''),
        (7247453771928674, 'list', 'PATROL_routeType', 'PATROL.systemEntityname.randon1575464639032', 'PATROL.systemEntityname.randon1575464639032', 'PATROL', 1000, 1, 0, 0, ''),
        (7135648348386624, 'list', 'PATROL_planType', 'PATROL.systemEntityname.randon1576309467041', 'PATROL.systemEntityname.randon1576309467041', 'PATROL', 1000, 1, 0, 0, ''),
        (7262378018126507, 'list', 'PATROL_payCardType', 'PATROL.systemEntityname.randon1577590986632', 'PATROL.systemEntityname.randon1577590986632', 'PATROL', 1000, 1, 0, 0, ''),
        (7190497698338450, 'list', 'PATROL_signInType', 'PATROL.systemEntityname.randon1577591156262', 'PATROL.systemEntityname.randon1577591156262', 'PATROL', 1000, 1, 0, 0, ''),
        (7253116190543579, 'list', 'PATROL_realValue', 'PATROL.systemEntityname.randon1584600866455', 'PATROL.systemEntityname.randon1584600866455', 'PATROL', 1000, 1, 0, 0, ''),
        (7134073051125032, 'list', 'PATROL_tempTaskSource', 'PATROL.systemEntityname.randon1602840918822', 'PATROL.systemEntityname.randon1602840918822', 'PATROL', 1000, 1, 0, 0, ''),
        (7200617624658844, 'list', 'PATROL_taskDetailState', 'PATROL.systemEntityname.randon1587109710964', 'PATROL.systemEntityname.randon1587109710964', 'PATROL', 1000, 1, 0, 0, '')
), updated AS (
    UPDATE public.sys_entity target
       SET row_version = 0, type = source.type, name = source.name,
           display_name = source.display_name, module_id = source.module_id,
           cid = source.cid, valid = source.valid, multi_flag = source.multi_flag,
           sys_default = source.sys_default, memo = source.memo, modify_time = CURRENT_TIMESTAMP
      FROM source
     WHERE target.code = source.code
 RETURNING target.code
)
INSERT INTO public.sys_entity
    (id, row_version, type, code, name, display_name, module_id, cid, valid, multi_flag, sys_default, memo, source)
SELECT source.id, 0, source.type, source.code, source.name, source.display_name,
       source.module_id, source.cid, source.valid, source.multi_flag, source.sys_default, source.memo, 'module'
  FROM source
 WHERE NOT EXISTS (SELECT 1 FROM public.sys_entity current_row WHERE current_row.code = source.code)
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, code = EXCLUDED.code, name = EXCLUDED.name,
    display_name = EXCLUDED.display_name, module_id = EXCLUDED.module_id,
    cid = EXCLUDED.cid, valid = EXCLUDED.valid, multi_flag = EXCLUDED.multi_flag,
    sys_default = EXCLUDED.sys_default, memo = EXCLUDED.memo, modify_time = CURRENT_TIMESTAMP;

WITH source(id, type, code, entity_code, name, display_name, cid, valid, leaf, default_flag,
            full_path, full_path_name, parent_id, parent_name, lay_no, lay_rec, seq_id, sort,
            des_a, des_b, des_c, memo) AS (
    VALUES
        (1439496794570672, 'list', 'lastWeek', 'PATROL_dateWindow', 'PATROL.systemCodevalue.randon1589876520357', '近7天', 1000, 1, 1, 0, 'PATROL_dateWindow/lastWeek', '近7天', NULL::bigint, 'PATROL.systemEntityname.randon1589771192925', 1, '1439496794570672', NULL::bigint, 546, '', '', '', ''),
        (1439496794800048, 'list', 'lastMonth', 'PATROL_dateWindow', 'PATROL.systemCodevalue.randon1589876500831', '近30天', 1000, 1, 1, 0, 'PATROL_dateWindow/lastMonth', '近30天', NULL::bigint, 'PATROL.systemEntityname.randon1589771192925', 1, '1439496794800048', NULL::bigint, 545, '', '', '', ''),
        (1439496796667824, 'list', 'none', 'PATROL_finishType', 'PATROL.propertyshowName.randon1576312174954.flag', '无结束时', 1000, 1, 1, 0, 'PATROL_finishType/none', '无结束时', NULL::bigint, 'PATROL.systemEntityname.randon1576746169451', 1, '1439496796667824', NULL::bigint, 547, '', '', '', ''),
        (1439496796864432, 'list', 'repeatNum', 'PATROL_finishType', 'PATROL.systemCodevalue.randon1576746259005', '重复次数', 1000, 1, 1, 0, 'PATROL_finishType/repeatNum', '重复次数', NULL::bigint, 'PATROL.systemEntityname.randon1576746169451', 1, '1439496796864432', NULL::bigint, 548, '', '', '', ''),
        (1439496797061040, 'list', 'finishTime', 'PATROL_finishType', 'ec.scheduler.job.endtime', '结束时间', 1000, 1, 1, 0, 'PATROL_finishType/finishTime', '结束时间', NULL::bigint, 'PATROL.systemEntityname.randon1576746169451', 1, '1439496797061040', NULL::bigint, 549, '', '', '', ''),
        (1439496797585328, 'list', 'day', 'PATROL_monthRepeatType', 'PATROL.systemCodevalue.randon1576747804003', '按天', 1000, 1, 1, 0, 'PATROL_monthRepeatType/day', '按天', NULL::bigint, 'PATROL.systemEntityname.randon1576747761701', 1, '1439496797585328', NULL::bigint, 550, '', '', '', ''),
        (1439496797814704, 'list', 'week', 'PATROL_monthRepeatType', 'PATROL.systemCodevalue.randon1576747815817', '按周', 1000, 1, 1, 0, 'PATROL_monthRepeatType/week', '按周', NULL::bigint, 'PATROL.systemEntityname.randon1576747761701', 1, '1439496797814704', NULL::bigint, 551, '', '', '', ''),
        (1439496798404528, 'list', 'team', 'PATROL_staffAssign', 'PATROL.systemCodevalue.randon1576830960476', '班组', 1000, 1, 1, 0, 'PATROL_staffAssign/team', '班组', NULL::bigint, 'PATROL.systemEntityname.randon1576830784001', 1, '1439496798404528', NULL::bigint, 552, '', '', '', ''),
        (1439496798601136, 'list', 'staff', 'PATROL_staffAssign', 'ec.workflow.modifyOwner.ownerName', '负责人', 1000, 1, 1, 0, 'PATROL_staffAssign/staff', '负责人', NULL::bigint, 'PATROL.systemEntityname.randon1576830784001', 1, '1439496798601136', NULL::bigint, 553, '', '', '', ''),
        (1439496799158192, 'list', 'Monday', 'PATROL_week', 'foundation.calendar.monday', '周一', 1000, 1, 1, 0, 'PATROL_week/Monday', '周一', NULL::bigint, 'PATROL.systemEntityname.randon1576309705399', 1, '1439496799158192', NULL::bigint, 554, '', '', '', ''),
        (1439496799354800, 'list', 'tuesday', 'PATROL_week', 'PATROL.systemCodevalue.randon1576309778772', '周二', 1000, 1, 1, 0, 'PATROL_week/tuesday', '周二', NULL::bigint, 'PATROL.systemEntityname.randon1576309705399', 1, '1439496799354800', NULL::bigint, 555, '', '', '', ''),
        (1439496799551408, 'list', 'wednesday', 'PATROL_week', 'PATROL.systemCodevalue.randon1576309801456', '周三', 1000, 1, 1, 0, 'PATROL_week/wednesday', '周三', NULL::bigint, 'PATROL.systemEntityname.randon1576309705399', 1, '1439496799551408', NULL::bigint, 556, '', '', '', ''),
        (1439496799748016, 'list', 'thursday', 'PATROL_week', 'PATROL.systemCodevalue.randon1576309828329', '周四', 1000, 1, 1, 0, 'PATROL_week/thursday', '周四', NULL::bigint, 'PATROL.systemEntityname.randon1576309705399', 1, '1439496799748016', NULL::bigint, 557, '', '', '', ''),
        (1439496799977392, 'list', 'friday', 'PATROL_week', 'PATROL.systemCodevalue.randon1576309846303', '周五', 1000, 1, 1, 0, 'PATROL_week/friday', '周五', NULL::bigint, 'PATROL.systemEntityname.randon1576309705399', 1, '1439496799977392', NULL::bigint, 558, '', '', '', ''),
        (1439496800174000, 'list', 'saturday', 'PATROL_week', 'PATROL.systemCodevalue.randon1576309867091', '周六', 1000, 1, 1, 0, 'PATROL_week/saturday', '周六', NULL::bigint, 'PATROL.systemEntityname.randon1576309705399', 1, '1439496800174000', NULL::bigint, 559, '', '', '', ''),
        (1439496800370608, 'list', 'sunday', 'PATROL_week', 'PATROL.systemCodevalue.randon1576309892002', '周日', 1000, 1, 1, 0, 'PATROL_week/sunday', '周日', NULL::bigint, 'PATROL.systemEntityname.randon1576309705399', 1, '1439496800370608', NULL::bigint, 560, '', '', '', ''),
        (1439496800927664, 'list', 'running', 'PATROL_taskState', 'PATROL.systemCodevalue.randon1597116157035', '执行中', 1000, 1, 1, 0, 'PATROL_taskState/running', '执行中', NULL::bigint, 'PATROL.systemEntityname.randon1577193574613', 1, '1439496800927664', NULL::bigint, 561, '', '', '', ''),
        (1439496801124272, 'list', 'notIssued', 'PATROL_taskState', 'PATROL.systemCodevalue.randon1577193608417', '未下发', 1000, 1, 1, 0, 'PATROL_taskState/notIssued', '未下发', NULL::bigint, 'PATROL.systemEntityname.randon1577193574613', 1, '1439496801124272', NULL::bigint, 280, '', '', '', ''),
        (1439496801353648, 'list', 'cancelled', 'PATROL_taskState', 'PATROL.systemCodevalue.randon1577193725091', '已取消', 1000, 1, 1, 0, 'PATROL_taskState/cancelled', '已取消', NULL::bigint, 'PATROL.systemEntityname.randon1577193574613', 1, '1439496801353648', NULL::bigint, 563, '', '', '', ''),
        (1439496801550256, 'list', 'issued', 'PATROL_taskState', 'PATROL.systemCodevalue.randon1577193669011', '已下发', 1000, 1, 1, 0, 'PATROL_taskState/issued', '已下发', NULL::bigint, 'PATROL.systemEntityname.randon1577193574613', 1, '1439496801550256', NULL::bigint, 420, '', '', '', ''),
        (1439496801779632, 'list', 'completed', 'PATROL_taskState', 'PATROL.systemCodevalue.randon1577193701064', '已完成', 1000, 1, 1, 0, 'PATROL_taskState/completed', '已完成', NULL::bigint, 'PATROL.systemEntityname.randon1577193574613', 1, '1439496801779632', NULL::bigint, 562, '', '', '', ''),
        (1439496801976240, 'list', 'overdue', 'PATROL_taskState', 'PATROL.systemCodevalue.randon1587381766728', '已超期', 1000, 1, 1, 0, 'PATROL_taskState/overdue', '已超期', NULL::bigint, 'PATROL.systemEntityname.randon1577193574613', 1, '1439496801976240', NULL::bigint, 562, '', '', '', '任务计划结束时间大于当前时间'),
        (1439496802533296, 'list', 'input', 'PATROL_editType', 'PATROL.systemCodevalue.randon1575354787212', '录入', 1000, 1, 1, 0, 'PATROL_editType/input', '录入', NULL::bigint, 'PATROL.systemEntityname.randon1575354684864', 1, '1439496802533296', NULL::bigint, 567, '', '', '', ''),
        (1439496802697136, 'list', 'singleSelect', 'PATROL_editType', 'ec.property.radio', '单选', 1000, 1, 1, 0, 'PATROL_editType/singleSelect', '单选', NULL::bigint, 'PATROL.systemEntityname.randon1575354684864', 1, '1439496802697136', NULL::bigint, 568, '', '', '', ''),
        (1439496802926512, 'list', 'multipleSelect', 'PATROL_editType', 'PATROL.systemCodevalue.randon1575354861516', '多选', 1000, 1, 1, 0, 'PATROL_editType/multipleSelect', '多选', NULL::bigint, 'PATROL.systemEntityname.randon1575354684864', 1, '1439496802926512', NULL::bigint, 569, '', '', '', ''),
        (1439496803123120, 'list', 'whether', 'PATROL_editType', 'PATROL.systemCodevalue.randon1575354908424', '是否', 1000, 1, 1, 0, 'PATROL_editType/whether', '是否', NULL::bigint, 'PATROL.systemEntityname.randon1575354684864', 1, '1439496803123120', NULL::bigint, 570, '', '', '', ''),
        (1439496803712944, 'list', 'char', 'PATROL_valueType', 'PATROL.systemCodevalue.randon1575355004389', '字符', 1000, 1, 1, 0, 'PATROL_valueType/char', '字符', NULL::bigint, 'PATROL.systemEntityname.randon1575354987758', 1, '1439496803712944', NULL::bigint, 571, '', '', '', ''),
        (1439496803942320, 'list', 'number', 'PATROL_valueType', 'foundation.user.passwordContain.num', '数字', 1000, 1, 1, 0, 'PATROL_valueType/number', '数字', NULL::bigint, 'PATROL.systemEntityname.randon1575354987758', 1, '1439496803942320', NULL::bigint, 572, '', '', '', ''),
        (1439496804466608, 'list', 'Assign', 'PATROL_assignType', 'PATROL.systemCodevalue.randon1576649003338', '指派模式', 1000, 1, 1, 0, 'PATROL_assignType/Assign', '指派模式', NULL::bigint, 'PATROL.systemEntityname.randon1576648945152', 1, '1439496804466608', NULL::bigint, 573, '', '', '', ''),
        (1439496804695984, 'list', 'effect', 'PATROL_assignType', 'ec.pending.over', '生效', 1000, 1, 1, 0, 'PATROL_assignType/effect', '生效', NULL::bigint, 'PATROL.systemEntityname.randon1576648945152', 1, '1439496804695984', NULL::bigint, 574, '', '', '', ''),
        (1439496805253040, 'list', 'day', 'PATROL_dayRepeatType', 'PATROL.patrolPlan.PatrolPlan.day', '天', 1000, 1, 1, 0, 'PATROL_dayRepeatType/day', '天', NULL::bigint, 'PATROL.systemEntityname.randon1576747895875', 1, '1439496805253040', NULL::bigint, 575, '', '', '', ''),
        (1439496805482416, 'list', 'workDay', 'PATROL_dayRepeatType', 'foundation.calendar.workday', '工作日', 1000, 1, 1, 0, 'PATROL_dayRepeatType/workDay', '工作日', NULL::bigint, 'PATROL.systemEntityname.randon1576747895875', 1, '1439496805482416', NULL::bigint, 576, '', '', '', ''),
        (1439496806006704, 'list', 'notEnabled', 'PATROL_passReason', 'PATROL.systemCodevalue.randon1584601425995', '设备未启用', 1000, 1, 1, 0, 'PATROL_passReason/notEnabled', '设备未启用', NULL::bigint, 'PATROL.systemEntityname.randon1584601398319', 1, '1439496806006704', NULL::bigint, 577, '', '', '', ''),
        (1439496806662064, 'list', 'compelet', 'PATROL_faultStatus', 'PATROL.systemCodevalue.randon1589593856533', '已完结', 1000, 1, 1, 0, 'PATROL_faultStatus/compelet', '已完结', NULL::bigint, 'PATROL.systemEntityname.randon1589593829054', 1, '1439496806662064', NULL::bigint, 578, '', '', '', ''),
        (1439496806891440, 'list', 'void', 'PATROL_faultStatus', 'PATROL.systemCodevalue.randon1589593870635', '作废', 1000, 1, 1, 0, 'PATROL_faultStatus/void', '作废', NULL::bigint, 'PATROL.systemEntityname.randon1589593829054', 1, '1439496806891440', NULL::bigint, 579, '', '', '', ''),
        (1439496807153584, 'list', 'ongoing', 'PATROL_faultStatus', 'PATROL.systemCodevalue.randon1589593893305', '进行中', 1000, 1, 1, 0, 'PATROL_faultStatus/ongoing', '进行中', NULL::bigint, 'PATROL.systemEntityname.randon1589593829054', 1, '1439496807153584', NULL::bigint, 580, '', '', '', ''),
        (1439496807776176, 'list', 'eam', 'PATROL_routeType', 'PATROL.systemCodevalue.randon1575464679237', '设备巡检', 1000, 1, 1, 0, 'PATROL_routeType/eam', '设备巡检', NULL::bigint, 'PATROL.systemEntityname.randon1575464639032', 1, '1439496807776176', NULL::bigint, 581, '', '', '', ''),
        (1439496808005552, 'list', 'technology', 'PATROL_routeType', 'PATROL.systemCodevalue.randon1575464694628', '工艺巡检', 1000, 1, 1, 0, 'PATROL_routeType/technology', '工艺巡检', NULL::bigint, 'PATROL.systemEntityname.randon1575464639032', 1, '1439496808005552', NULL::bigint, 582, '', '', '', ''),
        (1439496808234928, 'list', 'ses', 'PATROL_routeType', 'PATROL.systemCodevalue.randon1575464736112', '安环巡检', 1000, 1, 1, 0, 'PATROL_routeType/ses', '安环巡检', NULL::bigint, 'PATROL.systemEntityname.randon1575464639032', 1, '1439496808234928', NULL::bigint, 583, '', '', '', ''),
        (1439496808759216, 'list', 'single', 'PATROL_planType', 'PATROL.systemCodevalue.randon1576309499141', '单次', 1000, 1, 1, 0, 'PATROL_planType/single', '单次', NULL::bigint, 'PATROL.systemEntityname.randon1576309467041', 1, '1439496808759216', NULL::bigint, 584, '', '', '', ''),
        (1439496808955824, 'list', 'week', 'PATROL_planType', 'PATROL.systemCodevalue.randon1576309601567', '按周重复', 1000, 1, 1, 0, 'PATROL_planType/week', '按周重复', NULL::bigint, 'PATROL.systemEntityname.randon1576309467041', 1, '1439496808955824', NULL::bigint, 585, '', '', '', ''),
        (1439496809152432, 'list', 'month', 'PATROL_planType', 'PATROL.systemCodevalue.randon1576309633780', '按月重复', 1000, 1, 1, 0, 'PATROL_planType/month', '按月重复', NULL::bigint, 'PATROL.systemEntityname.randon1576309467041', 1, '1439496809152432', NULL::bigint, 586, '', '', '', ''),
        (1439496809381808, 'list', 'hour', 'PATROL_planType', 'PATROL.systemCodevalue.randon1576309529218', '按小时重复', 1000, 1, 1, 0, 'PATROL_planType/hour', '按小时重复', NULL::bigint, 'PATROL.systemEntityname.randon1576309467041', 1, '1439496809381808', NULL::bigint, 584, '', '', '', ''),
        (1439496809578416, 'list', 'day', 'PATROL_planType', 'PATROL.systemCodevalue.randon1576309554023', '按天重复', 1000, 1, 1, 0, 'PATROL_planType/day', '按天重复', NULL::bigint, 'PATROL.systemEntityname.randon1576309467041', 1, '1439496809578416', NULL::bigint, 584, '', '', '', ''),
        (1439496810201008, 'list', 'card', 'PATROL_payCardType', 'PATROL.systemCodevalue.randon1577591038339', '刷卡签到', 1000, 1, 1, 0, 'PATROL_payCardType/card', '刷卡签到', NULL::bigint, 'PATROL.systemEntityname.randon1577590986632', 1, '1439496810201008', NULL::bigint, 589, '', '', '', ''),
        (1439496810430384, 'list', 'signIn', 'PATROL_payCardType', 'PATROL.patrolRoute.WorkArea.isSign', '手工签到', 1000, 1, 1, 0, 'PATROL_payCardType/signIn', '手工签到', NULL::bigint, 'PATROL.systemEntityname.randon1577590986632', 1, '1439496810430384', NULL::bigint, 590, '', '', '', ''),
        (1439496811052976, 'list', 'break', 'PATROL_signInType', 'PATROL.systemCodevalue.randon1577591213430', '标签损坏', 1000, 1, 1, 0, 'PATROL_signInType/break', '标签损坏', NULL::bigint, 'PATROL.systemEntityname.randon1577591156262', 1, '1439496811052976', NULL::bigint, 591, '', '', '', ''),
        (1439496811282352, 'list', 'notPosted', 'PATROL_signInType', 'PATROL.systemCodevalue.randon1577591322730', '未贴标签', 1000, 1, 1, 0, 'PATROL_signInType/notPosted', '未贴标签', NULL::bigint, 'PATROL.systemEntityname.randon1577591156262', 1, '1439496811282352', NULL::bigint, 592, '', '', '', ''),
        (1439496811478960, 'list', 'other', 'PATROL_signInType', 'foundation.module.systemcode.other', '其他', 1000, 1, 1, 0, 'PATROL_signInType/other', '其他', NULL::bigint, 'PATROL.systemEntityname.randon1577591156262', 1, '1439496811478960', NULL::bigint, 593, '', '', '', ''),
        (1439496812036016, 'list', 'abnormal', 'PATROL_realValue', 'PATROL.systemCodevalue.randon1584600915950', '异常', 1000, 1, 1, 0, 'PATROL_realValue/abnormal', '异常', NULL::bigint, 'PATROL.systemEntityname.randon1584600866455', 1, '1439496812036016', NULL::bigint, 594, '', '', '', ''),
        (1439496812232624, 'list', 'doubtful', 'PATROL_realValue', 'PATROL.systemCodevalue.randon1584600994180', '可疑', 1000, 1, 1, 0, 'PATROL_realValue/doubtful', '可疑', NULL::bigint, 'PATROL.systemEntityname.randon1584600866455', 1, '1439496812232624', NULL::bigint, 595, '', '', '', ''),
        (1439496812494768, 'list', 'normal', 'PATROL_realValue', 'PATROL.systemCodevalue.randon1584600907721', '正常', 1000, 1, 1, 0, 'PATROL_realValue/normal', '正常', NULL::bigint, 'PATROL.systemEntityname.randon1584600866455', 1, '1439496812494768', NULL::bigint, 596, '', '', '', ''),
        (1439496813084592, 'list', 'PDA', 'PATROL_tempTaskSource', 'PATROL.systemCodevalue.randon1602840978273', 'PDA', 1000, 1, 1, 0, 'PATROL_tempTaskSource/PDA', 'PDA', NULL::bigint, 'PATROL.systemEntityname.randon1602840918822', 1, '1439496813084592', NULL::bigint, 597, '', '', '', ''),
        (1439496813313968, 'list', 'PC', 'PATROL_tempTaskSource', 'PATROL.systemCodevalue.randon1602840992312', 'PC', 1000, 1, 1, 0, 'PATROL_tempTaskSource/PC', 'PC', NULL::bigint, 'PATROL.systemEntityname.randon1602840918822', 1, '1439496813313968', NULL::bigint, 598, '', '', '', ''),
        (1439496813871024, 'list', 'checked', 'PATROL_taskDetailState', 'PATROL.systemCodevalue.randon1587109893795', '已检', 1000, 1, 1, 0, 'PATROL_taskDetailState/checked', '已检', NULL::bigint, 'PATROL.systemEntityname.randon1587109710964', 1, '1439496813871024', NULL::bigint, 541, '', '', '', ''),
        (1439496814067632, 'list', 'skip', 'PATROL_taskDetailState', 'PATROL.systemCodevalue.randon1587109870185', '跳检', 1000, 1, 1, 0, 'PATROL_taskDetailState/skip', '跳检', NULL::bigint, 'PATROL.systemEntityname.randon1587109710964', 1, '1439496814067632', NULL::bigint, 542, '', '', '', ''),
        (1439496814264240, 'list', 'exemption', 'PATROL_taskDetailState', 'PATROL.systemCodevalue.randon1587109783298', '免检', 1000, 1, 1, 0, 'PATROL_taskDetailState/exemption', '免检', NULL::bigint, 'PATROL.systemEntityname.randon1587109710964', 1, '1439496814264240', NULL::bigint, 543, '', '', '', ''),
        (1439496814460848, 'list', 'pending', 'PATROL_taskDetailState', 'PATROL.systemCodevalue.randon1587109851119', '待检', 1000, 1, 1, 0, 'PATROL_taskDetailState/pending', '待检', NULL::bigint, 'PATROL.systemEntityname.randon1587109710964', 1, '1439496814460848', NULL::bigint, 544, '', '', '', '')
), updated AS (
    UPDATE public.sys_code target
       SET row_version = 0, type = source.type, name = source.name, display_name = source.display_name,
           cid = source.cid, valid = source.valid, leaf = source.leaf, default_flag = source.default_flag,
           full_path = source.full_path, full_path_name = source.full_path_name,
           parent_id = source.parent_id, parent_name = source.parent_name, lay_no = source.lay_no,
           lay_rec = source.lay_rec, seq_id = source.seq_id, sort = source.sort,
           des_a = source.des_a, des_b = source.des_b, des_c = source.des_c,
           memo = source.memo, modify_time = CURRENT_TIMESTAMP
      FROM source
     WHERE target.entity_code = source.entity_code AND target.code = source.code
 RETURNING target.entity_code, target.code
)
INSERT INTO public.sys_code
    (id, row_version, type, code, entity_code, name, display_name, cid, valid, leaf, default_flag,
     full_path, full_path_name, parent_id, parent_name, lay_no, lay_rec, seq_id, sort, des_a, des_b, des_c, memo)
SELECT source.id, 0, source.type, source.code, source.entity_code, source.name, source.display_name,
       source.cid, source.valid, source.leaf, source.default_flag, source.full_path, source.full_path_name,
       source.parent_id, source.parent_name, source.lay_no, source.lay_rec, source.seq_id, source.sort,
       source.des_a, source.des_b, source.des_c, source.memo
  FROM source
 WHERE NOT EXISTS (
       SELECT 1 FROM public.sys_code current_row
        WHERE current_row.entity_code = source.entity_code AND current_row.code = source.code
 )
ON CONFLICT (id) DO UPDATE SET
    type = EXCLUDED.type, code = EXCLUDED.code, entity_code = EXCLUDED.entity_code,
    name = EXCLUDED.name, display_name = EXCLUDED.display_name, cid = EXCLUDED.cid,
    valid = EXCLUDED.valid, leaf = EXCLUDED.leaf, default_flag = EXCLUDED.default_flag,
    full_path = EXCLUDED.full_path, full_path_name = EXCLUDED.full_path_name,
    parent_id = EXCLUDED.parent_id, parent_name = EXCLUDED.parent_name, lay_no = EXCLUDED.lay_no,
    lay_rec = EXCLUDED.lay_rec, seq_id = EXCLUDED.seq_id, sort = EXCLUDED.sort,
    des_a = EXCLUDED.des_a, des_b = EXCLUDED.des_b, des_c = EXCLUDED.des_c,
    memo = EXCLUDED.memo, modify_time = CURRENT_TIMESTAMP;

COMMIT;
