## 1.0.0
/*====================================================*/
/* TABLE: 门户信息表                                       */
/*====================================================*/
CREATE TABLE EC_PORTLET (
    CODE VARCHAR(510) NOT NULL,
    MEMO VARCHAR(4000),
    HEIGHT INT,
    RESIZE_FUNC TEXT,
    ONLOAD_FUNC TEXT,
    IFRAME_FLAG TINYINT,
    MENU_INFO_ID NUMERIC,
    MENU_OPERATE_ID NUMERIC,
    MENU_CODE VARCHAR(510),
    OPERATE_CODE VARCHAR(510),
    CID NUMERIC,
    MODULE_CODE VARCHAR(510),
    IS_HIDDEN TINYINT,
    POWER_FLAG TINYINT,
    SCOPE_NUM INT,
    VERSION INT DEFAULT 0,
    IS_DEFAULT INT,
    TITLE_COLOR VARCHAR(510),
    TITLE_KEY VARCHAR(510),
    TITLE VARCHAR(510),
    SIZE_NUM INT,
    MORE_TARGET VARCHAR(510),
    MORE_URL VARCHAR(510),
    URL VARCHAR(510),
    CREATOR VARCHAR(32) DEFAULT NULL,
    MODIFIER VARCHAR(32) DEFAULT NULL,
    TERMINATOR VARCHAR(32) DEFAULT NULL,
    CREATE_TIME DATETIME,
    MODIFY_TIME DATETIME,
    DELETE_TIME DATETIME,
    CREATE_STAFF_ID BIGINT ,
    MODIFY_STAFF_ID BIGINT ,
    PRIMARY KEY (CODE)
);
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '门户信息表', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', NULL, NULL;
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '编码主键', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'CODE';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '公司ID', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'CID';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '关联菜单ID', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'MENU_INFO_ID';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '关联菜单CODE', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'MENU_CODE';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '高度,IFRAMEFLAG为TRUE时有效', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'HEIGHT';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '是否适用IFRAME', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'IFRAME_FLAG';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '备注', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'MEMO';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '模板编码', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'MODULE_CODE';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '是否启用权限', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'POWER_FLAG';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '所属范围   0所有公司   1本公司', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'SCOPE_NUM';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '创建者', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'CREATOR';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '修改者', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'MODIFIER';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '删除者', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'TERMINATOR';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '创建时间', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'CREATE_TIME';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '修改时间', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'MODIFY_TIME';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '删除时间', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'DELETE_TIME';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '创建者人员ID', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'CREATE_STAFF_ID';
EXECUTE SP_ADDEXTENDEDPROPERTY N'MS_DESCRIPTION', '修改者人员ID', N'USER', N'DBO', N'TABLE', N'EC_PORTLET', N'COLUMN', N'MODIFY_STAFF_ID';
CREATE UNIQUE INDEX SYS_C00155238 ON EC_PORTLET(CODE);

CREATE TABLE EC_MY_PORTLET (
	ID numeric(19,0) NOT NULL,
	VERSION int DEFAULT 0,
	CONFIG text COLLATE Chinese_PRC_CI_AS NULL,
	USER_ID numeric(19,0) NULL,
	CONSTRAINT PK__EC_MY_PO__3214EC279912A35C PRIMARY KEY (ID)
);

## 1.0.1
INSERT INTO EC_PORTLET
(CODE, HEIGHT, IFRAME_FLAG,POWER_FLAG, CID, MODULE_CODE, TITLE_KEY, TITLE, URL)
VALUES('myProcess', 350, 1,0, 0, 'portal','portal.homepage.myProcess','portal.homepage.myProcess','/license/#/myProcess');

INSERT INTO EC_PORTLET
(CODE, HEIGHT, IFRAME_FLAG,POWER_FLAG, CID, MODULE_CODE, TITLE_KEY, TITLE, URL)
VALUES('pendingNotice', 110, 1,0, 0, 'portal','portal.homepage.pendingNotice','portal.homepage.pendingNotice','/license/#/pendingNotice');

## 1.0.2
UPDATE EC_PORTLET SET url='/supplant/#/myProcess' WHERE CODE = 'myProcess';
UPDATE EC_PORTLET SET url='/supplant/#/pendingNotice' WHERE CODE = 'pendingNotice';

## 1.0.3
INSERT INTO EC_MY_PORTLET
(ID ,CONFIG ,USER_ID)
VALUES(1,'[{"portlets":[{"cid":0,"code":"myProcess","default":false,"hidden":false,"iframeFlag":false,"menuInfoId":0,"powerFlag":false,"scopeNum":0,"title":"我的流程","titleKey":"portal.homepage.myProcess","url":"/supplant/#/myProcess?__t__=1616033155820"}],"width":"33%"},{"portlets":[{"cid":0,"code":"pendingNotice","default":false,"hidden":false,"iframeFlag":false,"menuInfoId":0,"powerFlag":false,"scopeNum":0,"title":"待办提醒","titleKey":"portal.homepage.pendingNotice","url":"/supplant/#/pendingNotice?__t__=1616033156792"}],"width":"33%"},{"portlets":[],"width":"33%"}]',-1);
