ws.port=30135
nacos.server-addr=127.0.0.1:8848
nacos.group=prod
ws.boosThreads=2
ws.workThreads=200
ws.connectTimeOutMills=3000
ws.bufferLowWaterMark=32768
ws.bufferHighWaterMark=65536
ws.idleTimeOutSeconds=60
jwt.header=Authorization
jwt.tokenHead=${REPLACE_ME}
jwt.secret=${REPLACE_ME}
