## 1.0.0
CREATE TABLE IF NOT EXISTS `mod_module_registry` (
  `id` BIGINT(20) NOT NULL,
  `module_id` VARCHAR(64) NOT NULL,
  `module_code` VARCHAR(128) DEFAULT NULL,
  `module_name` VARCHAR(64) NOT NULL,
  `module_type` VARCHAR(24) NOT NULL DEFAULT 'SYSTEM',
  `creator` VARCHAR(64) DEFAULT '',
  `create_time` TIMESTAMP DEFAULT current_timestamp,
  `create_staff_id` BIGINT(20) DEFAULT NULL,
  `modifier` VARCHAR(64) DEFAULT '',
  `modify_time` TIMESTAMP,
  `modify_staff_id` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `udx_mod_id` (`module_id`)
);
CREATE TABLE IF NOT EXISTS `mod_module_app_rel` (
  `id` BIGINT(20) NOT NULL,
  `app_id` VARCHAR(64) NOT NULL,
  `module_id` VARCHAR(64) NOT NULL,
  `creator` VARCHAR(64) DEFAULT '',
  `create_time` TIMESTAMP DEFAULT current_timestamp,
  `create_staff_id` BIGINT(20) DEFAULT NULL,
  `modifier` VARCHAR(64) DEFAULT '',
  `modify_time` TIMESTAMP,
  `modify_staff_id` BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_module_app_rel_appid` (`app_id`)
);
insert into mod_module_registry(id, module_id, module_name, module_type) values
(10000, 'authentication', 'reg.moduleName.authentication', 'SYSTEM'),
(10001, 'notificationEmail', 'reg.moduleName.notificationEmail', 'SYSTEM'),
(10002, 'appConfig', 'reg.moduleName.appConfig', 'SYSTEM'),
(10003, 'notificationDingtalk', 'reg.moduleName.notificationDingtalk', 'SYSTEM'),
(10004, 'systemConfig', 'reg.moduleName.systemConfig', 'SYSTEM'),
(10005, 'notificationWechat', 'reg.moduleName.notificationWechat', 'SYSTEM'),
(10006, 'reg', 'reg.moduleName.reg', 'SYSTEM'),
(10007, 'sys', 'reg.moduleName.sys', 'SYSTEM'),
(10008, 'i18n', 'reg.moduleName.i18n', 'SYSTEM'),
(10009, 'notificationStationletter', 'reg.moduleName.notificationStationletter', 'SYSTEM'),
(10010, 'notificationApiServer', 'reg.moduleName.notificationApiServer', 'SYSTEM'),
(10011, 'workflow', 'reg.moduleName.workflow', 'SYSTEM'),
(10012, 'organization', 'reg.moduleName.organization', 'SYSTEM'),
(10013, 'theme', 'reg.moduleName.theme', 'SYSTEM'),
(10014, 'userManagement', 'reg.moduleName.userManagement', 'SYSTEM'),
(10015, 'composeManage', 'reg.moduleName.composeManage', 'SYSTEM'),
(10016, 'notificationAdmin', 'reg.moduleName.notificationAdmin', 'SYSTEM'),
(10017, 'notificationEngine', 'reg.moduleName.notificationEngine', 'SYSTEM'),
(10018, 'rbac', 'reg.moduleName.rbac', 'SYSTEM'),
(10019, 'systemCode', 'reg.moduleName.systemCode', 'SYSTEM'),
(10020, 'appManager', 'reg.moduleName.appManager', 'SYSTEM'),
(10021, 'signature', 'reg.moduleName.signature', 'SYSTEM'),
(10022, 'portal', 'reg.moduleName.portal', 'SYSTEM'),
(10023, 'fileServer', 'reg.moduleName.fileServer', 'SYSTEM'),
(10024, 'taskScheduler', 'reg.moduleName.taskScheduler', 'SYSTEM'),
(10025, 'counter', 'reg.moduleName.counter', 'SYSTEM'),
(10026, 'sysbase', 'reg.moduleName.sysbase', 'SYSTEM'),
(10027, 'printer', 'reg.moduleName.printer', 'SYSTEM'),
(10028, 'auditlog', 'reg.moduleName.auditlog', 'SYSTEM');
