package net._139130;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-07T09:07:38.523+08:00
 * Generated source version: 3.4.3
 */
@WebService(targetNamespace = "http://www.139130.net", name = "WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceSoap {

    @WebMethod(operationName = "GetResponse", action = "http://www.139130.net/GetResponse")
    @RequestWrapper(localName = "GetResponse", targetNamespace = "http://www.139130.net", className = "net._139130.GetResponse")
    @ResponseWrapper(localName = "GetResponseResponse", targetNamespace = "http://www.139130.net", className = "net._139130.GetResponseResponse")
    @WebResult(name = "GetResponseResult", targetNamespace = "http://www.139130.net")
    public java.util.List<net._139130.MTResponse> getResponse(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password,
            @WebParam(name = "PageSize", targetNamespace = "http://www.139130.net")
                    int pageSize
    );

    @WebMethod(operationName = "SetMedias", action = "http://www.139130.net/SetMedias")
    @RequestWrapper(localName = "SetMedias", targetNamespace = "http://www.139130.net", className = "net._139130.SetMedias")
    @ResponseWrapper(localName = "SetMediasResponse", targetNamespace = "http://www.139130.net", className = "net._139130.SetMediasResponse")
    @WebResult(name = "SetMediasResult", targetNamespace = "http://www.139130.net")
    public java.util.List<net._139130.MediaItems> setMedias(

            @WebParam(name = "fullPath", targetNamespace = "http://www.139130.net")
                    java.lang.String fullPath
    );

    @WebMethod(operationName = "Post", action = "http://www.139130.net/Post")
    @RequestWrapper(localName = "Post", targetNamespace = "http://www.139130.net", className = "net._139130.Post")
    @ResponseWrapper(localName = "PostResponse", targetNamespace = "http://www.139130.net", className = "net._139130.PostResponse")
    @WebResult(name = "PostResult", targetNamespace = "http://www.139130.net")
    public net._139130.GsmsResponse post(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password,
            @WebParam(name = "mtpack", targetNamespace = "http://www.139130.net")
                    net._139130.MTPacks mtpack
    );

    @WebMethod(operationName = "FindReport", action = "http://www.139130.net/FindReport")
    @RequestWrapper(localName = "FindReport", targetNamespace = "http://www.139130.net", className = "net._139130.FindReport")
    @ResponseWrapper(localName = "FindReportResponse", targetNamespace = "http://www.139130.net", className = "net._139130.FindReportResponse")
    @WebResult(name = "FindReportResult", targetNamespace = "http://www.139130.net")
    public java.util.List<net._139130.MTReport> findReport(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password,
            @WebParam(name = "batchid", targetNamespace = "http://www.139130.net")
                    java.lang.String batchid,
            @WebParam(name = "mobile", targetNamespace = "http://www.139130.net")
                    java.lang.String mobile,
            @WebParam(name = "pageindex", targetNamespace = "http://www.139130.net")
                    int pageindex,
            @WebParam(name = "flag", targetNamespace = "http://www.139130.net")
                    int flag
    );

    @WebMethod(operationName = "ModifyPassword", action = "http://www.139130.net/ModifyPassword")
    @RequestWrapper(localName = "ModifyPassword", targetNamespace = "http://www.139130.net", className = "net._139130.ModifyPassword")
    @ResponseWrapper(localName = "ModifyPasswordResponse", targetNamespace = "http://www.139130.net", className = "net._139130.ModifyPasswordResponse")
    @WebResult(name = "ModifyPasswordResult", targetNamespace = "http://www.139130.net")
    public int modifyPassword(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "old_password", targetNamespace = "http://www.139130.net")
                    java.lang.String oldPassword,
            @WebParam(name = "new_password", targetNamespace = "http://www.139130.net")
                    java.lang.String newPassword
    );

    @WebMethod(operationName = "PostMass", action = "http://www.139130.net/PostMass")
    @RequestWrapper(localName = "PostMass", targetNamespace = "http://www.139130.net", className = "net._139130.PostMass")
    @ResponseWrapper(localName = "PostMassResponse", targetNamespace = "http://www.139130.net", className = "net._139130.PostMassResponse")
    @WebResult(name = "PostMassResult", targetNamespace = "http://www.139130.net")
    public int postMass(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password,
            @WebParam(name = "mobiles", targetNamespace = "http://www.139130.net")
                    java.util.List<java.lang.String> mobiles,
            @WebParam(name = "content", targetNamespace = "http://www.139130.net")
                    java.lang.String content,
            @WebParam(name = "subid", targetNamespace = "http://www.139130.net")
                    java.lang.String subid,
            @WebParam(name = "orgCode", targetNamespace = "http://www.139130.net")
                    java.lang.String orgCode,
            @WebParam(name = "msgFmt", targetNamespace = "http://www.139130.net")
                    int msgFmt
    );

    @WebMethod(operationName = "FindResponse", action = "http://www.139130.net/FindResponse")
    @RequestWrapper(localName = "FindResponse", targetNamespace = "http://www.139130.net", className = "net._139130.FindResponse")
    @ResponseWrapper(localName = "FindResponseResponse", targetNamespace = "http://www.139130.net", className = "net._139130.FindResponseResponse")
    @WebResult(name = "FindResponseResult", targetNamespace = "http://www.139130.net")
    public java.util.List<net._139130.MTResponse> findResponse(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password,
            @WebParam(name = "batchid", targetNamespace = "http://www.139130.net")
                    java.lang.String batchid,
            @WebParam(name = "mobile", targetNamespace = "http://www.139130.net")
                    java.lang.String mobile,
            @WebParam(name = "pageindex", targetNamespace = "http://www.139130.net")
                    int pageindex,
            @WebParam(name = "flag", targetNamespace = "http://www.139130.net")
                    int flag
    );

    @WebMethod(operationName = "GetReport", action = "http://www.139130.net/GetReport")
    @RequestWrapper(localName = "GetReport", targetNamespace = "http://www.139130.net", className = "net._139130.GetReport")
    @ResponseWrapper(localName = "GetReportResponse", targetNamespace = "http://www.139130.net", className = "net._139130.GetReportResponse")
    @WebResult(name = "GetReportResult", targetNamespace = "http://www.139130.net")
    public java.util.List<net._139130.MTReport> getReport(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password,
            @WebParam(name = "PageSize", targetNamespace = "http://www.139130.net")
                    int pageSize
    );

    @WebMethod(operationName = "PostSingle", action = "http://www.139130.net/PostSingle")
    @RequestWrapper(localName = "PostSingle", targetNamespace = "http://www.139130.net", className = "net._139130.PostSingle")
    @ResponseWrapper(localName = "PostSingleResponse", targetNamespace = "http://www.139130.net", className = "net._139130.PostSingleResponse")
    @WebResult(name = "PostSingleResult", targetNamespace = "http://www.139130.net")
    public int postSingle(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password,
            @WebParam(name = "mobile", targetNamespace = "http://www.139130.net")
                    java.lang.String mobile,
            @WebParam(name = "content", targetNamespace = "http://www.139130.net")
                    java.lang.String content,
            @WebParam(name = "subid", targetNamespace = "http://www.139130.net")
                    java.lang.String subid,
            @WebParam(name = "orgCode", targetNamespace = "http://www.139130.net")
                    java.lang.String orgCode,
            @WebParam(name = "msgFmt", targetNamespace = "http://www.139130.net")
                    int msgFmt
    );

    @WebMethod(operationName = "PostGroup", action = "http://www.139130.net/PostGroup")
    @RequestWrapper(localName = "PostGroup", targetNamespace = "http://www.139130.net", className = "net._139130.PostGroup")
    @ResponseWrapper(localName = "PostGroupResponse", targetNamespace = "http://www.139130.net", className = "net._139130.PostGroupResponse")
    @WebResult(name = "PostGroupResult", targetNamespace = "http://www.139130.net")
    public int postGroup(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password,
            @WebParam(name = "mssages", targetNamespace = "http://www.139130.net")
                    java.util.List<net._139130.MessageData> mssages,
            @WebParam(name = "subid", targetNamespace = "http://www.139130.net")
                    java.lang.String subid
    );

    @WebMethod(operationName = "GetAccountInfo", action = "http://www.139130.net/GetAccountInfo")
    @RequestWrapper(localName = "GetAccountInfo", targetNamespace = "http://www.139130.net", className = "net._139130.GetAccountInfo")
    @ResponseWrapper(localName = "GetAccountInfoResponse", targetNamespace = "http://www.139130.net", className = "net._139130.GetAccountInfoResponse")
    @WebResult(name = "GetAccountInfoResult", targetNamespace = "http://www.139130.net")
    public net._139130.AccountInfo getAccountInfo(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password
    );

    @WebMethod(operationName = "GetBusinessType", action = "http://www.139130.net/GetBusinessType")
    @RequestWrapper(localName = "GetBusinessType", targetNamespace = "http://www.139130.net", className = "net._139130.GetBusinessType")
    @ResponseWrapper(localName = "GetBusinessTypeResponse", targetNamespace = "http://www.139130.net", className = "net._139130.GetBusinessTypeResponse")
    @WebResult(name = "GetBusinessTypeResult", targetNamespace = "http://www.139130.net")
    public java.util.List<net._139130.BusinessType> getBusinessType(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password
    );

    @WebMethod(operationName = "GetMOMessage", action = "http://www.139130.net/GetMOMessage")
    @RequestWrapper(localName = "GetMOMessage", targetNamespace = "http://www.139130.net", className = "net._139130.GetMOMessage")
    @ResponseWrapper(localName = "GetMOMessageResponse", targetNamespace = "http://www.139130.net", className = "net._139130.GetMOMessageResponse")
    @WebResult(name = "GetMOMessageResult", targetNamespace = "http://www.139130.net")
    public java.util.List<net._139130.MOMsg> getMOMessage(

            @WebParam(name = "account", targetNamespace = "http://www.139130.net")
                    java.lang.String account,
            @WebParam(name = "password", targetNamespace = "http://www.139130.net")
                    java.lang.String password,
            @WebParam(name = "pagesize", targetNamespace = "http://www.139130.net")
                    int pagesize
    );
}
